### ISSUE TITLE
anything wrong with AWCY encoding time?

### ISSUE THREAD

**Issue by stan1958** [xiph/rav1e#1010]
https://beta.arewecompressedyet.com/?job=master-f82655563521fffe9f5fbb6f3a0cb9b5a5e2d43d&job=master-4cec397518ccd134e4b62bd6c9dc05f99bff5cfd&job=master-820a640e0bddd4f23784da8dd1d532c12c68d963&job=master-3da4937e15d66b2e3888e5116c61c5e12dd62dd2&job=master-36d075f299cb82126877ba52e85adf408d0ca9e0&job=master-bc6917585d6399a3ad6737a82c7cd39f9078713d&job=master-f515062cffc6a78188a9e5a4d017134237985ec5

**Comment by tdaede** [comment]
Looks like par_iter totally decimates encoding time on AWCY.

@lu-zero thoughts? How does it determine number of threads?

**Comment by lu-zero** [comment]
Looks like awcy has way too many cores.

As local bandaid could you please add `RAYON_NUM_THREADS=4` to the environment?

**Comment by lu-zero** [comment]
#1011 provides a non-env override to size properly the thread pool
