### ISSUE TITLE
Document & distribute speed functions

### ISSUE THREAD

**Issue by EwoutH** [xiph/rav1e#1015]
I encoded 120 frames of the [Morocco](https://www.youtube.com/watch?v=hVvEISFw9w0&t=2s) clip with rav1e f2aa4c6 from speed 6 to 0 and found some [strange results](https://docs.google.com/spreadsheets/d/1JpPz-Tvj8OO9VGyv-0_VQQRlMVpChuwYeRwr3L3Ss1E/edit#gid=1747162432):

- Speed 6 and 5 are completely identical in result, while the latter is somewhat slower (probably measurement error).
- Speed 2 produces larger files than speed 3 while 4% slower.
- Speed 1 is about equal size to speed 3 while 14% slower.

![rav1e-fps-size](https://user-images.githubusercontent.com/15776622/53012233-b1623500-3442-11e9-8e38-9819d6d755ea.png)

This was of course a single, short clip, tonight I will try some more with different scene's and motion patterns. 

I think two main changes are needed:
- Document speed features. I would propose a large table with the different speed settings on the X-axis and the different speed features on the Y-axis, where each cell states if it's enabled if not
- Better distribute speed functions over the different settings. The gap between 1 and 0 and between 5 and 4 is way to large, while the others are very small.

**Comment by EwoutH** [comment]
Based on [api.rs](https://github.com/xiph/rav1e/blob/master/src/api.rs) I've composed the [following table](https://docs.google.com/spreadsheets/d/1Z_nkVZqc6CZeFBtFptugzspX-7-qf9nC1pHqfJ4mE60/edit?usp=sharing). Can someone confirm this is correct?

|                      |    -s 0    |    -s 1    |       -s 2       |       -s 3       |  -s 4  |  -s 5  |  -s 6  |  -s 7  |  -s 8  |  -s 9  |  -s 10 |
|----------------------|:----------:|:----------:|:----------------:|:----------------:|:------:|:------:|:------:|:------:|:------:|:------:|:------:|
| min_block_size       |     4X4    |     4X4    |        8X8       |       16X16      |  32X32 |  64X64 |  64X64 |  64X64 |  64X64 |  64X64 |  64X64 |
| multiref             |    TRUE    |    TRUE    |       TRUE       |       FALSE      |  FALSE |  FALSE |  FALSE |  FALSE |  FALSE |  FALSE |  FALSE |
| fast_deblock         |    FALSE   |    FALSE   |       FALSE      |       FALSE      |  TRUE  |  TRUE  |  TRUE  |  TRUE  |  TRUE  |  TRUE  |  TRUE  |
| reduced_tx_set       |    FALSE   |    FALSE   |       TRUE       |       TRUE       |  TRUE  |  TRUE  |  TRUE  |  TRUE  |  TRUE  |  TRUE  |  TRUE  |
| tx_domain_distortion |    FALSE   |    FALSE   |       FALSE      |       FALSE      |  TRUE  |  TRUE  |  TRUE  |  TRUE  |  TRUE  |  TRUE  |  TRUE  |
| encode_bottomup      |    TRUE    |    FALSE   |       FALSE      |       FALSE      |  FALSE |  FALSE |  FALSE |  FALSE |  FALSE |  FALSE |  FALSE |
| rdo_tx_decision      |    TRUE    |    TRUE    |       TRUE       |       TRUE       |  FALSE |  FALSE |  FALSE |  FALSE |  FALSE |  FALSE |  FALSE |
| prediction_modes     | ComplexAll | ComplexAll | ComplexKeyframes | ComplexKeyframes | Simple | Simple | Simple | Simple | Simple | Simple | Simple |
| include_near_mvs     |    TRUE    |    TRUE    |       TRUE       |       FALSE      |  FALSE |  FALSE |  FALSE |  FALSE |  FALSE |  FALSE |  FALSE |
| no_scene_detection   |    FALSE   |    FALSE   |       FALSE      |       FALSE      |  FALSE |  FALSE |  FALSE |  FALSE |  FALSE |  FALSE |  TRUE  |

**Comment by shssoichiro** [comment]
Yes, currently speed 5-10 are all identical. I've been actively benchmarking the various settings and plan to rebalance and document the speed settings once benchmarking is complete. So far discussion has only been on IRC, so thank you for making a ticket to officially track this.
