### ISSUE TITLE
Participate in MSU Annual Video Codecs Comparison 2019

### ISSUE THREAD

**Issue by EwoutH** [xiph/rav1e#1019]
Moscow State University is soon (deadline March 1) starting with it's yearly codec review, it would be great to have rav1e included in it.
- [MSU Annual Video Codecs Comparison 2019: Call for codecs](http://www.compression.ru/video/codec_comparison/call_for_codecs_19.html)

**Comment by tdaede** [comment]
They use VBR mode, so we'd need to do some quick last minute work to make VBR mode look good.

**Comment by tdaede** [comment]
Unfortunately VBR still isn't good enough to submit :/
