### ISSUE TITLE
Encoding fails for a clip with lots of black frames when using a target bitrate (quantizer dropping to 0)

### ISSUE THREAD

**Issue by gnafuthegreat** [xiph/rav1e#1020]
Running this:

`rav1e -o tfe-columbia-1080p-rav1e-1000k.ivf -b 1000 tfe-columbia-1080p.y4m`

Results in this error:

<pre>1920x1080 @ 24000/1001 fps
encoded 33 frames, 0.067 fps, 32.52 Kb/s                    thread 'main' panicked at 'assertion failed: fi.base_q_idx > 0', src/header.rs:625:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic
   6: rav1e::encoder::write_obus
   7: rav1e::encoder::encode_frame
   8: rav1e::api::Context::receive_packet
   9: rav1e::main
  10: std::rt::lang_start::{{closure}}
  11: std::panicking::try::do_call
  12: __rust_maybe_catch_panic
  13: std::rt::lang_start_internal
  14: main
  15: __libc_start_main
  16: _start</pre>

Source file is available here:

https://themayhaks.com/~gideon/tfe-columbia-1080p.y4m.xz

This is happening with d78dc36331581ae1416f7df6deffd0c441582907.

**Comment by gnafuthegreat** [comment]
I wonder if this is an issue with so many black frames in succession triggering the quantizer to be 0, which is of course not currently supported.  Is it possible the new rate control is having trouble with so many black frames in a row, going to lower and lower quantizers because it can and then causing an issue when it reaches 0?

**Comment by tdaede** [comment]
Yeah basically, there needs to be a clamp of the quantizer to 1.
