### ISSUE TITLE
Add CDEF support.

### ISSUE THREAD

**Issue by tdaede** [xiph/rav1e#105]
For now, set a constant CDEF level, and simply call the C CDEF implementation.

**Comment by tmatth** [comment]
I'm working on this in the https://github.com/xiph/rav1e/tree/feature/cdef branch, still need to apply cdef for chroma, handle non-4:2:0 and non-multiple of SB size cases.

**Comment by tmatth** [comment]
https://tools.ietf.org/id/draft-midtskogen-netvc-cdef-00.html

**Comment by tmatth** [comment]
TODO: replace values in the padding with CDEF_VERY_LARGE.

**Comment by xiphmont** [comment]
Full bitstream support implemented, encoder does not yet use much of the capability, though it's on and running by default.  Better integration to come, but the support is now all there.
