### ISSUE TITLE
Frame flushing regression - last sub GOP constructed incorrectly

### ISSUE THREAD

**Issue by SmilingWolf** [xiph/rav1e#1081]
I perform semi-regular encoder benchmarks on a set of anime-centered clips.
While preparing this month's report I noticed a massive drop in BD rate (up to 12% less efficiency).

I bisected the commits between the last "good" tests, performed on commit 64b9f501, and the one where I first noticed the drop, commit 57e4f926. Turned out the bad commit is 3202bf70 (ping @shssoichiro):
```
# sh bd_rate.sh /c/Users/utente/Desktop/regressionTesting/rav1e-0.1.0-1219-be245fc0.out /c/Users/utente/Desktop/regressionTesting/rav1e-0.1.0-1222-3202bf70.out
        RATE (%) DSNR (dB)
 MSSSIM 12.5511 -0.502696
PSNRHVS 12.6137 -0.699069
  HVMAF 12.4122 -1.06813
```
BD rate report up to the commit before the bad one:
```
# sh bd_rate.sh /c/Users/utente/Desktop/regressionTesting/rav1e-0.1.0-977-64b9f501.out /c/Users/utente/Desktop/regressionTesting/rav1e-0.1.0-1219-be245fc0.out
        RATE (%) DSNR (dB)
 MSSSIM -3.70748 0.161186
PSNRHVS -3.5851 0.215709
  HVMAF -5.32006 0.524379
```
BD rate between 64b9f501 and a more recent one (d3b81ca1):
```
# sh bd_rate.sh /c/Users/utente/Desktop/regressionTesting/rav1e-0.1.0-977-64b9f501.out /c/Users/utente/Desktop/regressionTesting/rav1e-0.1.0-1768-d3b81ca1.out
        RATE (%) DSNR (dB)
 MSSSIM 9.60217 -0.394358
PSNRHVS 9.65825 -0.547198
  HVMAF 6.88864 -0.659584
```
The regression can be reliably replicated on a variety anime clips with different resolutions (1280x720, 1920x1080), so I'm sure it's not just a pathological case with this particular clip.

Note that the regression is not nearly as bad on more "real life" content, for example ToS:
```
# sh bd_rate.sh /c/Users/utente/Desktop/codecComparison/TearsOfSteel/statistics/rav1e-0.1.0-977-64b9f501.out /c/Users/utente/Desktop/codecComparison/TearsOfSteel/statistics/rav1e-0.1.0-1726-57e4f926.out
        RATE (%) DSNR (dB)
 MSSSIM 0.557544 -0.0240243
PSNRHVS 0.898872 -0.0503387
  HVMAF -0.0647014 -0.0338935
```

I'm using the AppVeyor Win64 builds in an MSYS2 environment on Win7 64bits.
The clip used during bisection can be found here (FFV1 video in MKV container): https://mega.nz/#!QwhCxIob!I_aWvxX_igulPzZw9nr__nxvr7X-jYPcOlCLUfqL_-I
Cmdlines used during bisection:
`seq -w 112 16 160 | xargs -n1 -P6 -I {} ./rav1e-0.1.0-1222-3202bf70.exe --low_latency false -o rav1e-0.1.0-1222-3202bf70/test.rav1e.cq{}.ivf --quantizer {} -s 2 --tune Psnr orig.i420.y4m`

**Comment by SmilingWolf** [comment]
I've done some decoding tests with ffmpeg to compare a "good" file with a "bad" one.
It looks like the queue doesn't interact well with frame reordering, and inserts too many frames.
Somehow this doesn't break decoding or even change the number of total frames, but overbloats the output file. It looks like it always tries to complete a frame pyramid.

For example:
good encode:
```
[NULL @ 00000000005c5140] Frame 16:  size 1280x720  upscaled 1280  render 1280x720  subsample 2x2  bitdepth 8  tiles 1x1.
[NULL @ 00000000005c5140] Frame 14:  size 1280x720  upscaled 1280  render 1280x720  subsample 2x2  bitdepth 8  tiles 1x1.
[NULL @ 00000000005c5140] Frame 13:  size 1280x720  upscaled 1280  render 1280x720  subsample 2x2  bitdepth 8  tiles 1x1.
[NULL @ 00000000005c5140] Frame 15:  size 1280x720  upscaled 1280  render 1280x720  subsample 2x2  bitdepth 8  tiles 1x1.
[NULL @ 00000000005c5140] Frame 18:  size 1280x720  upscaled 1280  render 1280x720  subsample 2x2  bitdepth 8  tiles 1x1.
[NULL @ 00000000005c5140] Frame 17:  size 1280x720  upscaled 1280  render 1280x720  subsample 2x2  bitdepth 8  tiles 1x1.
[NULL @ 00000000005c5140] Frame 19:  size 1280x720  upscaled 1280  render 1280x720  subsample 2x2  bitdepth 8  tiles 1x1.
```

bad encode:
```
[NULL @ 00000000004e5140] Frame 16:  size 1280x720  upscaled 1280  render 1280x720  subsample 2x2  bitdepth 8  tiles 1x1.
[NULL @ 00000000004e5140] Frame 14:  size 1280x720  upscaled 1280  render 1280x720  subsample 2x2  bitdepth 8  tiles 1x1.
[NULL @ 00000000004e5140] Frame 13:  size 1280x720  upscaled 1280  render 1280x720  subsample 2x2  bitdepth 8  tiles 1x1.
[NULL @ 00000000004e5140] Frame 15:  size 1280x720  upscaled 1280  render 1280x720  subsample 2x2  bitdepth 8  tiles 1x1.
[NULL @ 00000000004e5140] Frame 20:  size 1280x720  upscaled 1280  render 1280x720  subsample 2x2  bitdepth 8  tiles 1x1.
[NULL @ 00000000004e5140] Frame 18:  size 1280x720  upscaled 1280  render 1280x720  subsample 2x2  bitdepth 8  tiles 1x1.
[NULL @ 00000000004e5140] Frame 17:  size 1280x720  upscaled 1280  render 1280x720  subsample 2x2  bitdepth 8  tiles 1x1.
[NULL @ 00000000004e5140] Frame 19:  size 1280x720  upscaled 1280  render 1280x720  subsample 2x2  bitdepth 8  tiles 1x1.
```
Notice how frame 20 is not present in the good encode, but present in the bad one.

It doesn't stop there, sometimes it tries to build a pyramid when there are not enough frames, too:
good encode:
```
[NULL @ 00000000005c5140] Frame 16:  size 1280x720  upscaled 1280  render 1280x720  subsample 2x2  bitdepth 8  tiles 1x1.
[NULL @ 00000000005c5140] Frame 14:  size 1280x720  upscaled 1280  render 1280x720  subsample 2x2  bitdepth 8  tiles 1x1.
[NULL @ 00000000005c5140] Frame 13:  size 1280x720  upscaled 1280  render 1280x720  subsample 2x2  bitdepth 8  tiles 1x1.
[NULL @ 00000000005c5140] Frame 15:  size 1280x720  upscaled 1280  render 1280x720  subsample 2x2  bitdepth 8  tiles 1x1.
[NULL @ 00000000005c5140] Frame 17:  size 1280x720  upscaled 1280  render 1280x720  subsample 2x2  bitdepth 8  tiles 1x1.
```
bad encode:
```
[NULL @ 00000000004e5140] Frame 16:  size 1280x720  upscaled 1280  render 1280x720  subsample 2x2  bitdepth 8  tiles 1x1.
[NULL @ 00000000004e5140] Frame 14:  size 1280x720  upscaled 1280  render 1280x720  subsample 2x2  bitdepth 8  tiles 1x1.
[NULL @ 00000000004e5140] Frame 13:  size 1280x720  upscaled 1280  render 1280x720  subsample 2x2  bitdepth 8  tiles 1x1.
[NULL @ 00000000004e5140] Frame 15:  size 1280x720  upscaled 1280  render 1280x720  subsample 2x2  bitdepth 8  tiles 1x1.
[NULL @ 00000000004e5140] Frame 20:  size 1280x720  upscaled 1280  render 1280x720  subsample 2x2  bitdepth 8  tiles 1x1.
[NULL @ 00000000004e5140] Frame 18:  size 1280x720  upscaled 1280  render 1280x720  subsample 2x2  bitdepth 8  tiles 1x1.
[NULL @ 00000000004e5140] Frame 17:  size 1280x720  upscaled 1280  render 1280x720  subsample 2x2  bitdepth 8  tiles 1x1.
```
Notice the surplus Frame 18, missing Frame 19, and surplus Frame 20

Full logs attached
[rav1e-0.1.0-1219-be245fc0.ffmpegLog.txt](https://github.com/xiph/rav1e/files/2941097/rav1e-0.1.0-1219-be245fc0.ffmpegLog.txt)
[rav1e-0.1.0-1222-3202bf70.ffmpegLog.txt](https://github.com/xiph/rav1e/files/2941098/rav1e-0.1.0-1222-3202bf70.ffmpegLog.txt)

**Comment by shssoichiro** [comment]
@SmilingWolf Do you see identical output from ffmpeg in the latest master to what you are seeing in 3202bf7? There have been a few commits with refactors and bugfixes to the lookahead since that commit.

**Comment by SmilingWolf** [comment]
Unfortunately yes, I do see the same kind of errors. Log from file encoded with d3b81ca1 attached.
[rav1e-0.1.0-1768-d3b81ca1.ffmpegLog.txt](https://github.com/xiph/rav1e/files/2941171/rav1e-0.1.0-1768-d3b81ca1.ffmpegLog.txt)

**Comment by shssoichiro** [comment]
I'm questioning whether 3202bf7 is truly the culprit. I've gone through the changes in that commit extensively and found no difference that would cause this. I also get the same MD5 for the output from that commit and the one immediately preceding it.

I will do some more research and see if I can find more information.

**Comment by SmilingWolf** [comment]
I thought I might have mixed something while bisecting, but it's not the case.
I just finished re-running the encodes, calculating the metrics and the ffmpeg decoding tests: same result as the last time.
I'm attaching everything: executables used, scripts with the cmdlines, quality measurements and ffmpeg decoding logs.
[issue1081.zip](https://github.com/xiph/rav1e/files/2967238/issue1081.zip)

Random thought: are you testing on windows or linux? Could it be some component is bugged or behaves differently depending on the platform? It's a wild guess, but I've seen it happen with python

**Comment by tdaede** [comment]
It's also dependent on the # of frames in the clip - if you picked a clip to test on that was a convenient length, it won't show.

**Comment by shssoichiro** [comment]
I was able to reproduce with the fileset you sent, and the original input file, without limiting the number of frames. So @tdaede is probably correct. I'll look into this some more and see if I can find a fix now.

**Comment by lu-zero** [comment]
Here some notes on what I have half done:
- [ ] move the encoding loop in a stand alone thread (needed by #689)
- [ ] feed the frames to the scenechange detector, queue them up until:
  - the scenechange is detected
  - the limit has been hit
  - a flush has been hit
- [ ] feed the group to the reordering logic and prepare the frame-invariants
- [ ] encode the group

**Comment by ycho** [comment]
Thanks for reporting and sharing the possible bugs.
In order to isolate the possible culprits, I think It might be helpful to turn off some of encoding features or options, such as frame reordering, multi reference, and scene change detection.

**Comment by dwbuiten** [comment]
@lu-zero won't this logic need to be changed again once scene detection is cost-based (i.e. no longer entirely decoupled)?

**Comment by SmilingWolf** [comment]
> 
> 
> Thanks for reporting and sharing the possible bugs.
> In order to isolate the possible culprits, I think It might be helpful to turn off some of encoding features or options, such as frame reordering, multi reference, and scene change detection.

Ok, I will do so. I know frame reordering is controlled by low_latency and scene detection can be turned off by having max kexyframe interval equal to min kexyframe interval.
How would I go about turning off multi-reference frames? Is that a flag that can only be deactivated at build time?

**Comment by shssoichiro** [comment]
@SmilingWolf Multiref is automatically enabled when low latency is false. Multiref can be enabled on its own when low latency is true--you could use `--speed-test multiref --low_latency true` to enable that combination.

**Comment by ycho** [comment]
Since the problem occurs in "SUB GOP", I think we need to keep frame reorder enabled.
And it seems that there is no options to turn off multi-ref with keeping frame reorder turned on.
Thus, we will need add a new encoder control switch which can turn on/off frame reorder only (I believe this might have been there but removed since meaningless from the speed level viewpoint), or hardcode it, setting "multiref = false;" at
https://github.com/xiph/rav1e/blob/master/src/encoder.rs#L655

**Comment by SmilingWolf** [comment]
I received the notification and rushed to test.
In my tests it doesn't look like the problem has been resolved.
I'm attaching a couple of files: the encoded one, and the FFmpeg log.
The encode was produced this morning with rav1e 70005e35 (build 2106 on AppVeyor).
The cmdline:
`rav1e --low_latency false -o test.rav1e.cq112.ivf --quantizer 112 -s 2 --tune Psnr orig.i420.y4m`

Small excerpt (lines 389-392):
```
[NULL @ 00000000004c9480] Frame 28:  size 1280x720  upscaled 1280  render 1280x720  subsample 2x2  bitdepth 8  tiles 1x1.
[NULL @ 00000000004c9480] Frame 26:  size 1280x720  upscaled 1280  render 1280x720  subsample 2x2  bitdepth 8  tiles 1x1.
[NULL @ 00000000004c9480] Frame 25:  size 1280x720  upscaled 1280  render 1280x720  subsample 2x2  bitdepth 8  tiles 1x1.
[NULL @ 00000000004c9480] Frame 0:  size 1280x720  upscaled 1280  render 1280x720  subsample 2x2  bitdepth 8  tiles 1x1.
```

[2106-test.rav1e.cq112.ffmpeg.txt](https://github.com/xiph/rav1e/files/3047125/2106-test.rav1e.cq112.ffmpeg.txt)
[test.rav1e.cq112.zip](https://github.com/xiph/rav1e/files/3047127/test.rav1e.cq112.zip)

**Comment by EwoutH** [comment]
Can we reopen this?

**Comment by SmilingWolf** [comment]
Trying to talk on #daala but it looks like I'm muted

**Comment by tdaede** [comment]
In the uploaded ivf, the problem is pretty easily visible just comparing the number of OBU_TILE_GROUPS and temporal units (they should be identical):
```
$ ~/sandbox/aom/cmake-build/tools/dump_obu ~/test.rav1e.cq112.ivf | grep Temporal | wc -l
480
$ ~/sandbox/aom/cmake-build/tools/dump_obu ~/test.rav1e.cq112.ivf | grep OBU_TILE_GROUP | wc -l
514
```

**Comment by lu-zero** [comment]
https://github.com/xiph/rav1e/pull/1392 makes the problem with the reordering logic more apparent.

**Comment by tdaede** [comment]
Reencoding on master shows the problem is gone:

[thomas@kaban rav1e]$ ~/sandbox/aom/cmake-build/tools/dump_obu test.rav1e.cq112.ivf | grep Temporal | wc -l
480
[thomas@kaban rav1e]$ ~/sandbox/aom/cmake-build/tools/dump_obu test.rav1e.cq112.ivf | grep OBU_TILE_GROUP | wc -l
480

Thanks to @YaLTeR for fixing this longstanding bug!

**Comment by rzumer** [comment]
Presumably solved by https://github.com/xiph/rav1e/commit/27647f6ebd86c91410d1390fbeca78f46e190bea.

**Comment by ycho** [comment]
Yay, this has been finally fixed! Beers to folk(s) who fixed this.
