### ISSUE TITLE
Add fuzz testing

### ISSUE THREAD

**Issue by tmatth** [xiph/rav1e#115]
Fuzzing raw input is generally easier, but fuzzing the decisions would be more useful (but probably more involved/intrusive).

Some potentially helpful links:

https://github.com/pingcap/fail-rs
https://rust-fuzz.github.io/book/introduction.html
https://github.com/BurntSushi/quickcheck
https://github.com/altsysrq/proptest

and might as well add this link from @lu-zero for posterity:
https://doc.rust-lang.org/std/num/struct.Wrapping.html

**Comment by lu-zero** [comment]
[fail-rs](https://github.com/pingcap/fail-rs) let us leverage failpoints to force decisions that would be hard to trigger by simple input fuzzing.

[proptest](https://github.com/altsysrq/proptest) and [quickcheck](https://github.com/BurntSushi/quickcheck) can simulate fuzzing effectively, while `cargo-fuzz` is sort of easy to access the functionalities offered by LLVM libFuzzer.

**Comment by lu-zero** [comment]
Currently the decode/integration tests use random inputs, we can possibly expand them using `cargo-fuzz`.
