### ISSUE TITLE
Setting keyint to any value less than 12 makes rav1e infiniloop. 

### ISSUE THREAD

**Issue by lu-zero** [xiph/rav1e#1164]
The infiniloop is in`set_frame_properties`. 

Disabling the scene detection code makes the problem go away.

**Comment by kodabb** [comment]
@dwbuiten has a patch for this

**Comment by dwbuiten** [comment]
it doesnt do quite this... it's not a full fix.

**Comment by lu-zero** [comment]
See https://github.com/xiph/rav1e/issues/1081 for a sample triggering it

**Comment by rzumer** [comment]
Cannot reproduce on master.
```
$ ffmpeg -i orig.i420.mkv orig.y4m
$ cargo run --release --bin rav1e -- orig.y4m --keyint 10 -s 1 -o enc_file.ivf
    Finished release [optimized] target(s) in 1.79s
     Running `target\release\rav1e.exe orig.y4m --keyint 10 -s 1 -o enc_file.ivf`
1280x720 @ 24000/1001 fps
encoded 378 frames, 0.162 fps, 1563.00 Kb/s
```

**Comment by rzumer** [comment]
Presumably solved by https://github.com/xiph/rav1e/commit/27647f6ebd86c91410d1390fbeca78f46e190bea.
