### ISSUE TITLE
Directional intra prediction broken with tx partition

### ISSUE THREAD

**Issue by ycho** [xiph/rav1e#1200]
Directional intra prediction failis with: tx split to any levels, i.e. 1 or 2.

**Comment by tdaede** [comment]
Can you post a test case?

**Comment by ycho** [comment]
You can reproduce this two ways,
1) rebase https://github.com/rom1v/rav1e/commits/tiling.100 on master 70005e353aa8ce21e3ecd257c927f71d4012a117,
then run
./target/release/rav1e ~/sequences/objective-1-fast/KristenAndSara_1280x720_60f.y4m -o test.ivf -r test_rec.y4m --quantizer 60 --speed=0 --limit=3 --tile-rows-log2 1 --tile-cols-log2 1
then, assert fails at:
debug_assert!((tx_size, tx_type) == 
rdo_tx_size_type(fi, fs, cw, bsize, bo, mode_luma, ref_frames, mvs, skip)); 

2) Hard code to enable tx partition depth = 2,
i.e. in rdo_tx_size_type(),
let rdo_tx_depth = if do_rdo_tx_size { 1 } else { 0 };
change 1 ==> 2, which enables partition go one more level, i.e depth from 1 to 2.
The same assert will fail.

**Comment by ycho** [comment]
@tdaede, also I was seeing that the assert fails only for the rectangular partitions!

**Comment by ycho** [comment]
It can be reproducible for speed=0,1,2,3, i.e. when tx rdo is enabled.
./target/release/rav1e ~/sequences/objective-1-fast/KristenAndSara_1280x720_60f.y4m -o test.ivf -r 
test_rec.y4m --quantizer 60 --speed=3 --limit=1 --tune=Psnr
- I have tried w/ and w/o "--tune=Psnr" and tx_domain_dist off (by hard coding) but fails.
- One way I found to stop is to disable tx partition, i.e. set '2' to '0' in :
"let rdo_tx_depth = if do_rdo_tx_size { 2 } else { 0 };" in rdo_tx_size_type()

**Comment by rainliu** [comment]
I checked the code, one of reasons that directional intra predictions are broken is because of has_bl() and has_tr() didn't consider PARTITION_TYPE for HORZ and VERT split mode. For example, for 16x8 HORZ split, if tx size is 4x4, then has_br() and has_tr() return wrong value for non-first column or row 4x4 blocks.

**Comment by ycho** [comment]
> I checked the code, one of reasons that directional intra predictions are broken is because of has_bl() and has_tr() didn't consider PARTITION_TYPE for HORZ and VERT split mode. For example, for 16x8 HORZ split, if tx size is 4x4, then has_br() return wrong value for non-first column 4x4 blocks.

Hi- thanks a lot for trying this.
The has_tr() and has_bl() are checking those.
https://github.com/xiph/rav1e/blob/c84872d70f7fd741d7c3c03cf44cf5e4cf1ea21d/src/partition.rs#L600 and
https://github.com/xiph/rav1e/blob/c84872d70f7fd741d7c3c03cf44cf5e4cf1ea21d/src/partition.rs#L657

I've also quickly tested again by disabling non-square partitions, then I still have desync.

commit 72c47ecfeba33b4d839c9f10584574c1ef892a9c + enabling those six of disabled directional intra prediction modes.
./target/release/rav1e ~/sequences/objective-1-fast/KristenAndSara_1280x720_60f.y4m -o test.ivf -r test_rec.y4m --quantizer 200 --speed=3 --limit    =1 --tune=Psnr

<img width="1634" alt="Screen Shot 2019-06-21 at 11 49 05 AM" src="https://user-images.githubusercontent.com/10123259/59944821-af24dd00-941a-11e9-845e-048b22242a45.png">

**Comment by ycho** [comment]
Btw, we have other desync issue going on due to CDEF, at large qp like 200, so the desync I see again with disabling non-square partition could come from it.
Hence I tested again with CDEF turned off, but desync is still there.

**Comment by rainliu** [comment]
let me show you an example, for 16x8 top hozi partition, the yellow block is 4x4, where has_bl() should return false since the bottom left block is not decoded yet.  However, inside[ get_intra_edges()](https://github.com/xiph/rav1e/blob/c84872d70f7fd741d7c3c03cf44cf5e4cf1ea21d/src/partition.rs#L515) function, it uses yellow block's x/y and tx4x4 as input to has_bl(), which never have partition information. Therefore, it always return wrong value.

![Screenshot 2019-06-21 12 39 27](https://user-images.githubusercontent.com/2069201/59947287-adaae300-9421-11e9-90f0-ccd03affc937.png)

**Comment by ycho** [comment]
Oh, I think you are correct, and what you are describing is **one** of the multiple causes as you described. Because, the desync still comes even w/o using non-square partitions.
However, what you are saying, i.e using tx block's x/y position also applies to square partition as well, i.e. we have 16x16 partition that has four of 8x8 tx blocks, correct? Then, that is another thing I need to see whether it is related to this breakage.
Again, I appreciate your time and trying to correct my thoughts! It helps a lot!

**Comment by ycho** [comment]
As a background history, around time when has_tr() and has_bl() functions were written, partition size == tx size because rav1e did not have tx partition yet.

**Comment by ycho** [comment]
> However, what you are saying, i.e using tx block's x/y position also applies to square partition as well, i.e. we have 16x16 partition that has four of 8x8 tx blocks, correct? Then, that is another thing I need to see whether it is related to this breakage.
In fact, before your comment today, I was testing whether each of 32x32 tx in 64x64 partition has correct top_right available pixels and bottom_left available pixels, i.e.
let num_avail = if y != 0 && has_tr(bo, bsize) { ...
and
let num_avail = if x != 0 && has_bl(bo, bsize) {
and it seems okay.

**Comment by ycho** [comment]
If tx partition level = 1, let rdo_tx_depth = if do_rdo_tx_size { **1** } else { 0 };  // 2 --> 1,
and disable non-square partition, then desync is gone.
(I remember this was the case before I enabled tx partition level = 2).

**Comment by ycho** [comment]
I think this issue is related to https://github.com/xiph/rav1e/issues/1221
In libaom there are two versions of has_top_right() and has_bottom_left() functions, and the one for intra prediction has the parameter, partition. So, I think reav1e is indeed missing this part.

**Comment by ycho** [comment]
> let me show you an example, for 16x8 top hozi partition, the yellow block is 4x4, where has_bl() should return false since the bottom left block is not decoded yet. However, inside[ get_intra_edges()](https://github.com/xiph/rav1e/blob/c84872d70f7fd741d7c3c03cf44cf5e4cf1ea21d/src/partition.rs#L515) function, it uses yellow block's x/y and tx4x4 as input to has_bl(), which never have partition information. Therefore, it always return wrong value.
> 
> ![Screenshot 2019-06-21 12 39 27](https://user-images.githubusercontent.com/2069201/59947287-adaae300-9421-11e9-90f0-ccd03affc937.png)

btw, in this picture, tx level partition is 2 since partition size = 16x8, and tx size = 4x4.

**Comment by ycho** [comment]
> Also, I think the bottom left block is decoded prior to the yellow 4x4 block.
> Because, 16x8 partition is first divide into two 8x8 tx blks.
> Then at 2nd level, each 8x8 tx blk split into four of 4x4 tx blks.
> So, the order of decoding 4x4 tx blocks is:
> 0 1 4 5
> 2 3 6 7
> (4 is the yellow 4x4 block).
> Then, the bottom left for yellow block 4 comes from block 3.

This was wrong! (I am dumb).
If 16x8 partition chooses two levels of tx partition, then the decode order is
0 1 2 3
4 5 6 7
i.e. raster scan, not quadtree fashion!

**Comment by rainliu** [comment]
yeah, that's the difference between VP9/AV1 and HEVC for tx block processing order.

**Comment by ycho** [comment]
As in https://github.com/xiph/rav1e/pull/1373
My plan is to disable tx partition until correct fix has landed.
Also, enable back the disabled intra prediction partition.

**Comment by ycho** [comment]
The has_top_right() and has_bottom_left() for directional intra prediction in libaom also use both bsize and tx_size, in addition to partition type info.

**Comment by ycho** [comment]
Closing this, since #1391 is expected to resolve the issue.
