### ISSUE TITLE
Publish to crates.io

### ISSUE THREAD

**Issue by lu-zero** [xiph/rav1e#1202]
Prerequisites:
- [x] Have a nasm-rs release we can use
- [x] Publish a `0.1.0` for `ivf` and `rav1e`

**Comment by rzumer** [comment]
This seems like a duplicate of #491. If that's the case, I recommend editing the opening post in that issue with the checklist appended, and closing this one.

**Comment by lu-zero** [comment]
It is not :)

**Comment by rzumer** [comment]
Then can you detail the difference, besides the fact that this issue is specifying a particular repository?
