### ISSUE TITLE
Better user experience when choosing `-I 0`

### ISSUE THREAD

**Issue by ycho** [xiph/rav1e#1211]
Encoder statistics says all re encoded as KEY, but only one frame is encoded repetitively.

**Comment by shssoichiro** [comment]
`-I 1` should give all key frames IIRC, but it seems unintuitive for `-I 0` to give this buggy behavior. It should either behave the same as `-I 1`, or throw an error saying the minimum keyframe interval is 1.

**Comment by ycho** [comment]
@shssoichiro, Thanks- Yes, -I 1 worked. But, I really intuitively thought I should use -I 0, thinking 'interval' means in-between/exclusive. :)

**Comment by rzumer** [comment]
My interpretation for interval is "each <n> frame". So with `-I 1` "each 1 frame" is a keyframe, and "each 0 frame" does not make sense. But I also agree that it would be better to handle `-I 0` either by returning an error, or by making it behave like `-I 1`.
