### ISSUE TITLE
has_top_right() or has_tr() for intra prediction might be different for inter and intra

### ISSUE THREAD

**Issue by ycho** [xiph/rav1e#1221]
This might be the reason for the breakage of direction intra prediction.

**Comment by aditj** [comment]
Hey! Is anyone working on this? If not, I'd love to :)

**Comment by ycho** [comment]
@aditj, that would be awesome! Thank you for your interest.
Currently, directional intra prediction is disabled, which I believe this fix can probably help.
Also, fyi, referencing two different functions with the same name has_top_right() in libaom would be helpful, though it is possible that they do really do the same thing.

**Comment by aditj** [comment]
Hey @ycho !  I am new to the codebase so it is a bit confusing I found the has_tr function in partition.rs, a little help would be appreciated :) . Now, how do I make two seperate functions for inter and intra frame prediction? (Do I add a function with a bit different name in the same file or something else,and what would be the difference between the functions for inter and intra mode?)

>Also, fyi, referencing two different functions with the same name has_top_right() in libaom would be helpful, though it is possible that they do really do the same thing.

Also, how are the libaom functions referenced in rav1e?

**Comment by ycho** [comment]
Currently has_tr() for inter seems working fine. However, it seems missing sth for intra prediction (you can test this by enabling the disabled directional intra pred). We can probably add some suffix to had_tr() for intra.

Rav1e does not call any of libaom functions. By ‘referencing’, I meant ‘comparing’.

**Comment by aditj** [comment]
@ycho would we want the has_top_right() for intra  to have the same functionality as [this](https://github.com/mozilla/aom/blob/46b7bb243b39929c02d6decc1bdb2e39e11540d6/av1/common/reconintra.c#L442) ?

**Comment by ycho** [comment]
@aditj, I meant this AOM normative branch source code, https://aomedia.googlesource.com/aom/+/refs/heads/av1-normative/av1/common/reconintra.c#195

**Comment by ycho** [comment]
Some more clues, that I wanted to share.
The disabled directional intra predictions seems to fail for rectangular partitions only.
In order to reproduce this, first enabled the disabled directional intra prediction, for ex. revert the commit 68c694f081a657081779c4c5f6849af5e85c0e1d.
At speed 0,1,2 (that enables tx partition), in debug mode, the assert :
  debug_assert!((tx_size, tx_type) ==
                rdo_tx_size_type(fi, ts, cw, bsize, tile_bo, mode_luma, ref_frames, mvs, skip));
in encode_block_with_modes() will fail.
Or, use 2x2 tiles (not enabled as of Apr 19, 2019, but will be enabled soon) at probably any speed levels, the same assert would fail.

**Comment by aditj** [comment]
> Some more clues, that I wanted to share.
> The disabled directional intra predictions seems to fail for rectangular partitions only.
> In order to reproduce this, first enabled the disabled directional intra prediction, for ex. revert the commit [68c694f](https://github.com/xiph/rav1e/commit/68c694f081a657081779c4c5f6849af5e85c0e1d).
> At speed 0,1,2 (that enables tx partition), in debug mode, the assert :
> debug_assert!((tx_size, tx_type) ==
> rdo_tx_size_type(fi, ts, cw, bsize, tile_bo, mode_luma, ref_frames, mvs, skip));
> in encode_block_with_modes() will fail.
> Or, use 2x2 tiles (not enabled as of Apr 19, 2019, but will be enabled soon) at probably any speed levels, the same assert would fail.

@ycho I am new to rav1e but I'll tryto reproduce the same. Thanks!

**Comment by lu-zero** [comment]
Any news about it?

**Comment by ycho** [comment]
We have update: https://github.com/xiph/rav1e/issues/1200#issuecomment-504565010
The difference is the existence of 'partition' info for the version for intra prediction.

**Comment by ycho** [comment]
Closing, since this is covered by #1391.
