### ISSUE TITLE
Memory Use Grows Forever

### ISSUE THREAD

**Issue by dwbuiten** [xiph/rav1e#1261]
Near as I can tell from tests, rav1e's memory grows infinitely when encoding. Running tests over longer clips easily reproduces this for me. Even after, 300-400 frames, memory use is still growing. Memory usage/growth is even more pronounced with tiles enabled.

Can be reproduced via: `rav1e --quantizer 100 --output whatever.ivf ducks_take_off_2160p50.y4m`. I personally ran this on a 96 core machine, if that matters (I doubt it...).

Here's heaptracker output after 33 frames (which took 14-ish hours... heaptracker is SLOW. ctrl-c after that.): http://chromashift.org/rav1e_33f_4k.txt (CTRL-F for 'PEAK' (all caps))

**Comment by tdaede** [comment]
This tells us that the two big users are Frame and FrameState. Unfortunately it's not super clear to me which one is the leak... possibly both. I'll take a look at FrameState first because it's simpler.

**Comment by tdaede** [comment]
FrameStates themselves hold Frames. FrameInvariants hold a reference count for all of their reference frames. If we never delete FrameInvariants, we will never lose our reference frames.

The garbage_collect() function is supposed to remove frame invariants more than 1 in the past. So either it doesn't work or something else is holding onto them.

**Comment by tdaede** [comment]
AFAIK the garbage collection for FrameInvariants is working correctly. At the end of garbage collection we only have one FrameInvariant left.

**Comment by tdaede** [comment]
So, while trying to get jemalloc profiling to work, I discovered that memory usage actually stays constant when using jemalloc. So.... maybe it is fragmentation, and/or glibc's allocator being terrible?

**Comment by dwbuiten** [comment]
I thought jemalloc was default for rust? I got my (stable) toolchain via rustup and I assumed it would use it?

**Comment by lu-zero** [comment]
In order to reduce the memory footprint jemalloc is now optional (you use [jemallocator](https://github.com/gnzlbg/jemallocator) to use it)

**Comment by dwbuiten** [comment]
I can confirm that using jemalloc solves the memory growth issue for me. So, maybe it *is* fragmentation?

**Comment by dwbuiten** [comment]
Spoke too soon:
```[17:33] < Daemon404> lu_zero, hrm... maybe this is more complex than i though
[17:33] < Daemon404> running 96 parallel rav1e cli and i see mem usage creeping up stilll
[17:33] < Daemon404> even after 100-200 frames
[17:34] < Daemon404> (with jemalloc...)
[17:34] < Daemon404> maybe theres different fragmentation with such a large amount of allocs and processes
```

**Comment by tdaede** [comment]
Can you test with master now? I think the ever-increasing memory is now fixed.

**Comment by dwbuiten** [comment]
I can confirm master no longer has this issue.
