### ISSUE TITLE
Desync since LRF refactor

### ISSUE THREAD

**Issue by ycho** [xiph/rav1e#1286]
Desync between encoder and decoder occurs with the use of 2x2 tiles.

git checkout 465360f63d60b42bdd313a96abf94d376b89f11d -b 465360f6
(Older version seems having same issue
git checkout 8058856aa6950e827c930aadb350f77823893156 -b 8058856aa)

./target/release/rav1e ~/sequences/objective-1-fast/ducks_take_off_1080p50_60f.y4m -o test.ivf -r test_rec.y4m --quantizer 60 --speed=5 --limit=2 --tile-rows-log2 1 --tile-cols-log2 1 --tune Psnr --low_latency

cmp test_rec.yuv test_dec.yuv
test_rec.yuv test_dec.yuv differ: char 11923177, line 1
==> It seems 4th frame has mismatch. (Since frame size = 1920x1080x1.5)

If the tile options "--tile-rows-log2 0 --tile-cols-log2 0", there is no desync.

**Comment by ycho** [comment]
Update, if --quantizer 10 (with 2x2 tiles), the desync has gone.
"--quantizer 100" still has desync

**Comment by ycho** [comment]
It turns out, using the same enc options above but w/o tiles, older commit before TILE has landed desyncs as well.

**Comment by tmatth** [comment]
```
e7ac4a56bd3f7141bf5f7e29e05a04d02ba7bc81 is the first bad commit
commit e7ac4a56bd3f7141bf5f7e29e05a04d02ba7bc81
Author: Monty Montgomery <xiphmont@gmail.com>
Date:   Tue Jan 22 02:52:46 2019 -0500

    Ongoing optimization and refactoring work for LRF RDO
    
    Unroll various boundary cases to get a better feel for expression flow.
```

**Comment by ycho** [comment]
> According to git bisect:
> 
> ```
> e7ac4a56bd3f7141bf5f7e29e05a04d02ba7bc81 is the first bad commit
> commit e7ac4a56bd3f7141bf5f7e29e05a04d02ba7bc81
> Author: Monty Montgomery <xiphmont@gmail.com>
> Date:   Tue Jan 22 02:52:46 2019 -0500
> 
>     Ongoing optimization and refactoring work for LRF RDO
>     
>     Unroll various boundary cases to get a better feel for expression flow.
> ```
> 
> [e7ac4a5](https://github.com/xiph/rav1e/commit/e7ac4a56bd3f7141bf5f7e29e05a04d02ba7bc81) is not a small change.
> 
> ```
> Key Frames:      1    avg size:  333208 B
> Inter:           4    avg size:  163255 B
> Intra Only:      0    avg size:       0 B
> Switch:          0    avg size:       0 B
> /tmp/dec_file /tmp/rec_file differ: byte 2072454, line 2
> Desync detected!!!
> ```

Thanks for pinpoint the source, and ouch its rolling five months back!

**Comment by xiphmont** [comment]
Well, dang.  Will look into this ~ immediately.

**Comment by tmatth** [comment]
> > According to git bisect:
> > ```
> > e7ac4a56bd3f7141bf5f7e29e05a04d02ba7bc81 is the first bad commit
> > commit e7ac4a56bd3f7141bf5f7e29e05a04d02ba7bc81
> > Author: Monty Montgomery <xiphmont@gmail.com>
> > Date:   Tue Jan 22 02:52:46 2019 -0500
> > 
> >     Ongoing optimization and refactoring work for LRF RDO
> >     
> >     Unroll various boundary cases to get a better feel for expression flow.
> > ```
> > 
> > 
> > [e7ac4a5](https://github.com/xiph/rav1e/commit/e7ac4a56bd3f7141bf5f7e29e05a04d02ba7bc81) is not a small change.
> > ```
> > Key Frames:      1    avg size:  333208 B
> > Inter:           4    avg size:  163255 B
> > Intra Only:      0    avg size:       0 B
> > Switch:          0    avg size:       0 B
> > /tmp/dec_file /tmp/rec_file differ: byte 2072454, line 2
> > Desync detected!!!
> > ```
> 
> Thanks for pinpoint the source, and ouch its rolling five months back!

NP, I got to use `git bisect run check-for-desync.sh`, which runs the encode you suggested (although I did have to manually go and find a working commit first) and by exiting with 0 or 1 automates the process of marking commits as good or bad.

**Comment by xiphmont** [comment]
This appears to be the same bug that barrbrain found a bit earlier and I'd been working on since.  Assuming it is (and I will verify this) the desync is actually being caused by deblocking, and I think it's a libaom bug.

The problem is that the spec says deblocking applies to the full width MI_ROWS by MI_COLS frame.  On odd-sized frames, this means that deblocking continues outside the crop rectangle into the padded area.  Rav1e is doing as the spec says.  Libaom stops deblocking at the crop frame.

When deblocking is active but the other loop filters are not, there is not necessarily a desync on output as the disagreement is outside the crop.  However, CDEF and LRF perform metrics on pixels to the full frame witdh, even if that's outside the crop, so it can cause one or both to produce erroneous pixels in-frame if it changes the working filter state.

**Comment by tmatth** [comment]
Using `dav1d` instead of aomdec:
```
     Running `target/release/rav1e /derf-media/objective-1-fast/ducks_take_off_1080p50_60f.y4m -o enc_file.ivf -r rec_file.y4m --quantizer 100 --speed=5 --limit=5 --tune Psnr --low_latency`
1920x1080 @ 50/1 fps
encoded 5/5 frames, 0.061 fps, 77049.06 Kb/s, est. size: 0.94 MB, est. time: 0 s                      
Key Frames:      1    avg size:  333208 B
Inter:           4    avg size:  163255 B
Intra Only:      0    avg size:       0 B
Switch:          0    avg size:       0 B
dav1d a690e54 - by VideoLAN
Decoded 5/5 frames (100.0%)
/tmp/dec_file /tmp/rec_file differ: byte 2072454, line 2
Desync detected!!!
```

**Comment by xiphmont** [comment]
OK, barrbrain's desync is fixed, checking this one.

**Comment by xiphmont** [comment]
Desync still replicates.

**Comment by xiphmont** [comment]
> According to git bisect:

The relevant change that makes this the 'bad' commit is that it turns LRF on for the first time.  Up to this point the LRF code was present but inactive.

Not yet clear the problem is LRF-- disabling CDEF leaving LRF on also eliminates the desync. 

Monty
