### ISSUE TITLE
Build Fails when Spaces in Path to Build Directory

### ISSUE THREAD

**Issue by theonewolf** [xiph/rav1e#1299]
I can't get the latest (`master`, commit `ef7a66a`) to build.  I am using Ubuntu 18.04.2 LTS on the WSL (Windows Subsystem for Linux), `cargo version` reports `cargo 1.35.0 (6f3e9c367 2019-04-04)`.

Running this command:

```
cargo build --release
```

The error message is:

```
error: Only `-l` and `-L` flags are allowed in build script of `rav1e v0.1.0 (/mnt/c/Users/WolfgangRichter/OneDrive/Development/rav1e)`: `-L /mnt/c/Users/WolfgangRichter/OneDrive/Development/rav1e/target/release/build/rav1e-3360cc2e11dc7960/out`
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by lu-zero** [comment]
The message is not telling much information, try to

```
# rustup update
# cargo update
# cargo build --release -v
```

And paste the some more lines if it still does not build.

**Comment by theonewolf** [comment]
@lu-zero I moved the folder into `/tmp/rav1e` and the build is working now.

In my original path (redacted above) I had:

1. Spaces in the full path
2. It was on an NTFS file system, not the pure Linux emulated file system in WSL

I am investigating both as potential sources of the issue.

**Comment by theonewolf** [comment]
@lu-zero I believe your build process can not handle spaces in the full path to the `rav1e` folder while building:

```
error: Only `-l` and `-L` flags are allowed in build script of `rav1e v0.1.0 (/tmp/theonewolf test/rav1e/rav1e)`: `-L /tmp/theonewolf test/rav1e/rav1e/target/release/build/rav1e-3360cc2e11dc7960/out`
```

**Comment by lu-zero** [comment]
is that specific to `rav1e` or it happens even if you try to build a simple test library (.e.g. `cargo new --lib testcase`)

**Comment by rzumer** [comment]
This is easy to reproduce by renaming the rav1e directory to include spaces.
