### ISSUE TITLE
rav1e assumes 4:0:0 is monochrome

### ISSUE THREAD

**Issue by dwbuiten** [xiph/rav1e#1312]
`header.rs` contains:

```Rust
let monochrome = seq.chroma_sampling == ChromaSampling::Cs400;
```

I don't think is is true, and it causes failure when trying to feed the encoder grayscale videos.

**Comment by tdaede** [comment]
In AV1 spec, monochrome == grayscale. Could you elaborate on the failure?

**Comment by tdaede** [comment]
Or do you mean using a monochrome color space with 4:2:0?

**Comment by dwbuiten** [comment]
Oh, I see, OK. The failure is just `unimplemented!` (which doesnt so nice when calling from C).

I thought this was a bug since monchrome usually doesn't mean grayscale... (I was trying to use 4:0:0).
