### ISSUE TITLE
ColorDescription enum values don't match with the spec

### ISSUE THREAD

**Issue by sdroege** [xiph/rav1e#1315]
E.g. https://aomediacodec.github.io/av1-spec/ mentions that the primaries are

| 1  | CP_BT_709 | BT.709 |
| -- | -- | -- |
| 2  | CP_UNSPECIFIED | Unspecified |
| 4  | CP_BT_470_M | BT.470 System M (historical) |
| 5  | CP_BT_470_B_G | BT.470 System B, G (historical) |
| 6  | CP_BT_601 | BT.601 |
| 7  | CP_SMPTE_240 | SMPTE 240 |
| 8  | CP_GENERIC_FILM | Generic film (color filters using illuminant C) |
| 9  | CP_BT_2020 | BT.2020, BT.2100 |
| 10 | CP_XYZ | SMPTE 428 (CIE 1921 XYZ) |
| 11 | CP_SMPTE_431 | SMPTE RP 431-2 |
| 12 | CP_SMPTE_432 | SMPTE EG 432-1 |
| 22 | CP_EBU_3213 | EBU Tech. 3213-E |

while the rav1e enum is (see comments for mismatches)

```rust
pub enum ColorPrimaries {
    BT709 = 1,
    Unspecified,
    BT470M = 4,
    BT470BG,
    ST170M, // BT_601
    ST240M,
    Film,
    BT2020,
    ST428,  // XYZ
    P3DCI, // SMPTE_431
    P3Display, // SMPTE_432
    Tech3213 = 22, // EBU_3213
}
```

Similar problems are with the other enums (transfer characteristics, matrix).

**Comment by kodabb** [comment]
sorry what is the problem here? the names are different because it's a different project but the values and the semantics are identical

**Comment by sdroege** [comment]
It's confusing if the spec and the API disagree about the names

**Comment by sdroege** [comment]
Yeah and in GStreamer we have yet another name for some of these. Too many standards.

If you think following some other projects' naming scheme for consistency is more important than using the naming in the AV1 spec that's fine with me. Either way someone will have to translate names, I just thought it might be less confusing if the encoder API was at least consistent in naming with the spec it implements :)
