### ISSUE TITLE
Desync between encoder and decoder

### ISSUE THREAD

**Issue by ycho** [xiph/rav1e#1347]
/target/release/rav1e ~/sequences/objective-1-fast/KristenAndSara_1280x720_60f.y4m -o test.ivf -r test_rec.y4m --quantizer 200 --limit=3

$ cmp test_rec.yuv test_dec.yuv
test_rec.yuv test_dec.yuv differ: char 3338561, line 54

It happens current master d9a921f10c873935b897c7fa81a4a94d4a4768ca and even 3 months old one b72bdbfa5636fd1b3e42044214f696eac4d69955.

Does not happen with --quantizer 100

**Comment by tmatth** [comment]
Can reproduce with ducks take off.

**Comment by ycho** [comment]
Looks like turning off the CDEF fix it?
Tried with f571c6320abfc04678cb4fb1ecbdce1d033374bb.

**Comment by ycho** [comment]
@xiphmont , I think your fix https://github.com/xiph/rav1e/commit/426280f5b5fea25fb73d3685393fabd7bb080742 fixes this issue?
If so, we can close this!

**Comment by ycho** [comment]
> @xiphmont , I think your fix [426280f](https://github.com/xiph/rav1e/commit/426280f5b5fea25fb73d3685393fabd7bb080742) fixes this issue?
> If so, we can close this!

@xiphmont, Oh sorry- I tried for 3 frames and seeing that the desync is still there.

**Comment by xiphmont** [comment]
BTW, this one is still here after the recent fixes, I'm looking at it next.

**Comment by ycho** [comment]
This seems fixed by https://github.com/xiph/rav1e/commit/c245abdd935a741146bc41b3c4d78844f0980987
