### ISSUE TITLE
Blinking effect

### ISSUE THREAD

**Issue by easyfab** [xiph/rav1e#1352]
rav1e git d9a921f

command line : rav1e.exe Kimono1_1920x1080_24.y4m --tile-cols-log2 3 --tile-rows-log2 2  -b 2000  -o Kimono1_1920x1080_24.test2.ivf

At the end of the video, on the roof I see blinking effect.
Not sure it's new, but I don't remember to see it in the past

[Kimono1_1920x1080_24.test2.zip](https://github.com/xiph/rav1e/files/3292988/Kimono1_1920x1080_24.test2.zip)

**Comment by dwbuiten** [comment]
I this something you can reproduce with e.g. `--quantizer 170` (or 160)?

Also, a source would be good.

**Comment by easyfab** [comment]
With --quantizer 170 it's more sublte but still there. 
I cut a smaller part.

source : https://www.sendspace.com/file/ejpi0d

encode result : [Kimono1_1920x1080_24.test3.zip](https://github.com/xiph/rav1e/files/3293319/Kimono1_1920x1080_24.test3.zip)

If you look carefully this area you can see small area that one frame are darker than next frame ligher and so on.

![Kimono1_1920x1080_24 test4 ivf_snapshot_00 00 000](https://user-images.githubusercontent.com/3464416/59553797-b1aab100-8f9a-11e9-9750-cebf318f6b56.jpg)

**Comment by gnafuthegreat** [comment]
If it helps anyone else to see the effect, I might categorize it as "strobing" rather than "blinking".

**Comment by easyfab** [comment]
I retry and I can't reproduce with 9a7ab75
It seems to be fixed now.
