### ISSUE TITLE
Large partitions will probably be broken by 80592c72f214ca46502442cb60c1b37e69bd971d

### ISSUE THREAD

**Issue by tdaede** [xiph/rav1e#136]
Investigate and fix.

**Comment by ycho** [comment]
FYI, 80592c72 is : 
"    Option to disable small tx size for intra chroma
    
    This is essentially an implementation of Mozilla's big_chorma_tx
    proposal, and CFL is already using this.
    
    The option is turned on by default."

So, to remedy this problem, we can start implementing multiple transform sizes.

**Comment by ycho** [comment]
#128 will address this.
