### ISSUE TITLE
Add custom cargo command to run clippy with same options as travis

### ISSUE THREAD

**Issue by tdaede** [xiph/rav1e#1406]

**Comment by lu-zero** [comment]
The cargo `[alias]` support is user-controlled. so I wouldn't add a `.cargo/config` in the rav1e tree.

We could consider embed the information in lib.rs or just make a clippy.sh and call it from the CI.

**Comment by lu-zero** [comment]
Alternatively we could ask upstream to extend the clippy configuration so we can store there this information.

**Comment by tdaede** [comment]
https://github.com/rust-lang/rust-clippy/issues/1313

**Comment by shssoichiro** [comment]
No longer needed, superceded by #1744
