### ISSUE TITLE
Normalize rustfmt.toml and CODING_STYLE.md

### ISSUE THREAD

**Issue by tdaede** [xiph/rav1e#1418]
They differ. Having worked on multiple Rust codebases at this point, I would probably prefer deviating less.

**Comment by lu-zero** [comment]
Of:
```
max_width = 79
comment_width = 79
force_explicit_abi = false
fn_args_layout = "Compressed"
use_small_heuristics = "Max"
match_arm_blocks = false
reorder_imports = true
tab_spaces = 2
use_field_init_shorthand = true
trailing_comma = "Never"
```
Only those two are quite noticeable to somebody coming from most of the other rust projects:
```
tab_spaces = 2
trailing_comma = "Never"
```

**Comment by tdaede** [comment]
fn_args_layout is also problematic as it's nightly rustfmt only, which makes it way more obnoxious to use.

**Comment by rzumer** [comment]
I personally prefer to avoid trailing commas, though it is not for very rational reasons (I mostly think it looks ugly, and weird syntactically).

**Comment by barrbrain** [comment]
I prefer `trailing_comma = "Vertical"` only for the reason that the unified diffs for inserting an item into a long list don't contain any deleted lines.

**Comment by lu-zero** [comment]
![image](https://user-images.githubusercontent.com/239012/61391810-ccd04f80-a8bd-11e9-9e3a-1b21e2bf5ad6.png)

I would argue that also `max_width = 79` is problematic once we have editorconfig trying to be "helpful".
