### ISSUE TITLE
Make fastrdo dumper behind a feature flag

### ISSUE THREAD

**Issue by tdaede** [xiph/rav1e#1420]
Then we can drop the serde dep from the library.

**Comment by Klaven** [comment]
I would like to do this one. I could use an example of what you want if you don't mind! Thanks!

**Comment by lu-zero** [comment]
Thank you

**Comment by shssoichiro** [comment]
@Klaven You can grep through the codebase for `dump_ivf` for an example. The fastrdo feature flag should end up being very similar.

**Comment by lu-zero** [comment]
I made [this](https://crates.io/crates/noop_proc_macro) to make easier to keep the derives around.

**Comment by lu-zero** [comment]
``` rust
#[cfg(not(feature = "serialize"))]
extern crate noop_proc_macro as serde_derive;
```

would do.

**Comment by lu-zero** [comment]
Hi, any update on this?
