### ISSUE TITLE
Override nasm path in cargo build

### ISSUE THREAD

**Issue by jefft0** [xiph/rav1e#1428]
Is there an option for `cargo build --release` to override the path of the nasm executable? I need this because the default nasm on macOS is old but it cannot be removed. I need to override to the install path of a recent version of nasm.

**Comment by lu-zero** [comment]
Setting `PATH` was enough for me, is it not for you?

**Comment by jefft0** [comment]
OK. The following command works. Thanks for the help.

    PATH=/usr/local/bin:$PATH cargo build --release
