### ISSUE TITLE
Scenecut Tweaks

### ISSUE THREAD

**Issue by dwbuiten** [xiph/rav1e#1441]
See: https://code.videolan.org/videolan/x264/blob/master/encoder/slicetype.c#L1426-1455

Now that we have lookahead for scene cuts, this should be easier, although require some refactoring.

Related to, but not part of https://github.com/xiph/rav1e/issues/794, technically.

CC: @YaLTeR @lu-zero

**Comment by shssoichiro** [comment]
I think this is similar enough to #794 that one of them could be closed, unless you feel there's something extra that's not included in the other ticket. I've picked up work on this again after the recent lookahead changes have made implementing this easier.

**Comment by dwbuiten** [comment]
I opened this because adding these tweaks is markedly different from switching to a cost-based keyframe placement algorithm, to me. I should have have two different issues in the first place...

**Comment by shssoichiro** [comment]
That makes sense. In that case, I can get a PR open for this ticket today and open a separate PR for #794 when that's ready.

**Comment by shssoichiro** [comment]
I found that the lookahead wasn't functioning the way it needed to for this to work correctly, so I've been doing some debugging to try and fix that. It was only doing the full lookahead at the very start of the video, and afterwards would only read one frame past the current. So, I will instead have this PR up Soon (TM).

**Comment by tdaede** [comment]
OK. The one thing I'm not sure about is if it would be better to look at multiple frames in the future (e.g. reading from frame_q) or rather mutating fi's in the past, and rewriting multiple fi's if a keyframe is inserted. One reason to do the latter is the fi's will have qres and hres motion search data on them from @YaLTeR's patches, which could be used instead of the current full-frame diff.

**Comment by shssoichiro** [comment]
That sounds like a possibility. The other option is to do qres and hres motion search during `compute_lookahead_data`, which would avoid having to edit FIs after they've been set. Either way will require a decent amount of refactor. For now, I've opened a PR to move forward with the change as-is (looking only ahead).

**Comment by YaLTeR** [comment]
> do qres and hres motion search during `compute_lookahead_data`

This is actually exactly what I do for temporal RDO, and I'm planning to PR it later today. I need to point out though that this is motion search on _original_ frames rather than _reconstructed_ frames, so the usual qres and hres motion search is still present too.
