### ISSUE TITLE
Desync with large size image, for ex: 3840x2160, dav1d error: "Overrun in OBU bit buffer into next OBU"

### ISSUE THREAD

**Issue by ycho** [xiph/rav1e#1509]
commit: 5554cfe2f897d27cc64a8964f355e0d7982f081a

It seems master desync with crowd_run-1frame.y4m, 3840x2160.
Cannot decode with either dav1d or aomdec.

https://people.xiph.org/~yushin/data/crowd_run-1frame.y4m

./target/release/rav1e /Users/yushin/Downloads/crowd_run-1frame.y4m -o test.ivf -r test_rec.y4m --quantizer=100 --speed=10 --limit=1 --tune=Psnr

lassen:rav1e yushin$ ../dav1d/build/tools/dav1d -i test.ivf -o test_dec_dav1d.y4m
dav1d 0.3.1-25-g63eef33 - by VideoLAN
Overrun in OBU bit buffer into next OBU
Error decoding frame: Invalid argument
No data decoded

**Comment by ycho** [comment]
If "--tile-rows-log2=1 ----tile-cols-log2=1" is used, then FINE!

**Comment by tdaede** [comment]
first bad commit is 00707b28e2503c6b1f62c6e690473ffc97f0e140

**Comment by ycho** [comment]
> first bad commit is [00707b2](https://github.com/xiph/rav1e/commit/00707b28e2503c6b1f62c6e690473ffc97f0e140)

@rzumer , can you take a look at this please?
