### ISSUE TITLE
Using gigabytes of memory when encoding 720p long clips

### ISSUE THREAD

**Issue by syniox** [xiph/rav1e#1523]
(Sorry for my bad English)
using commit 914fe8df0df9cdb87bd0f56fa8a57c8a3eab948
Footprint increases slowly and serially(about 8MB/s).
I closed it when 3 GB RAM was used by rav1e.Not a frame was encoded before closing it.
(Can encode with --limit 60, but it takes a long time before the first frame was encoded)
Is it expected?
(or anything wrong with my command?)
system: xubuntu 18.04 with sse4.1
```
ffmpeg -i tears_of_steel_720p.mov -an -f yuv4mpegpipe - | rav1e - --quantizer 120 -o output.ivf
```

**Comment by lu-zero** [comment]
Could you please test if 84c76ce11e449fc938b59215d26fc38ae0ac56b4 works in a different way?
