### ISSUE TITLE
Use Temporal RDO lookahead metric for scene detection instead of frame delta

### ISSUE THREAD

**Issue by tdaede** [xiph/rav1e#1528]
The lookahead for temporal RDO computes the "complexity" of each block (inter vs intra cost) when it does the motion search, relative to all of its references. We should use those numbers instead of the current frame difference metric, both because it's "free" and because it's motion compensated, so it's far more accurate.

**Comment by shssoichiro** [comment]
The complicated portion here is that we currently select the frame type before temporal RDO runs. So this will take a decent amount of refactor. But I think the refactor is necessary anyway, the current flow is hard to follow.
