### ISSUE TITLE
Bug: encoding the last quantized coeff in 4x4 cause desync

### ISSUE THREAD

**Issue by ycho** [xiph/rav1e#153]
Want to remove this line, but cannot since it introduces desync, esp. at lower QIndex.
https://github.com/xiph/rav1e/blob/91c95d6a4b9b8dcdebf7cec3f8600fe3b75941ea/src/quantize.rs#L23

**Comment by tdaede** [comment]
I haven't bothered to fix  this because all of this code will be replaced by lv_map_multi.

**Comment by ycho** [comment]
Okay- My curiosity already made me start probing, but let me stop here then,
