### ISSUE TITLE
Desync at speed 0, 4K image, 4x4 or 2x2 tiles

### ISSUE THREAD

**Issue by ycho** [xiph/rav1e#1565]
./target/release/rav1e crowd_run-1frame.y4m -o test.ivf -r test_rec.y4m --quantizer=150 --speed=0 --limit=1 --tune=Psnr --tile-rows-log2=2 --tile-cols-log2=2
(Was fine with speed 3)

https://people.xiph.org/~yushin/data/crowd_run-1frame.y4m

**Comment by ycho** [comment]
Ne desync with "--tile-rows-log2=0 --tile-cols-log2=0"

**Comment by ycho** [comment]
<Chagall> codeview: how about with cdef off?
<codeview> Chagall: Still desync with cdef off.

**Comment by xiphmont** [comment]
This test passes on current master (with the command line syntax altered to use tile-rows= and tile-cols=, as the '-log2' options no longer exist)

**Comment by ycho** [comment]
> This test passes on current master (with the command line syntax altered to use tile-rows= and tile-cols=, as the '-log2' options no longer exist)

Yeap- the desync has gone for 2x2 tiles on my MacOS.
