### ISSUE TITLE
Desync if "--tune Psnr", with speed 0, KristenAndSara_1280x720_60f.y4m, 1 frame only

### ISSUE THREAD

**Issue by ycho** [xiph/rav1e#1598]
./target/release/rav1e ~/sequences/objective-1-fast/KristenAndSara_1280x720_60f.y4m -o test.ivf -r test_rec.y4m --quanti    zer 100 --speed=0 --limit=1 --tune=Psnr

**Comment by xiphmont** [comment]
Can't reproduce this one on current master.

**Comment by ycho** [comment]
> Can't reproduce this one on current master.

Same thing is confirmed from my side, so closing.
