### ISSUE TITLE
Changing min block size for speed 1 from 8x8 to 4x4 gives a regression

### ISSUE THREAD

**Issue by ycho** [xiph/rav1e#1612]
#1570

**Comment by ycho** [comment]
@smarter, Hi- I remember once you have reported (during daala WW in Brussel?) similar thing like this before?

**Comment by ycho** [comment]
[AWCY results showing the change from master at speed 1](https://beta.arewecompressedyet.com/?job=master-2b20894d_s1%402019-08-21T16%3A10%3A31.334Z&job=test_s1_min_blk_4x4%402019-08-21T16%3A17%3A33.625Z)

**Comment by ycho** [comment]
[AWCY for 1 frame only, coming soon][https://beta.arewecompressedyet.com/?job=master-2b20894d_s1_1f%402019-08-30T20%3A04%3A13.298Z&job=test_s1_min_blk_4x4_1f%402019-08-30T20%3A04%3A27.382Z]

**Comment by ycho** [comment]
Tested 62c8a5d9d284296f40f1bc8e59a20cdccd97000e, (end of May 2019) and it is fine. I.e. changing min blk size downto 4x4 gives a gain.
[AWCY test for 62c8a5d9d284296f40f1bc8e59a20cdccd97000e](https://beta.arewecompressedyet.com/?job=ref_62c8a5d9_s5_1f%402019-09-03T18%3A42%3A50.092Z&job=test_62c8a5d9_min4x4_s5_1f%402019-09-03T18%3A43%3A49.617Z)

**Comment by shssoichiro** [comment]
There are quite a few differences from speed 5 to speed 1. Enabling full TX set, RDO TX decision, include near MVs, quantizer RDO, and complex pred modes for all frames. So, it would seem one of those is interacting poorly with 4x4 block size.

**Comment by ycho** [comment]
> There are quite a few differences from speed 5 to speed 1. Enabling full TX set, RDO TX decision, include near MVs, quantizer RDO, and complex pred modes for all frames. So, it would seem one of those is interacting poorly with 4x4 block size.

Right, so I am testing with turning off most of those enc options with current master.
Besides, for an additional clue, with current master I've changed speed 0's min blk size to 8x8, then there is some loss, but too smaller than I've expected.
[speed 0 with min blk sie 8x8](https://beta.arewecompressedyet.com/?job=cc7c5f3_minBlk8x8_s0_1f%402019-09-03T21%3A34%3A47.110Z&job=cc7c5f3_s0_1f%402019-09-03T21%3A33%3A11.102Z)

**Comment by ycho** [comment]
With most enc options off, I am seeing gains with min blk size 4x4 at speed 5 and 1:
(With most enc options off, speed 1 and 5 do the same thing, so the gain is exactly the same!)
[AWCY, most enc off, min blk size 4x4 speed 5](https://beta.arewecompressedyet.com/?job=ref_d0be7126_s5_1f%402019-09-03T21%3A18%3A08.624Z&job=test_d0be7126__min4x4_s5_1f%402019-09-03T21%3A19%3A02.523Z)

[AWCY, most enc off, min blk size 4x4 speed 1](https://beta.arewecompressedyet.com/?job=ref_d0be7126_s1_1f%402019-09-03T21%3A19%3A38.023Z&job=test_d0be7126__min4x4_s1_1f%402019-09-03T21%3A19%3A48.998Z)

**Comment by ycho** [comment]
Thinking that it might be due to --tune Psy, so trying --tune psnr now.
[awcy, --tune psnr, speed 5](https://beta.arewecompressedyet.com/?job=master-2b20894d_s5_psnr%402019-09-03T23%3A59%3A33.794Z&job=test_s5_min_blk_4x4_psnr%402019-09-03T23%3A59%3A51.176Z)

**Comment by ycho** [comment]
TEST: min blk size 8x8 --> 4x4

[awcy speed 0, --tune psnr, 1 frame](https://beta.arewecompressedyet.com/?job=cc7c5f3_minBlk8x8_s0_1f%402019-09-03T21%3A34%3A47.110Z&job=cc7c5f3_s0_1f%402019-09-03T21%3A33%3A11.102Z)
|    PSNR | PSNR Cb | PSNR Cr | PSNR HVS | SSIM | MS SSIM | CIEDE 2000 |
|    ---: |    ---: |    ---: |     ---: | ---: |    ---: |       ---: |
| -0.2565 |     N/A |     N/A |  -0.2884 |  N/A | -0.2391 |        N/A |

[awcy speed 0, --tune psnr](coming soon)

[awcy speed 0, --tune psnr with disabled tx-domain distortion](https://beta.arewecompressedyet.com/?job=disable_tx_dist_bd7945be_minblk8x8_s0_psnr_1f%402019-09-04T23%3A39%3A36.477Z&job=disable_tx_dist_3e1299a1_s0_min_blk_4x4_psnr_1f%402019-09-04T23%3A40%3A46.026Z)
|    PSNR | PSNR Cb | PSNR Cr | PSNR HVS | SSIM | MS SSIM | CIEDE 2000 |
|    ---: |    ---: |    ---: |     ---: | ---: |    ---: |       ---: |
| -1.4786 |     N/A |     N/A |  -1.3267 |  N/A | -1.2814 |        N/A |

[awcy speed 1, --tune psnr with disabled tx-domain distortion](https://beta.arewecompressedyet.com/?job=disable_tx_dist_bd7945be_s1_psnr_1f%402019-09-04T23%3A39%3A02.701Z&job=disable_tx_dist_3e1299a1_s1_min_blk_4x4_psnr_1f%402019-09-04T23%3A40%3A02.271Z)
--> This tells that top-down partition search (speed 1~10) may have issue of changing min blk size from 8x8 to 4x4 and no gain but regression.

**Comment by ycho** [comment]
If 4x4 min blk is used, at speed 5 and 8, there is a gain, -1.20% and -1.07% psnbr-bdrate, resp. 

[AWCY, speed 5](https://beta.arewecompressedyet.com/?job=master-2b20894d_s5_psnr_1f%402019-09-05T17%3A49%3A10.329Z&job=test_s5_min_blk_4x4_psnr_1f%402019-09-05T19%3A44%3A17.041Z)

[AWCY, speed 8](https://beta.arewecompressedyet.com/?job=master-2b20894d_s8_psnr_1f%402019-09-05T20%3A31%3A11.536Z&job=test_s8_min_blk_4x4_psnr_1f%402019-09-05T20%3A31%3A21.302Z)

**Comment by ycho** [comment]
If 4x4 min blk is used, at speed 5 and 8, there is a gain, -1.20% and -1.07% psnbr-bdrate, resp. 

[AWCY, speed 5](https://beta.arewecompressedyet.com/?job=master-2b20894d_s5_psnr_1f%402019-09-05T17%3A49%3A10.329Z&job=test_s5_min_blk_4x4_psnr_1f%402019-09-05T19%3A44%3A17.041Z)

[AWCY, speed 8](https://beta.arewecompressedyet.com/?job=master-2b20894d_s8_psnr_1f%402019-09-05T20%3A31%3A11.536Z&job=test_s8_min_blk_4x4_psnr_1f%402019-09-05T20%3A31%3A21.302Z)

**Comment by ycho** [comment]
For speed 2,3,4, further tested changing min blk size downto 4x4, then it was fine and giving gain > 1.0% for 4, but loss for 2 and 3, so I am guessing tx rdo might be related.

**Comment by ycho** [comment]
Back to the very base, I've tried turning off most of speed options,

[awcy, all disabled, speed 1, 1 frame](https://beta.arewecompressedyet.com/?job=ref_d0be7126_s1_1f%402019-09-03T21%3A19%3A38.023Z&job=test_d0be7126__min4x4_s1_1f%402019-09-03T21%3A19%3A48.998Z)

> With most enc options off, I am seeing gains with min blk size 4x4 at speed 5 and 1:
> (With most enc options off, speed 1 and 5 do the same thing, so the gain is exactly the same!)
> [AWCY, most enc off, min blk size 4x4 speed 5](https://beta.arewecompressedyet.com/?job=ref_d0be7126_s5_1f%402019-09-03T21%3A18%3A08.624Z&job=test_d0be7126__min4x4_s5_1f%402019-09-03T21%3A19%3A02.523Z)
> 
> [AWCY, most enc off, min blk size 4x4 speed 1](https://beta.arewecompressedyet.com/?job=ref_d0be7126_s1_1f%402019-09-03T21%3A19%3A38.023Z&job=test_d0be7126__min4x4_s1_1f%402019-09-03T21%3A19%3A48.998Z)

Revisiting the case I've tried before, since I think it will be the best base, where most of enc options are turned off and it then shows the expected gain when 4x4 min block size is introduced at speed 1.

**Comment by ycho** [comment]
I didn't post the case that disabled the tx rdo at speed 1, which gives 0.85% gain but most gains are from 1080p screen (I guess that was why I did not post this).

[awcy, disabled the tx rdo at speed 1, 1 frame](https://beta.arewecompressedyet.com/?job=disable_tx_rdo_s1_psnr_1f%402019-09-06T19%3A40%3A09.679Z&job=disable_tx_rdo_minblk4x4_s1_psnr_1f%402019-09-06T19%3A40%3A56.513Z)

|    PSNR | PSNR Cb | PSNR Cr | PSNR HVS | SSIM | MS SSIM | CIEDE 2000 |
|    ---: |    ---: |    ---: |     ---: | ---: |    ---: |       ---: |
| -0.8537 |     N/A |     N/A |  -0.2194 |  N/A | -0.3445 |        N/A |

And now I am testing to see what about if tx rdo only is enabled while most other enc options are disabled.

**Comment by ycho** [comment]
As recap, the regression at speed 1 is:

[awcy speed 1, --tune psnr, 1 frame](https://beta.arewecompressedyet.com/?job=master-2b20894d_s1_psnr_1f%402019-09-04T05%3A09%3A37.977Z&job=test_s1_min_blk_4x4_psnr_1f%402019-09-04T05%3A09%3A50.407Z)

|   PSNR | PSNR Cb | PSNR Cr | PSNR HVS | SSIM | MS SSIM | CIEDE 2000 |
|   ---: |    ---: |    ---: |     ---: | ---: |    ---: |       ---: |
| 0.5253 |     N/A |     N/A |   0.9234 |  N/A |  0.8565 |        N/A |

**Comment by ycho** [comment]
All right, finally seeing gains for most test sequences with min blk size 8x8 --> 4x4 for speed 1.
One firm clue.  Non-square partition of topdown partition search is screwing up our analysis.
All other enc options are not touched and intact as master.
(In short, I am screwed up by what I did! *_*)

min blk size 8x8 --> 4x4

[awcy, disabled non-square partition for topdown partition search, speed 1, 1 frame](https://beta.arewecompressedyet.com/?job=disable_rect_partition_s1_psnr_1f%402019-09-13T19%3A27%3A40.285Z&job=disable_rect_partition_minblk4x4_s1_psnr_1f%402019-09-13T19%3A28%3A00.587Z)

|    PSNR | PSNR Cb | PSNR Cr | PSNR HVS | SSIM | MS SSIM | CIEDE 2000 |
|    ---: |    ---: |    ---: |     ---: | ---: |    ---: |       ---: |
| -0.3630 |     N/A |     N/A |      N/A |  N/A |     N/A |        N/A |

**Comment by ycho** [comment]
I think I can finally conclude why. I.e. Why [changing min block size from 8x8 downto 4x4 for topdown partition search gives regression, as much as 0.46% psnr bdrate for 1 frame at speed 1] 
(https://beta.arewecompressedyet.com/?job=ref_master_s1_psnr_1f%402019-09-06T22%3A52%3A00.413Z&job=fix2_tx_size_minblk4x4_s1_psnr_1f%402019-09-07T05%3A41%3A30.874Z)

**Comment by shssoichiro** [comment]
Thanks for all the work investigating this. What do you propose the solution is? I think that 4x4 min block size should always produce better quality than 8x8 min.

Reopening for discussion.

**Comment by ycho** [comment]
As you might have tracked those test results above, w/o non-square partitions and changing min blk size from 8x8 to 4x4 give gain of 0.36% with very small increase in encoding time. Meanwhile, introducing non-square partitions to speed 1 on current master (c4886a38f0a8bba7c0377375eb8a4e564518cd0e) caused 44% ~ 11% enc time increase.
But given the possibility that the special rule (i.e. non-square at terminal only) can easily make our analysis or verification over old and new experiments harder, I suggest we reconsider whether we want keep non-square partition or not (of course, only for topdown partition search, i.e. speed 1 ~ 10).

**Comment by ycho** [comment]
> Thanks for all the work investigating this. What do you propose the solution is? Do we accept the speed penalty of opening up more rectangular block sizes for search? I think that 4x4 min block size should always produce better quality than 8x8 min.
> 
As in my comment above right after yours, I personally also prefer what you stated. I.e. disable non-square and change min blk size from 8x8 to 4x4 instead.

> Reopening for discussion.

**Comment by shssoichiro** [comment]
Closing per #1666
