### ISSUE TITLE
Large frame sizes cannot be decoded

### ISSUE THREAD

**Issue by rzumer** [xiph/rav1e#1614]
Source: nyan.y4m processed with `ffmpeg vf scale="-1:5000"`. Resolution is 7895x5000. Also tested rounding to mod2 (7894x5000), and assigning 4 and 9 tiles, all situations tested failed. Scaling to 4000 pixels high, however, works.

dav1d:
```
Error decoding frame: Invalid argument
```

aom:
```
Warning: Failed to decode frame 1: Corrupt frame detected
Warning: Additional information: Corrupted segment_ids
```

**Comment by rzumer** [comment]
Seems like it might be multiple issues.

When disabling CDEF and restoration:
 ```
Warning: Failed to decode frame 1: Corrupt frame detected
Warning: Additional information: Failed to decode tile data
```

**Comment by rzumer** [comment]
Standard 8K resolution works fine, so possibly an issue related to tile padding or similar.

**Comment by xiphmont** [comment]
I don't think this is tiling after investigation.
Also, I can't even run the test.  Over about 10 minutes it exhausts memory and the OOM killer gets it.

**Comment by shssoichiro** [comment]
Confirmed still broken on 6aa2c4e68c70c9c07769f3b2a98b4ccd18c5f9c9. It also does not matter if I set tiles to 1 or 4, I still get the same error. (Although we found some funky logic where rav1e might be force enabling tiles even if we set it to 1? So we can't rule out that this is related to tiling.)

**Comment by rzumer** [comment]
At least 2 tiles are needed for 5K IIRC.

**Comment by xiphmont** [comment]
More information?  I have an 8k nyancat, scaled as above, and with a default build.sh (just the different y4m file) it encodes and decodes correctly.

**Comment by shssoichiro** [comment]
I had never looked at the build.sh before so I took a look, and I've found where the breakdown starts to happen. If I run the build.sh, everything looks fine. If I manually run the encode with -s 3, I get an error in mpv, `[ffmpeg/video] libaom-av1: Failed to decode frame: Corrupt frame detected`, when trying to play it back.

The difference I found is that when I run it manually, I'm having mpv play the ivf file rav1e outputs, but the build.sh plays back the decoded y4m file. So I tested with `mpv --loop enc_file.ivf` output by the build script, and sure enough, I got the error.

**Comment by shssoichiro** [comment]
Is this possibly a bug in ffmpeg? That's the only point of failure I can see here. aomdec and dav1d are both able to decode to y4m successfully, but mpv and ffplay (which both use ffmpeg for playback) fail on the ivf file.

**Comment by rzumer** [comment]
I think that's a different issue. The original problem in this one seems fixed.

**Comment by shssoichiro** [comment]
It's not, though. I think the large frame sizes were misleading. The actual problem was the tiling, but the large frame sizes were causing rav1e to enable tiling. And again, the 5000p files fail to decode with ffmpeg, but work in aomdec and dav1d.

**Comment by rzumer** [comment]
Well, for what it's worth I can play my sample fine in mpv.
