### ISSUE TITLE
assertion failed: *importance >= 0.

### ISSUE THREAD

**Issue by moisesmcardona** [xiph/rav1e#1615]
```
rav1e "D:\temp\y4m-part-000001.y4m" -o "D:\temp\y4m-part-000001.ivf"  --quantizer 100 --threads 16 --tile-rows 8 --tile-cols 8 -s 8 -i 12 -I 240 --tune psychovisual --primaries unspecified --content_light 0,0 --matrix unspecified --range Limited --transfer unspecified -v
352x288 @ 25/1 fps

Backtrace omitted. Run with RUST_BACKTRACE=1 to display it.
Run with RUST_BACKTRACE=full to include source snippets.

The application panicked (crashed).
  assertion failed: *importance >= 0.
in src\api\mod.rs, line 1940
thread: <unnamed>
```

**Comment by dwbuiten** [comment]
Sounds like it might be the same bug or related to https://github.com/xiph/rav1e/issues/1601 since you are using 64 (!!!) tils for a 288p video (this is a bad idea even if it didn't crash btw... quality will be very bad).

**Comment by moisesmcardona** [comment]
I got the same issue after removing all of the parameters, and trying different `tile-rows` and `tile-columns` numbers. It also fails with 1080p videos.

**Comment by moisesmcardona** [comment]
Seems to work on Linux, but not on Windows.

Tested by manually building in Ubuntu using WSL and it works.

**Comment by YaLTeR** [comment]
That's interesting because importance should never be below 0 unless `intra_cost` somehow becomes below zero or something... Also really strange that it only breaks on Windows. Not sure I can diagnose that if it doesn't reproduce on Linux.

**Comment by lu-zero** [comment]
#1624 and #1623 fixed it.
