### ISSUE TITLE
Corrupted bitstream from 1 tile, 4K image

### ISSUE THREAD

**Issue by ycho** [xiph/rav1e#1635]
with master cc170c2a17675aae6fdcfd12ecc97eaeba90b974,
aomdec was not able to decode the bitstream from
./target/release/rav1e /Users/yushin/Downloads/crowd_run-1frame.y4m -o test.ivf -r test_rec.y4m --quantizer=150 --speed=    0 --limit=1 --tune=Psnr --tile-rows=0 --tile-cols=0

AOMedia Project AV1 Decoder 1.0.0-2268-gabef54f50
Warning: Failed to decode frame 1: Corrupt frame detected
Warning: Additional information: Failed to decode tile data
AOMedia Project AV1 Decoder 1.0.0-2268-gabef54f50
Warning: Failed to decode frame 1: Corrupt frame detected
Warning: Additional information: Failed to decode tile data

-dav1d was able to decode.

**Comment by rzumer** [comment]
Are you sure it is only coding 1 tile? I suggest printing the actual number from the tiling constructor, since it can increase if required due to rate and size constraints.

**Comment by ycho** [comment]
> Are you sure it is only coding 1 tile? I suggest printing the actual number from the tiling constructor, since it can increase if required due to rate and size constraints.
> 
> 4K should fall within constraints and stay at 1 tile, but we should make sure.

So, rav1e can automatically choose to use multiple tiles, esp. if one tile is larger (in its # of pixels or w/h) than limited by av1 spec?

**Comment by rzumer** [comment]
Exactly.

**Comment by ycho** [comment]
OK- as @rzumer suggested, with "enable_large_lru: false", the bug has gone and aomdec can decode successfully.

**Comment by xiphmont** [comment]
#1633 may have handled this, give master a try.

**Comment by ycho** [comment]
> #1633 may have handled this, give master a try.

Tried with master (https://github.com/xiph/rav1e/commit/ef482d4efd2989a27fde5ff6126813c1c6e1d8b9) but unfortunately aomdec still cannot decode it, saying
"AOMedia Project AV1 Decoder 1.0.0-2268-gabef54f50
Warning: Failed to decode frame 1: Corrupt frame detected
Warning: Additional information: Failed to decode tile data
AOMedia Project AV1 Decoder 1.0.0-2268-gabef54f50
Warning: Failed to decode frame 1: Corrupt frame detected
Warning: Additional information: Failed to decode tile data"

**Comment by xiphmont** [comment]
reproduced.  bisecting now, it will be a little while.

**Comment by xiphmont** [comment]
FWIW, the file with the given command line is being encoded with 2 tiles.

**Comment by ycho** [comment]
lassen:aom_build yushin$ tools/dump_obu ../rav1e/test.ivf
Temporal unit 0
  OBU type:        OBU_TEMPORAL_DELIMITER
      extension:   no
      length:      2
  OBU type:        OBU_SEQUENCE_HEADER
      extension:   no
      length:      14
  OBU type:        OBU_FRAME_HEADER
      extension:   no
      length:      30
  OBU type:        OBU_TILE_GROUP
      extension:   no
      length:      242416
  TU size: 242462
  OBU overhead:    4
File total OBU overhead: 4
lassen:aom_build yushin$

**Comment by xiphmont** [comment]
?

**Comment by ycho** [comment]
> ?

.... *_* 
Wanting to check the # of tiles decoded, I just ran "tools/dump_obu" of libaom,
and it seems it does not provide that info.

**Comment by xiphmont** [comment]
Oh, I see.  I checked via a println!() in the tiler :-)

**Comment by xiphmont** [comment]
Not a ton of progress yet, but to speed up the search for anyone else looking:
happens with the above command line at any speed
happens even with one thread
happens even if the tiler is forced (via a patch) to use only a single tile.

**Comment by xiphmont** [comment]
00707b28e2503c6b1f62c6e690473ffc97f0e140 ("Add rate restriction to TilingInfo constructor") appears to be the commit that broke things.
Command line passes test on previous commit 02fd9d04a40bcbf38fa399a91cbd00fbc019a4a1 ("Add conversion functions to Rational")

**Comment by rzumer** [comment]
Ok, I will look into it.

**Comment by ycho** [comment]
Testing https://github.com/ycho/rav1e/tree/test_not_limiting_min_tiles now and it still runs!

**Comment by ycho** [comment]
Now it is decodable by aomdec but desync occurs!

test_rec.yuv test_dec.yuv differ: char 10376546, line 1

**Comment by ycho** [comment]
![diff](https://user-images.githubusercontent.com/10123259/64651867-504a8080-d3d7-11e9-9e6f-5cb9e7217d37.png)

Looks like the difference is at chroma channels.

**Comment by xiphmont** [comment]
Just tried this all against current master, everything succeeds.

**Comment by ycho** [comment]
> Just tried this all against current master, everything succeeds.

Also the issue has gone. The aomdec is able to decode w/o desync! Closing.
