### ISSUE TITLE
multi-ref switch does not work correctly

### ISSUE THREAD

**Issue by ycho** [xiph/rav1e#1675]
At speed 5 , multi-ref is disabled but two ref frames are searched and encoded in bitstream.

<img width="1679" alt="Screen Shot 2019-09-18 at 1 02 19 PM" src="https://user-images.githubusercontent.com/10123259/65182036-3f23f400-da15-11e9-97e6-3e13ee6cc8ea.png">

(AOM analyzer, goto frame 2 there)[mfhttps://beta.arewecompressedyet.com/analyzer/?maxFrames=4&decoder=https://people.xiph.org/~mbebenita/analyzer/inspect.js&decoderName=master-low-latency%402019-09-18T07%3A46%3A50.014Z&file=https://beta.arewecompressedyet.com/runs/master-low-latency@2019-09-18T07:46:50.014Z/objective-1-fast/red_kayak_360p_60f.y4m-172.ivf&decoder=https://people.xiph.org/~mbebenita/analyzer/inspect.js&decoderName=branch-low-latency%402019-09-18T07%3A54%3A57.812Z&file=https://beta.arewecompressedyet.com/runs/branch-low-latency@2019-09-18T07:54:57.812Z/objective-1-fast/red_kayak_360p_60f.y4m-172.ivf]

Note: "--low-latency" is also given but it does not chance multi-ref

**Comment by shssoichiro** [comment]
(Just for clarity, multiref is automatically enabled when low-latency is false, regardless of speed level. The only way to use no-multiref is by setting --low-latency.)

**Comment by ycho** [comment]
> (Just for clarity, multiref is automatically enabled when low-latency is false, regardless of speed level. The only way to use no-multiref is by setting --low-latency.)

Yes, but the problem we have is that the flag seems set correctly but multi reference is happening when multiref flag == false!

**Comment by lu-zero** [comment]
Is the issue fixed now?

**Comment by shssoichiro** [comment]
Yes, #1674 fixed this.
