### ISSUE TITLE
Set speed 0 and 1 use the same enc options except partition search methods

### ISSUE THREAD

**Issue by ycho** [xiph/rav1e#1678]
So that we can track where the topdown partition search trapped in local optimal sizes, compared to bottomup partition search with exactly the same available enc modes.

**Comment by ycho** [comment]
It seems that only the partition strategy is different between speed 0 and 1 with current head of master https://github.com/xiph/rav1e/commit/39b93e6a7ea4f99361fd88ab997a96ee9bc7a6f2,
 
 const fn encode_bottomup_preset(speed: usize) -> bool {
    speed == 0
  }

**Comment by ycho** [comment]
Result will be soon available [awcy, speed 1 vs 0, psnr, low-delay](https://beta.arewecompressedyet.com/?job=branchc-low-latency%402019-09-19T22%3A57%3A20.488Z&job=master-low-latency%402019-09-18T07%3A46%3A50.014Z)

**Comment by ycho** [comment]
Hmm, we actually need new speed btw 0 and 1, say 0.5 that is bottomup partition search with square partition only because topdown  partition only uses square partition.

**Comment by ycho** [comment]
[awcy, speed 0.5 vs 1](https://beta.arewecompressedyet.com/?job=master-39b93e6_s1_psnr_low_latency_1f%402019-09-20T05%3A00%3A18.657Z&job=master-39b93e6_s0.5_psnr_low_latency_1f%402019-09-20T06%3A44%3A26.339Z)

**Comment by shssoichiro** [comment]
> Hmm, we actually need new speed btw 0 and 1, say 0.5 that is bottomup partition search with square partition only because topdown partition only uses square partition.

We can rebalance upwards, speed 5 and 6 are still identical at the moment.

**Comment by ycho** [comment]
> > Hmm, we actually need new speed btw 0 and 1, say 0.5 that is bottomup partition search with square partition only because topdown partition only uses square partition.
> 
> We can rebalance upwards, speed 6 and 7 are still identical at the moment.

Yes, please wait I will bump up at least one grid, i.e. 0.5 to be 1 and from 1 shift by one.

**Comment by ycho** [comment]
> [awcy, speed 0.5 vs 1](https://beta.arewecompressedyet.com/?job=master-39b93e6_s1_psnr_low_latency_1f%402019-09-20T05%3A00%3A18.657Z&job=master-39b93e6_s0.5_psnr_low_latency_1f%402019-09-20T06%3A44%3A26.339Z)
> PSNR 	PSNR Cb 	PSNR Cr 	PSNR HVS 	SSIM 	MS SSIM 	CIEDE 2000
> -1.3031 	N/A 	N/A 	N/A 	-1.1059 	N/A 	N/A

I thought this experiment is complete to fulfill our current and possible future quests on where topdown become blind when bottom can find better block size. 
However, there was again another thing I missed. With speed 1, topdown partition search, it is still able to use non-square partitions on right/borrom frame borders! (this was done while ago since it gives meaningful gain with very small increase in enc time). And this leads to several coding losses with some sequences in above awcy run.
So, the cure I think now is to have our speed 0.5 (i.e., bottomup with square partition only can also use non-squares on right/bottom frame borders, and this I estimate now and seems some handful of careful work needed.

**Comment by ycho** [comment]
done by #1687
