### ISSUE TITLE
Speed 5 to 4 gap is too large, -6.42%

### ISSUE THREAD

**Issue by ycho** [xiph/rav1e#1706]
|    PSNR | PSNR Cb | PSNR Cr | PSNR HVS |    SSIM | MS SSIM | CIEDE 2000 |
|    ---: |    ---: |    ---: |     ---: |    ---: |    ---: |       ---: |
| -6.4235 | -1.5380 | -1.4604 |  -4.8992 | -6.0668 | -5.0307 |    -4.1218 |

[awcy, speed 5 -> 4](https://beta.arewecompressedyet.com/?job=speed_bumpup_s5%402019-09-24T17%3A24%3A28.742Z&job=speed_bumpup_s4%402019-09-24T17%3A24%3A06.569Z)

The changes in encoding options is: RDO TX decision, which has two sub-options, tx_type and tx_partition (for intra mode only).

**Comment by ycho** [comment]
The gap has been improved, i.e. narrowed down to -4.5% by https://github.com/xiph/rav1e/pull/1774, [awcy](https://beta.arewecompressedyet.com/?job=s5-txset%402019-10-17T16%3A41%3A04.262Z&job=master-s6%402019-10-17T18%3A20%3A01.049Z)

**Comment by rzumer** [comment]
The run you linked is a comparison between levels 6 and 5. Between 5 and 4 the gap is about 6%.

**Comment by ycho** [comment]
With 6722d755244c2e3cd204f92e42a1a08845425ed3,
The bdrate change for speed 6->5 is -4.5% [awcy speed 6 -> 5](https://beta.arewecompressedyet.com/?job=master-6722d755_s5%402019-11-08T18%3A35%3A21.837Z&job=master-6722d755244c2e3cd204f92e42a1a08845425ed3)

and for speed 5 -> 4, -1.55% [awcy speed 5 -> 4](https://beta.arewecompressedyet.com/?job=master-6722d755_s5%402019-11-08T18%3A35%3A21.837Z&job=master-6722d755_s4%402019-11-08T18%3A35%3A54.135Z)
