### ISSUE TITLE
The reduced_tx_set_preset, i.e. speed 6 to 5 does not seem work correctly

### ISSUE THREAD

**Issue by ycho** [xiph/rav1e#1707]
The reduced_tx_set is enabled from speed 6 and turned on for higher.
AWCY tells that almost no change in speed and bdrate change.

[awcy speed 6 --> 5](https://beta.arewecompressedyet.com/?job=speed_bumpup_s6%402019-09-24T17%3A24%3A38.051Z&job=speed_bumpup_s5%402019-09-24T17%3A24%3A28.742Z)

|   PSNR | PSNR Cb | PSNR Cr | PSNR HVS |    SSIM | MS SSIM | CIEDE 2000 |
|   ---: |    ---: |    ---: |     ---: |    ---: |    ---: |       ---: |
| 0.0134 |  0.1496 |  0.1244 |  -0.0204 | -0.0201 | -0.0270 |     0.0488 |

**Comment by shssoichiro** [comment]
From the code, it seems like the only code where this makes a difference in encoding is in rdo_tx_type_decision, and then it only comes into play if rdo_tx_decision is enabled, which is only at speed <= 4. So it seems like possibly the speed settings for rdo_tx_decision and reduced_tx_set should be flipped?

**Comment by ycho** [comment]
> From the code, it seems like the only code where this makes a difference in encoding is in rdo_tx_type_decision, and then it only comes into play if rdo_tx_decision is enabled, which is only at speed <= 4. So it seems like possibly the speed settings for rdo_tx_decision and reduced_tx_set should be flipped?

That is right and I think I have addressed on this long time ago. However, if we just flip here speed 5,6 become much slower since rdo_tx_decision (even it has tx_size decision part only). So, we probably want to consider this.
Another impact, though almost no change on bitstream size, by changing the reduced_tx_set flag is :  self.write_bit(fi.use_reduced_tx_set)?; // reduced tx

Currently:
,,,reduced_tx_set_preset(speed: usize) -> bool {
    speed >= 6
  }

do_tx_decision_preset(speed: usize) -> bool {
    speed <= 4
  },,,

**Comment by ycho** [comment]
As I have reported in #1706, there it biggest coding gain gap -6.42 between speed 4 and 5 (caused by tx_rdo), I proposed to spread out this big gap to two speed levels by changing presets for reduced_tx_set and do_tx_decision as below:

reduced_tx_set_preset(speed: usize) -> bool {
speed >= 5
}

do_tx_decision_preset(speed: usize) -> bool {
speed <= 5
}

So, tx_rdo is enabled for speed 5 but w/o tx_type rdo.

**Comment by shssoichiro** [comment]
Sounds good to me :+1:

**Comment by rzumer** [comment]
Running the suggested solution on AWCY to ensure proper balance. Will submit a PR with it if it offers a good tradeoff or adjust parameters otherwise.

**Comment by ycho** [comment]
I have just fixed the last sentence as : "So, tx_rdo is enabled for speed 5 but with "reduced tx_type set".
In summary, current master does not do tx_rdo at speed 5. Proposed change is to do tx_rdo at speed 5 but with reduced tx_type set by revised reduced_tx_set_preset( ).

**Comment by rzumer** [comment]
Speed 4 with the proposed change has weird results, as BD rate worsens in addition to the speed reduction.

https://beta.arewecompressedyet.com/?job=master-s4%402019-10-10T21%3A22%3A48.151Z&job=s4-txset%402019-10-17T16%3A41%3A18.532Z
