### ISSUE TITLE
Backport dav1d update_cdf() assembly

### ISSUE THREAD

**Issue by tdaede** [xiph/rav1e#1720]
dav1d has a 2x as fast update_cdf() implementation, we should use it.

**Comment by dodomorandi** [comment]
I noticed that the dav1d `update_cdf` function uses the following unstable intrinsics:
* [pavgw](https://doc.rust-lang.org/core/arch/x86_64/fn._m_pavgw.html)
* [psubw](https://doc.rust-lang.org/core/arch/x86_64/fn._m_psubw.html)
* [paddw](https://doc.rust-lang.org/core/arch/x86_64/fn._m_paddw.html)

I am also not sure about `psraw`, a _packed shift raw arithmetic_ from MMX set, which I am not able to find in the core docs. A possible alternative could be `_mm_sra_pi16`, but it does not exists as well. Maybe it could be possible to use the 128 bit version?

Last consideration: maybe the three functions could be replaced by [_mm_avg_pu16](https://doc.rust-lang.org/core/arch/x86_64/fn._mm_avg_pu16.html), [_mm_sub_pi16](https://doc.rust-lang.org/core/arch/x86_64/fn._mm_sub_pi16.html) and [_mm_add_pi16](https://doc.rust-lang.org/core/arch/x86_64/fn._mm_add_pi16.html), but I am a bit noob with SIMD intrinsics and I don't know if there are subtle differences between the two series of versions.

**Comment by shssoichiro** [comment]
@dodomorandi What we have generally been preferring with dav1d's ASM is copying it as-is into rav1e (see the src/x86 directory) then compiling it with nasm. I don't know if you are more familiar with raw ASM syntax than with Rust's intrinsics.

**Comment by tdaede** [comment]
In this particular case I wrote it as intrinsics first, then converted it to asm for dav1d. We could either switch this to calling the nasm version, or backport the changes back into intrinsics. In this particular case, the reduced calling overhead of intrinsics might make using them more feasable.

Unfortunately *none* of the m64 intrinsics are stable in Rust, so you'd need to actually convert those functions to the 128 bit version. That's totally OK to do. On modern Intel CPUs that's totally OK to do as the 128 bit versions are the same speed. You'll just want to test it to make sure it's functionally identical (the unit tests should do this already).
