### ISSUE TITLE
cmake-building is unreliable

### ISSUE THREAD

**Issue by tdaede** [xiph/rav1e#178]
- [ ] a manual cargo clean is needed when the libaom code gets updated
- [ ] on some platforms there is no way to avoid the wxwindows dependency
- [ ] the encoding-decoding test is not present yet

Reverting #99 would be an improvement.

**Comment by lu-zero** [comment]
I'd rather have a feature so who wants to just build the encoder won't have to deal with the additional overhead.

**Comment by tdaede** [comment]
That's fine (we need some way to get it for the encoding-decoding test anyway)

**Comment by tdaede** [comment]
I infodumped into this etherpad: https://public.etherpad-mozilla.org/p/rav1e-cmake

**Comment by tdaede** [comment]
I think this is OK now.
