### ISSUE TITLE
Ability to query version (string) from C API (FFI)

### ISSUE THREAD

**Issue by joedrago** [xiph/rav1e#1801]
I'm hooking up rav1e support into libavif, and it'd be nice if there were capi calls such as:

```
const char * rav1e_version_short(void);
const char * rav1e_version_full(void);
```

Which returned lib.rs version::short, version::full string, etc, so I could expose those from my `avifCodecVersions()` call.

**Comment by dwbuiten** [comment]
This should be easy to do, I will add it in before we drop a release (very soon).
