### ISSUE TITLE
Artefacts when using low quantizer

### ISSUE THREAD

**Issue by SmilingWolf** [xiph/rav1e#1815]
While running some encodes at CQ 30, speed 5, Psy tune using rav1e commit 46a64c4 I noticed heavy blocking on one clip and general metrics degradation, with PSNR-HVS-M being particularly affected.

For example:
![044](https://user-images.githubusercontent.com/4309301/67982919-e5be0000-fc23-11e9-9e8b-d24d3b299329.png)

Closer inspection revealed a variety of more or less subtle artefacts, such as intensity shifting in the Y channel, in most clips encoded using the configuration from above.

Reduced clip for testing: https://mega.nz/#!FloAHajK!_OHewBCUU1D7AJvGYG3mxtWzFZNne17aC5j5bcJnRx0
Exact cmdline: `rav1e -o dist.rav1e.cq30.sp5.ivf --quantizer 30 -s 5 --tune Psychovisual rav1e.sp5.cq30.psy.bugRepro.y4m`

I have been unable to reproduce the issue using any other configuration so far, such as lower or higher CQ, using speed 6, or tune Psnr, at least using the clip above for testing.

Attached are two encodes, a faulty one at CQ 30 and a good one at CQ 31.
[dist.encodes.zip](https://github.com/xiph/rav1e/files/3795677/dist.encodes.zip)

**Comment by shssoichiro** [comment]
Interestingly, the same bug appears at q29 s5, but on the sleeve of the man to the right instead of on the sign. It does not seem to happen at q30 s4.

**Comment by quietvoid** [comment]
I've also had some blocking artifacts appear with 2 pass 10 bit, at around 8000 kbps as well.
Happened at speed 6 and 2, not sure about other speeds.

In some places it was darker, large blocks. Other places it was lighter blocks. Sometimes it was blocking at the edges of in-motion objects.
It only seemed to start appearing after 10s (240 frames at 24 fps, --keyint 24) for me.

Could only recreate with one clip though, not sure why it didn't happen with the exact same scenario but another clip.

**Comment by shssoichiro** [comment]
I'll do a bisect. See you in 8 hours. :smile:

**Comment by rzumer** [comment]
@shssoichiro Keep in mind the affected speed level is among those that were bumped up recently, so during a bisect it might be closer to 4 depending on the commit. Some speed levels were touched up individually as well, so it might be hard to get accurate bisect results if the cause happens to be a feature that was flipped on or off for balance.

**Comment by shssoichiro** [comment]
Indeed, a simple bisect shows 1ecbae4aaeb24991021517f0163d55305e86c7e8 as the first bad commit. Going to bed now, anyone else can feel free to pick up on this.

**Comment by SmilingWolf** [comment]
Applied 1ecbae4 on top of various "interesting" commits. Turned out the bug starts manifesting right after ea71393.

As countercheck I reverted ea71393 from the top of current master, commit 
0282b20, using `git apply -R ../ea71393.diff` and the blocking artefacts are gone and metrics are looking regular again.

I'll stress test this build with encodes at even lower Qs and report back.

@KyleSiefring is it possible this commit is the source of the bug, or could it be bringing out another that has gone undetected for longer?

**Comment by SmilingWolf** [comment]
0fa5464 + PR 1694 gives an encode with artifacts.
e0d9e78 with no other patches, tested at speed 3, 4 and 5 at a few different CQs between 25 and 35 doesn't seem affected.

**Comment by barrbrain** [comment]
@SmilingWolf Can you confirm whether PR #1824 eliminates the encoded artifacts?

**Comment by SmilingWolf** [comment]
I'm going to test the patch on the fragment posted above and report back.

However, would it be possible to withhold the patch for 24h? I'd like run full set of encodes on all my clips and report my findings.

**Comment by SmilingWolf** [comment]
Confirming the master branch as of 9e1c711 correctly encodes all my clips.
