### ISSUE TITLE
"--tune Psnr" mode completely broken

### ISSUE THREAD

**Issue by ycho** [xiph/rav1e#1816]
With commit 5bee8ea5f32820a7b25849340dd0116a103074e1,
"--tune Psnr" mode seems completely broken, giving huge coding loss.

[awcy --tune Psnr](https://beta.arewecompressedyet.com/?job=master-5bee8ea5f32820a7b25849340dd0116a103074e1&job=master-5bee8ea5_tune_psnr%402019-10-31T21%3A44%3A50.469Z)

**Comment by rzumer** [comment]
This definitely needs to be fixed before release (or PSNR tuning disabled), we cannot deliver a broken tuning mode.
