### ISSUE TITLE
C API function rav1e_status_to_str() returns a string the caller needs to free

### ISSUE THREAD

**Issue by jamrial** [xiph/rav1e#1821]
The function should ideally be changed to return a const char* string (Like the new version API functions). If that's not possible, then the doxy should mention that the string needs to be freed, or it will leak.

**Comment by lu-zero** [comment]
It is not possible, the error messages are not static strings and contain exactly what went wrong, if you could send a patch for the documentation would be great :)

**Comment by rzumer** [comment]
Closed by #1822.
