### ISSUE TITLE
rav1e_status_to_str documentation is incorrect and dangerous

### ISSUE THREAD

**Issue by dwbuiten** [xiph/rav1e#1825]
It says to use `free()`, for a heap allocation that happens inside the library, and is not guaranteed to be allocated by the same allocator. Also, I suspect this is wrong anyway, considering it is allocated by Rust itself (double wrong on windows).

**Comment by lu-zero** [comment]
https://github.com/xiph/rav1e/pull/1826 fixes it.

**Comment by barrbrain** [comment]
#1826 is now merged and replaced the returned values by static strings.
