### ISSUE TITLE
Support writing Timing Info

### ISSUE THREAD

**Issue by jamrial** [xiph/rav1e#1840]
Frame rate could be set using an encoder option for applications using the rav1e API. The CLI could also take it directly from the y4m input when available.

As far as i could see, it should be a matter or setting timing_info_present_flag to 1, time_base and num_units_in_display_tick in the timing_info section of sequence header to the framerate numerator and denominator respectively, and for simplicity equal_picture_interval to 1 and num_ticks_per_picture_minus_1 to 0.
Time stamps are not written in the bitstream with the above combination.

This will be useful for Annex B or raw Section 5 OBUs output, as some people have (unfortunately) started using and dumping samples in the wild.

**Comment by rzumer** [comment]
If the point is to override the frame rate I think that's done via the time base. I tested setting timing info as well but it does not seem to change the decoded frame rate.

**Comment by tdaede** [comment]
We already have said timing info (and the PR adds a way to override it), but we don't have a flag that actually writes the optional timing data into the bitstream, so we'll need to add it.

**Comment by jamrial** [comment]
Yes, the point of this ticket is to write timing info in the bitstream, for the cases where this information isn't available at the container level. That means Annex B or just plain raw OBUs.
Currently no decoder seems to care about any of the relevant Sequence Header fields, but i have a patch to make dav1d through ffmpeg honor them.

Also not just CLI. It should be an option accessible by API users, of course.

**Comment by rzumer** [comment]
Okay, I will add the requested functionality as part of #1841.
