### ISSUE TITLE
Duplicated -lrt, -lpthread and -lutil in pkg-config file

### ISSUE THREAD

**Issue by linkmauve** [xiph/rav1e#1847]
Here is the relevant line in the generated .pc file:
```pkg-config
Libs.private: -ldl -lrt -lpthread -lgcc_s -lc -lm -lrt -lpthread -lutil -lutil
```

It doesn’t prevent it from working here, but could eventually be an issue on some platforms.

The addition of -lc and -lgcc_s is weird too, I’m not sure how it will work on other platforms.  You may also want to replace -lpthread with -pthread, which is AIUI more portable.

**Comment by lu-zero** [comment]
It is a platform specific link line provided directly by `rustc`.

On linux with the normal binutils you may need this quite contrived link line.
