### ISSUE TITLE
Prepare an exhaustive speed report for 0.2

### ISSUE THREAD

**Issue by lu-zero** [xiph/rav1e#1856]
We are at around 23% speedup for 1080p content (8 tiles/ 8 thread), would be nice to get more data on what the user could expect. 

Checklist:
- Test with the default `cargo run --release`
- Test with `RUSTFLAGS="-C target-features=+avx2,+fma" cargo run --release`
- Test with `RUSTFLAGS="-C target-cpu=native" cargo run --release`

**Comment by easyfab** [comment]
CPU : AMD 2700x (16 threads ) windows 10
File : Kimono1_1920x1080_24.y4m ( 1080p 240 frames )

rav1e 0.1 (https://github.com/xiph/rav1e/releases/download/0.1.0/rav1e.exe)
rav1e acb7b692 ( from appveyor  Artifacts 1.0.4023 )
rav1e settings : default and --tiles 8

rav1e 0.1:              0.753 fps   (cpu usage ~35% )
rav1e acb7b69 :    0.950 fps   (cpu usage ~35% )

0.1 vs acb7b69 : +26.16% speedup

With 8 simultaneous chunks and --tiles 2

rav1e 0.1              2:22,38  -> 1.686 fps (cpu usage ~100% )
rav1e acb7b692     2:11,82 ->  1.821 fps (cpu usage ~100% )

0.1 vs acb7b69 : +8% speedup

**Comment by rzumer** [comment]
0.1.1 would be a patch release. By semver standards it seems like this belongs to 0.2.

**Comment by lu-zero** [comment]
Depends on how we count the feature you landed :) I'm fine in calling it 0.2

**Comment by Tggltn** [comment]
time ./rav1e  ../../../../GTAV30.y4m --verbose --tile-rows 2 --tile-cols 2  -b 3000 --speed 2  --output gta0.1-s2.ivf

Imput File GTAV https://media.xiph.org/video/derf/ 
60FPS would take to long
ffmpeg -i GTAV.y4m -filter:v fps=fps=30 GTAV30.y4m

Odroid-N2(it did only use the 4 Cortex-A73 cores1.8Ghz) Manjaro arm 

pre-0.2 rav1e 0.1.0 (20191127-13-g6df00f3) Build 29.November 

GTA30FPS | 0.1 | pre-0.2 | change | Perf diff
------------ | ------------- | ------------- | ------------- | -------------
Speed 2 |  [Log0.1](https://github.com/xiph/rav1e/files/3922872/benchmark0.1.txt) | [logpre-0.2](https://github.com/xiph/rav1e/files/3922888/benchmark0.2.txt) | 
Time | 1006m9,631s | 719m59,399s | 28,54% | TODO
FPS | 0.030 fps | 0.042 fps
Speed 4 | |
FPS | 846m42,178s | 596m7,948s | 29,50%
Time | 0.035 fps | 0.050 fps |   
Speed 6 |  | 
Time | 618m22,055s | 418m56,398s |  32,29% | TODO
FPS |  0.049 fps | 0.072 fps |
Speed 8 | | 
Time | 616m6,718s |  416m58,707s | 32,44%
FPS |  0.049 fps | 0.072 fps |


Core2Quad Q6600 2.4Ghz(SSE2 SSSE3) Endeavour OS (Archlinux-based)
0.1 Release rav1e 0.1.0 (UNKNOWN)
rav1e 0.1.0 (20191127-28-g7f6d027) Build 5.December 
[Log](https://github.com/xiph/rav1e/files/3935486/benchsave.txt)


GTA30FPS | 0.1 | pre-0.2 | change | Perf diff
------------ | ------------- | ------------- | ------------- | -------------
Speed 2 |  |
Time | 408m45,217s | 375m11,858s | 8,16% | [diffSpeed2](https://github.com/xiph/rav1e/files/3935442/rav1e0.1-0.2diffSpeed2.txt)
FPS | 0.073 fps | 0.080 fps |
Speed 4 | |
Time |322m40,287s |  295m35,611s | 8,39%
FPS | 0.093 fps | 0.102 fps |
Speed 6 | | 
Time | 197m28,395s | 165m39,063s | 16,16%  | [diffSpeed6](https://github.com/xiph/rav1e/files/3935449/rav1e0.1-0.2diffSpeed6.txt)
FPS | 0.152 fps | 0.181 fps |
Speed 8 | | 
Time |196m11,347s |  163m58,023s | 16,59%
FPS |  0.153 fps | 0.183 fps

**Comment by lu-zero** [comment]
![1080p Bosphorus Speed 10  - Encoding Speed](https://user-images.githubusercontent.com/239012/71110401-801fd600-21c7-11ea-8e48-908915bc9134.png)
![1080p Bosphorus Speed 8  - Encoding Speed-1](https://user-images.githubusercontent.com/239012/71110439-90d04c00-21c7-11ea-9227-ac342c8258a9.png)
![1080p Bosphorus Speed 6  - Encoding Speed](https://user-images.githubusercontent.com/239012/71110462-9fb6fe80-21c7-11ea-97de-a460e8ecd5cd.png)
![1080p Bosphorus Speed 4  - Encoding Speed](https://user-images.githubusercontent.com/239012/71110482-acd3ed80-21c7-11ea-977d-469783533824.png)

**Comment by lu-zero** [comment]
I guess that's all for 0.2.0.
