### ISSUE TITLE
Prominent corruption in VBR mode

### ISSUE THREAD

**Issue by dixie-flatliner** [xiph/rav1e#1857]
Some clips become intensely distorted when encoded in VBR mode. This does not occur in constant-quantizer mode. It does seem to persist across a range of bitrates, and regardless of whether or not tune=psnr or tune=psychovisual is used. Artifacting is obvious in both MPV and ffplay; screenshots are from MPV, of the unscaled video.

Conveniently, this shows up in the first 60s of _Tears of Steel_; linked download contains an uncompressed YUV clip and various encodes thereof. "defaults.ivf' is the result of not passing any settings to rav1e. "vbr.ivf" is the result of setting --bitrate=2000. "hi-" files are 3500kbps, "-psnr" files are made with tune=psnr.

https://mega.nz/#!1U13gKRa!6HUH8Z_RsP00dFP1v2S6eNEfZr8nhBhLJMjdbRCAhMQ

Screenshots:
![mpv-shot-vbr ivf-00_00_10 917-0001](https://user-images.githubusercontent.com/54378466/69098842-ff7e8600-0a1e-11ea-8156-2a0d14e67122.png)
![mpv-shot-vbr ivf-00_00_13 500-0002](https://user-images.githubusercontent.com/54378466/69098848-04433a00-0a1f-11ea-9b7c-24dedce19a16.png)
![mpv-shot-vbr ivf-00_00_18 917-0003](https://user-images.githubusercontent.com/54378466/69098852-073e2a80-0a1f-11ea-86ec-a04eb5abf1a6.png)
![mpv-shot-vbr ivf-00_00_20 792-0004](https://user-images.githubusercontent.com/54378466/69098856-09a08480-0a1f-11ea-8865-22d90bcdf322.png)
![mpv-shot-vbr ivf-00_00_25 792-0005](https://user-images.githubusercontent.com/54378466/69098858-0c02de80-0a1f-11ea-96bc-04dff3ff6f15.png)

There are other more subtle artifacts in the scenes with less obvious corruption-- check the steam/mist in the panning "40 Years Later" shot.

Used software:
__
rav1e 0.1.0 (0.1.0-19-gacb7b69) (from AppVeyor)
mpv 0.30.0-133-g35de8ea0a8 Copyright © 2000-2019 mpv/MPlayer/mplayer2 projects
built on Sun Nov 10 18:36:28 +08 2019
ffplay version git-2019-11-13-4e0860e Copyright (c) 2003-2019 the FFmpeg developers
built with gcc 9.2.1 (GCC) 20191010
__
Apologies in advance if this is a known bug (I didn't see any comparable open issues), or I've made some egregious error in the report.

**Comment by tdaede** [comment]
Could you try using two-pass mode? This may just be because first-pass does not use any lookahead yet.

**Comment by dwbuiten** [comment]
This isn't a "bug" so much as the 1-pass ratecontrol being not great - what you're seeing is due to it selecting too low of a quantizer, and blowing its bit budget, and then tanking to compensate.

This will get fixed once we introduced post-MC SATD complexity estimates in it, but for now, you can try setting the min and max quantizer to something conservative like 30 and 170 and maybe bumping the frame reservoir size.

**Comment by dixie-flatliner** [comment]
The encode is still running, but 2pass seems to do the trick. Didn't know this was a known problem, my bad.
