### ISSUE TITLE
Desync with speed 0 and 1

### ISSUE THREAD

**Issue by ycho** [xiph/rav1e#1858]
Tested with commit: acb7b69227ab29b42f8258b66d5c0dfee9a32470

./target/release/rav1e ~/Downloads/crowd_run_2160p50.y4m -o test.ivf -r test_rec.y4m --quantizer 128 --speed=1 --limit=3 --low_latency --tune=Psnr

../aom_build/aomdec test.ivf -o test_dec.y4m -v
../aom_build/aomdec test.ivf --rawvideo -o test_dec.yuv -v
ffmpeg -i test_rec.y4m test_rec.yuv -v 0
cmp test_rec.yuv test_dec.yuv

test_rec.yuv test_dec.yuv differ: char 8324073, line 1
==> difference in 2nd frame

Similar desync with speed 0. <s>1st frame is fine</s>.
Checked that it first happens at <s>the 2nd frame</s> both 1st and 2nd frame when two frames are encoded, and does. not happen if only one frame is encoded.
Speed 2, 6 and 10 were fine.

**Comment by shssoichiro** [comment]
Could you give it a test at speed 2? I'd like to see if this is likely related to bottom-up encoding.

**Comment by ycho** [comment]
Oh- Yeap, I missed stating that it was fine with speed 2!

**Comment by ycho** [comment]
If I try narrowing down the problematic area, it is inter frame & bottom-up partition search.

**Comment by ycho** [comment]
@shssoichiro 
It is possible "--tune Psnr" is causing desync for speed 0 and 1 (i.e. bottomup partition).
I tried:
 ./target/release/rav1e ~/Downloads/crowd_run_2160p50.y4m -o test.ivf -r test_rec.y4m --quantizer 128 --speed=1 --limit=2
, then it is fine.

And I tried again: 
./target/release/rav1e ~/Downloads/crowd_run_2160p50.y4m -o test.ivf -r test_rec.y4m --quantizer 128 --speed=1 --limit=2 --tune Psnr
, then desync happens.

test_rec.yuv test_dec.yuv differ: char 8418299, line 1

**Comment by barrbrain** [comment]
As far as I can tell, the desync occurs where 4x4 blocks are chosen. If I increase `min_block_size` to `BlockSize::BLOCK_8X8` keeping all other settings, then it is fine.

**Comment by ycho** [comment]
I am trying with tx_domain_distortion off now (its default is on, and used with --tune Psnr), which I suspect.

**Comment by ycho** [comment]
> I am trying with tx_domain_distortion off now (its default is on, and used with --tune Psnr), which I suspect.

There is still a desync, though different pixels are affected.

**Comment by ycho** [comment]
I tried with smaller input and 2x2 tiles, and there is also desync. Hence the issue is not specific to 4K but speed 0 or 1 with --tune Psnr.

**Comment by ycho** [comment]
Faster test:
./target/release/rav1e nyan.y4m -o test.ivf -r test_rec.y4m --quantizer 150 --speed=1 --limit=2  --low_latency --tune=Psnr

gives a desync!

**Comment by ycho** [comment]
And if I do this, it fixes for speed 1 nut speed 0 still has desync.

      //dist_scale: [1.0, lambda / lambda_u, lambda / lambda_v],
      dist_scale: [1.0, 1.0, 1.0],

i.e. if not use dist_scale[].

**Comment by ycho** [comment]
Trying with more recent commit, ed524d6c893d81c7b3b9f8122d954e078379a52e,
./target/release/rav1e nyan.y4m -o test.ivf -r test_rec.y4m --quantizer 150 --speed=1 --limit=2 --tune=Psnr
there is still desync for speed 1 with --tune Psnr. (As in split issue #, desync for speed 0 with both Psnr and Psycho")
test_rec.yuv test_dec.yuv differ: char 157117, line 113

**Comment by ycho** [comment]
Same desync occur with 1d44f9f4ea746664fbb0e32c9fca41e47f7be831
So, it seems broken before two suspected landed features, 1) Chroma scaling, 2) Activity masking

**Comment by ycho** [comment]
Located the culprit commit that causes this sync (i.e. speed 0 and 1 with --tune Psnr)
3bf1c46359ed61c9622f0f6fe8251c5a33885977

**Comment by ycho** [comment]
W/o reverting 3bf1c46, just disablling quantizer_rdo_preset() fixes the issue for both speed 0 and 1.

**Comment by ycho** [comment]
Update: It is NOT inter frame only. If two frames are encoded, both frames are affected, i.e. showing desync on both frames. However, if only one frame is encoded, there is no desync.

**Comment by ycho** [comment]
With different enc options, like more frames and smaller qndex,
./target/release/rav1e nyan.y4m -o test.ivf -r test_rec.y4m --quantizer 50 --speed=0 --limit=10

desync occur regardless --tune, with commit 1c01f90b788085e10c4ea5b2bb9206ef6b1c75d4
that is right before chroma scaling, Oct 11.

**Comment by ycho** [comment]
@shssoichiro ,
It also happens with speed 2, commit 3bf1c46359ed61c9622f0f6fe8251c5a33885977
./target/release/rav1e nyan.y4m -o test.ivf -r test_rec.y4m --quantizer 50 --speed=2 --limit=10

**Comment by ycho** [comment]
As early as b074992e54ab4067b3eabecd45110d451da95c2d has desync issue.
And now checking even earlier than it.

**Comment by ycho** [comment]
The issue only appears intermittent, depending on enc options.

**Comment by ycho** [comment]
Affected:
6b9f362fe1b7d859b07d94ee338ff99f7dca946d, Sep 3.

**Comment by ycho** [comment]
In commit 3c79e025f7c13635558ce66370920fb5a8a38754
I think speed 2 is affected because at that time it enables quantizer_rdo (With current master as of Dec 5, only speed 0 and 1 enables quantizer_rdo).

-  ///  - speed - 2, Min block size 8x8, TX domain distortion, complex pred modes for keyframes, RDO TX decision, include near MVs,
-  ///  - speed - 1, Min block size 8x8, TX domain distortion, complex pred modes, RDO TX decision, include near MVs,
-  ///  - speed - 0, slowest,  Min block size 4x4, TX domain distortion, complex pred modes, RDO TX decision, include near MVs, bottom-up encoding.
+  ///  - speed - 2, Min block size 8x8, TX domain distortion, complex pred modes for keyframes, RDO TX decision, include near MVs, quantizer RDO,
+  ///  - speed - 1, Min block size 8x8, TX domain distortion, complex pred modes, RDO TX decision, include near MVs, quantizer RDO,
+  ///  - speed - 0, slowest,  Min block size 4x4, TX domain distortion, complex pred modes, RDO TX decision, include near MVs, quantizer RDO, bottom-up encoding.

**Comment by ycho** [comment]
commit 3c79e025f7c13635558ce66370920fb5a8a38754 seems the origin of desync.
Date:   Wed Jul 31 10:27:20 2019 -0700
"Use segmentation to adjust block quantizers"
I.e. When quantizer_rdo is enabled for the 1st time for speed 0,1,2.

**Comment by ycho** [comment]
Reverting 3c79e025f7c13635558ce66370920fb5a8a38754 or disabling quantizer_rdo fixes the desync at the origin commit, however after that, commit db0da3c97efb269cb23571f2c1f68afdf1ad9813 (Add heuristic quantizer adjustment, Aug 21) causes desync again. So, I think that, before fixing those two, disabling two features will stops the desync at least temporarily on master.

**Comment by ycho** [comment]
This issue has been TEMPORARILY fixed by disabling the use of segmentation and thus quantizer rdo and heuristic quantizer selection but we will desire it fixed since it contributes to the coding efficiency significantly.

**Comment by ycho** [comment]
> This issue has been TEMPORARILY fixed by disabling the use of segmentation and thus quantizer rdo and heuristic quantizer selection but we will desire it fixed since it contributes to the coding efficiency significantly.

I will create new issue its title originates more according names, and close this issue.
