### ISSUE TITLE
Crash with OutOfMemory error when using 8K input. 

### ISSUE THREAD

**Issue by MaxValenzuela** [xiph/rav1e#1891]
```
rav1e input8k.y4m -o outputrav1e.ivf
Backtrace (most recent call first):
  File "<unknown>", line 0, in BaseThreadInitThunk
  File "<unknown>", line 0, in RtlUserThreadStart

The application panicked (crashed).
  input is not a y4m file: OutOfMemory
in src\libcore\result.rs, line 1165
thread: main
```

Also tried using --rdo-lookahead-frames with no luck.

These are the characteristics of my input as signaled by MediaInfo for reference:

> Format                                   : YUV4MPEG2
> File size                                : 1.85 GiB
> 
> Video
> Format                                   : YUV
> Width                                    : 7 680 pixels
> Height                                   : 4 320 pixels
> Display aspect ratio                     : 16:9
> Frame rate                               : 25.000 FPS
> Color space                              : YUV
> Scan type                                : Progressive
> Compression mode                         : Lossless

**Comment by lu-zero** [comment]
The problem was due y4m safety limit, https://github.com/xiph/rav1e/pull/1893 should had fixed it.

**Comment by ycho** [comment]
Hi @MaxValenzuela, thanks for trying and reporting it here. Have you tried encoding again with the master that has #1893 (increased the limit of y4m image frame size). If not, could you try encoding again please?

**Comment by ycho** [comment]
Ok. Just read that: Friday, Nov 29, "1:10 PM <Chagall> I successfully encoded 600 frames in 8K on my laptop using rav1e master"

**Comment by ycho** [comment]
@tdaede, so, I think it has been fixed by change in y4m side.

**Comment by lu-zero** [comment]
It should be fixed now. Please reopen if there are other related problems.

**Comment by MaxValenzuela** [comment]
It is working now from my side, thanks!

**Comment by ycho** [comment]
> It is working now from my side, thanks!

Awesome! Thanks for replying and confirming it!
