### ISSUE TITLE
Upstream nasm-rs uses stabs debug info for x86_64 elf

### ISSUE THREAD

**Issue by eclipseo** [xiph/rav1e#1981]
I built the rav1e binary but when I try to extract debuginfo and strip the binary, I'm encountering an issue:

```
explicitly decompress any DWARF compressed ELF sections in /builddir/build/BUILDROOT/rust-rav1e-0.2.0-1.fc32.x86_64/usr/bin/rav1e
extracting debug info from /builddir/build/BUILDROOT/rust-rav1e-0.2.0-1.fc32.x86_64/usr/bin/rav1e
Stabs debuginfo not supported: /builddir/build/BUILDROOT/rust-rav1e-0.2.0-1.fc32.x86_64/usr/bin/rav1e
Failed to update file: invalid section entry size
```
It seems there are Stabs debuginfo in the binary.

Is this normal? It prevents me from extracting the debuginfo. How can I turn that off?

**Comment by eclipseo** [comment]
(This is Rust 1.40 on x86_64)

**Comment by tdaede** [comment]
I think this should have fixed that: https://github.com/xiph/rav1e/pull/1938
Is your rav1e newer than that commit?

**Comment by eclipseo** [comment]
Yes I'm onto this commit, my nasm-rs is from upstream, that's why it doesn't include this commit. I'm in the process of patching it and see how this goes.
Can this be upstreamed otherwise?

**Comment by lu-zero** [comment]
Let's try to sync up with upstream then :) 

https://github.com/medek/nasm-rs/pulls

**Comment by lu-zero** [comment]
https://github.com/medek/nasm-rs/pull/26 is still ope with no feedback.

**Comment by lu-zero** [comment]
The upstream version 0.1.6 should work fine, could you please test it?

**Comment by lu-zero** [comment]
It does not since I managed to land a typo when I resolved a collision after a rebase :(

**Comment by barrbrain** [comment]
The upstream version 0.1.7 includes the typo fix and we now use that.
