### ISSUE TITLE
The header file generated by cinstall is not compatible with C++

### ISSUE THREAD

**Issue by yannlandry** [xiph/rav1e#2019]
Running `cargo cinstall --release` as specified in `README.md` produces a `rav1e.h` file that's not compatible for inclusion in C++ programs.

The following instructions should be added at the beginning and end of the generated header file:
```
#ifdef __cplusplus
extern "C" {
#endif
```
and
```
#ifdef __cplusplus
}
#endif
```

This will keep the library compatible with C programs while enabling compatibility with C++ programs.

**Comment by 1480c1** [comment]
I think this belongs in the cargo-c repo

**Comment by 1480c1** [comment]
Seems to stem from cbindgen maybe https://github.com/eqrion/cbindgen/issues/391

**Comment by lu-zero** [comment]
Let see if the cbindgen key works for us.

**Comment by lu-zero** [comment]
It seems to produce the correct file, please test that it works for your use-case.
