### ISSUE TITLE
downsampling is expensive

### ISSUE THREAD

**Issue by tdaede** [xiph/rav1e#2045]
```
    self.frame_data.insert(output_frameno, FrameData::new(fi, frame.clone()));
```

It would be nice to eliminate it.

**Comment by shssoichiro** [comment]
`frame` here should be an `Arc`, so cloning is just making a new pointer to the frame. Was this measured to be expensive?

**Comment by tdaede** [comment]
Oh, I just measured send_frame_properties and that ones the one thing that stuck out at me. It must actually be something else in there.

**Comment by shssoichiro** [comment]
It looks like downsampling to generate the hres and qres frames is taking the lion's share of the time there.

**Comment by tdaede** [comment]
Yup. Looks like the downsampling could be implemented quite a bit faster. It could also emit qres and hres at the same time, and could also be threaded.

**Comment by shssoichiro** [comment]
It looks like downsample is actually taking 0.27% of the total encode time at speed 10. While I think there are ways to speed it up, they would involve either unsafe code or intrinsics/ASM. I want to avoid unsafe code just to remove bounds checking, and given how small the impact of this function is overall, I don't think it's worthwhile to invest time into this function right now.
