### ISSUE TITLE
PredictionModesSetting is not processed correctly

### ISSUE THREAD

**Issue by rzumer** [xiph/rav1e#2087]
Outputting prediction modes passed to the intra prediction process, even at speed level 10, directional modes are being encoded. It seems like the setting is ignored.

**Comment by barrbrain** [comment]
In b5731b2 (Use SAD to trim the number of intra modes being evaluated in RDO), `RAV1E_INTRA_MODES_MINIMAL` was removed and all modes were evaluated for pruning.
Since 4faec27 (Prune intra modes with SATD instead of SAD.) the metric has changed.

**Comment by rzumer** [comment]
I see, so the definition changed. I would say this needs some comments to be more readable, but I was involved in the initial pruning method, so maybe it is not as confusing to someone else seeing this code for the first time. Closing anyway.
