### ISSUE TITLE
Desyncs when using AVX2 dav1d assembly with the intra edge filter

### ISSUE THREAD

**Issue by rzumer** [xiph/rav1e#2107]
Assembly for directional prediction is currently disabled, because it causes desyncs when enabling the intra edge filter. My guess is that it is related to the edge buffer. Depending on the prediction mode, different edges and corners are initialized or not, and the assembly may be sensitive to that. However, simply reverting the change made to the edge buffer initialization for native intra edge filter support (setting the top left pixel for all directional modes) does not solve the desync, so more research is needed to determine whether it is the actual cause, and if so, what is the correct way to fill the buffer.

**Comment by rzumer** [comment]
Seems like [this](https://code.videolan.org/videolan/dav1d/blob/master/src/ipred_prepare_tmpl.c#L198) needs to be implemented in partition::get_intra_edges() and handled in the native version.

**Comment by takehirokj** [comment]
I found that rav1e_ipred_z2_avx2 causes desync.
Replacing call_native to each rav1e_ipred_z1_avx2 and  rav1e_ipred_z3_avx2 doesn't
cause desync.

**Comment by rzumer** [comment]
The top left pixel filter is applied only for z2 prediction, so that makes sense. I am planning on fixing it next week.

**Comment by rzumer** [comment]
#2135 makes some progress towards fixing this, but not there yet.

**Comment by rzumer** [comment]
It seems the missing piece is the dx and dy parameters that must be passed to the z2 prediction function. It is used only for z2 and, I guess, only for the intra edge filter. I'll take a shot at it.

Corresponding dav1d code for filling those arguments [here](https://code.videolan.org/videolan/dav1d/blob/master/src/recon_tmpl.c#L1219).
