### ISSUE TITLE
Tx split for inter mode only works when reduce_tx_set is enabled

### ISSUE THREAD

**Issue by ycho** [xiph/rav1e#2122]
Investigating this and the most possible reason seems the tx_type for chroma is not derived correctly when tx-split happens in inter mode partition for certain lager partition sizes.

    let uv_tx_type =
      if partition_has_coeff { tx_type } else { TxType::DCT_DCT }; // if inter mode, uv_tx_type == tx_type

**Comment by ycho** [comment]
Need to get uv_tx_type by way of:
https://aomediacodec.github.io/av1-spec/#compute-transform-type-function

Specifically, I think this step is missing:
if ( !is_tx_type_in_set( txSet, txType ) )
 return DCT_DCT

**Comment by ycho** [comment]
Confirm that  TxType::V_DCT and TxType::H_DCT, enabled with TX_SET_INTER_2, is one of the reason for corruption. I think we have not actually used these two tx so far.

**Comment by ycho** [comment]
Also found that ADST is one of the reasons for desync (mismatch btw enc and dec images).
But, it has been fine with previously, i.e. before enabling inter tx_split?

**Comment by barrbrain** [comment]
After some exploration, it appears that `write_tx_size_inter()` currently only implements first-level splits. However, `rdo_tx_size_type()` trials up to second-level splits when `do_rdo_tx_size` evaluates to `true`. At decode this may cause the transform size to mismatch, which in turn causes the wrong CDF to potentially be picked when reading the transform type.

My exploration was with the following changes to allow the desync to be encountered:
```diff
diff --git a/src/api/config/speedsettings.rs b/src/api/config/speedsettings.rs
index c2a6eac3..837a4016 100644
--- a/src/api/config/speedsettings.rs
+++ b/src/api/config/speedsettings.rs
@@ -192,8 +192,8 @@ impl SpeedSettings {
     speed >= 8
   }
 
-  const fn reduced_tx_set_preset(speed: usize) -> bool {
-    speed >= 6
+  const fn reduced_tx_set_preset(_speed: usize) -> bool {
+    false
   }
 
   /// TX domain distortion is always faster, with no significant quality change
@@ -267,8 +267,8 @@ impl SpeedSettings {
   }
 
   // FIXME: With unknown reasons, inter_tx_split does not work if reduced_tx_set is false
-  const fn enable_inter_tx_split_preset(speed: usize) -> bool {
-    speed >= 9
+  const fn enable_inter_tx_split_preset(_speed: usize) -> bool {
+    true
   }
 
   fn fine_directional_intra_preset(speed: usize) -> bool {
diff --git a/src/rdo.rs b/src/rdo.rs
index d94d436b..1b750907 100644
--- a/src/rdo.rs
+++ b/src/rdo.rs
@@ -701,7 +701,7 @@ pub fn rdo_tx_size_type<T: Pixel>(
   let mut best_rd = std::f64::MAX;
 
   let do_rdo_tx_size =
-    fi.tx_mode_select && fi.config.speed_settings.rdo_tx_decision && !is_inter;
+    fi.tx_mode_select && fi.config.speed_settings.rdo_tx_decision;
   let rdo_tx_depth = if do_rdo_tx_size { 2 } else { 0 };
   let mut cw_checkpoint: Option<ContextWriterCheckpoint> = None;
 ```

**Comment by ycho** [comment]
Also, when I land open-partition and fixes several related and even unrelated issues for it, esp. tx context,
I have locally tested inter_tx_split is working lower speeds, like 3~8, and it worked. 
But don't remember it also worked for 0~2, which use min blk size 4x4.
Meanwhile, I remember the mib blk size inter_tx_split work was 16x16, so that it splits to 8x8.

**Comment by ycho** [comment]
Just tested again with below diff, enable_inter_tx_split is enabled for all speed level,
then it worked for speed 0 and 3. So, inter block as small as 8x8 can have 4x4 tx blocks in it.


diff --git a/src/api/config/speedsettings.rs b/src/api/config/speedsettings.rs
index c2a6eac3..1f52258c 100644
--- a/src/api/config/speedsettings.rs
+++ b/src/api/config/speedsettings.rs
@@ -268,7 +268,7 @@ impl SpeedSettings {
 
   // FIXME: With unknown reasons, inter_tx_split does not work if reduced_tx_set is false
   const fn enable_inter_tx_split_preset(speed: usize) -> bool {
-    speed >= 9
+    true//speed >= 9
   }
 
   fn fine_directional_intra_preset(speed: usize) -> bool {
diff --git a/src/rdo.rs b/src/rdo.rs
index a77d5b9e..d12f3f0f 100644
--- a/src/rdo.rs
+++ b/src/rdo.rs
@@ -712,6 +712,7 @@ pub fn rdo_tx_size_type<T: Pixel>(
   let mut cw_checkpoint: Option<ContextWriterCheckpoint> = None;
 
   for _ in 0..=rdo_tx_depth {
+    debug_assert!(!is_inter && rdo_tx_depth == 0);
     let tx_set = get_tx_set(tx_size, is_inter, fi.use_reduced_tx_set);
 
     let do_rdo_tx_type = tx_set > TxSet::TX_SET_DCTONLY

**Comment by barrbrain** [comment]
Oops, I removed the wrong `&& !is_inter` for my analysis. I intended to revert https://github.com/xiph/rav1e/commit/22bf11b7fc5ec47c2f31716fc916f8c3a5c11817 but manually edited the wrong line. I will try again with the right edit.
