### ISSUE TITLE
Replace segment selection with direct distortion scale lookup

### ISSUE THREAD

**Issue by tdaede** [xiph/rav1e#2141]
With the current distortion scales, we should be able to directly select the optimal segment without any sort of segmentation RDO. In particular, we need to do the opposite of the process described in rdo.c:distortion_scale_for.

tl;dr
```
where rdcost = D * scale + lambda * R:

scale = 2^(-2*delta_log_q)
-log2(scale)/2 = delta_log_q
segment_log_q = delta_log_q + base_log_q
```

Note that segment_log_q != segment qidx, however you can just precompute the log_q for every possible segment (or rather, threshold between segments). You'll also need to decide if you compute the threshold in log_q or linear Q space.

**Comment by barrbrain** [comment]
Note that when we rework the perceptual distortion scaling, it may be used in combination with temporal scaling for segment selection.
