### ISSUE TITLE
Fine directional prediction seems slower than it's worth at some speed levels

### ISSUE THREAD

**Issue by rzumer** [xiph/rav1e#2167]
Based on local tests and AWCY runs, I get about 10-20% higher frame rate with fine directional prediction disabled on speed level 2, while the BD-rate benefit is below 1%. I think it should be disabled by default for speed levels where it does not provide a worthwhile gain.

https://beta.arewecompressedyet.com/?job=no-fine-directional-modes-s2%402020-02-07T17%3A57%3A23.932Z&job=v0.3.0-s2%402020-02-07T12%3A33%3A40.400Z

**Comment by takehirokj** [comment]
Currently, we search fine direction around selected angle.
e.g., if n degree is best in rdo selection, then, n - 9, n - 6, ..., n + 9 are searched.

By moving this to slower settings, we can consider to search more fine directions. I confirmed it improves the quality previously.

**Comment by rzumer** [comment]
@takehirokj For -s 0 and -s 1 we may be able to tolerate relatively large performance impact, but for -s 2 and above we do not want to spend 20% more time encoding for 1% BD-rate gain. This is what we are seeing currently between speed levels 2 and 5. See A and B "Encoding Time" column [here](https://beta.arewecompressedyet.com/?job=v0.3.0-s3%402020-02-13T20%3A42%3A43.605Z&job=just-no-fine-inter-s3%402020-02-13T20%3A43%3A12.033Z) for speed 3, [here](https://beta.arewecompressedyet.com/?job=v0.3.0-s4%402020-02-13T20%3A42%3A50.379Z&job=just-no-fine-inter-s4%402020-02-13T20%3A43%3A28.492Z) for speed 4, and [here](https://beta.arewecompressedyet.com/?job=v0.3.0-s5%402020-02-13T20%3A42%3A55.981Z&job=just-no-fine-inter-s5%402020-02-13T20%3A43%3A37.254Z) for speed 5. Speed 6 and above seem OK.
