### ISSUE TITLE
Inter mode tx partition has a high encode time cost for low BD rate gain at low speed levels

### ISSUE THREAD

**Issue by rzumer** [xiph/rav1e#2169]
Below speed level 6, there is a large performance regression between rav1e 0.2 and 0.3. One of the changes causing this is https://github.com/xiph/rav1e/commit/7c4c5ef4eac1eb6a6c5853421e246528475ee5ad, which enables inter mode tx partition. For BD rate gains of about 1% the encoding time is increased by around 15-20%. At the default speed level of 6, the tradeoff is much better, but it needs to be disabled or optimized for lower speeds, at least above "exhaustive" modes (levels 0 and 1).

A comparison on AWCY between v0.3.0, v0.3.0 with fine directional prediction disabled, and v0.3.0 with fine directional prediction *and* inter mode tx partition disabled, is available [here](https://beta.arewecompressedyet.com/?job=v0.3.0-s2%402020-02-07T12%3A33%3A40.400Z&job=just-no-fine-inter-s2%402020-02-13T18%3A37%3A44.378Z&job=no-fine-dir-pred-no-tx-inter-part-s2%402020-02-13T18%3A33%3A14.757Z).

**Comment by ycho** [comment]
#2170 fixed this.
