### ISSUE TITLE
Retune speed level 5 to improve performance (speed)

### ISSUE THREAD

**Issue by rzumer** [xiph/rav1e#2182]
[This comparison](https://beta.arewecompressedyet.com/?job=master-4ab62c6273e0ec64656e85df9602a2046d0ed460&job=0.3.1_s5%402020-02-21T16%3A41%3A53.621Z) between v0.1.0 at default settings, v0.3.1 on speed 5, and v0.3.1 on speed 6, shows that while speed 6 provides much better performance at a relatively small loss in compression performance, speed 5 is only a tiny bit better in that regard, while being slower than v0.1.0 at low quantizers. This seems to indicate that there is a feature enabled that is not worth the performance tradeoff.

**Comment by ycho** [comment]
As I guess, the reason for "speed 5 is only a tiny bit better in that regard," is because of reduced_tx_set_preset(), which turn on reduced_tx (signaled at frame header) at speed >= 5 but
it is only effective at speed == 5, since there is no choice of tx type at speed > 6.

**Comment by shssoichiro** [comment]
This has been addressed in recent versions
