### ISSUE TITLE
Not setting the bitrate silently produces invalid first pass data

### ISSUE THREAD

**Issue by jamrial** [xiph/rav1e#2188]
https://github.com/xiph/rav1e/blob/8f273bcbde77e5f3711138a57c13dec9dc793973/src/bin/rav1e.rs#L170-L180

This chunk is never executed when it should. twopass_out() should return the final version of the buffer with the updated header, but it doesn't. Can be reproduced with the C API as well (see ffmpeg wrapper).

**Comment by lu-zero** [comment]
Not setting the bitrate produces this sort of erratic behavior, we are discussing how to make it impossible with the minimal API change, but it is not how you are supposed to use the rate control.

(this after I spent most of the day scanning through the commits to find a known-working one)
