### ISSUE TITLE
What is the new release v0.1.1?

### ISSUE THREAD

**Issue by marcomsousa** [xiph/rav1e#2189]
After v0.3.1 release you release

What is this new release v0.1.1?
Please clarify.

**Comment by lu-zero** [comment]
The release note is [available](https://github.com/xiph/rav1e/releases/tag/v0.1.1).

@rzumer is working on fine-tuning the speed levels and backported a fix worth a point release for the `0.1` branch. If you are happy with the `0.3` branch you may happily ignore it :)
