### ISSUE TITLE
(track): rav1e fails to compile due to err-derive using private symbol in quote

### ISSUE THREAD

**Issue by joedrago** [xiph/rav1e#2192]
I figured I'd make an issue here tracking this as I can no longer build rav1e right now, but there isn't anything for the rav1e team to do (unless you want to submit a PR to err-derive). err-derive was using `quote::__rt::TokenStream`, which I guess is a no-no, and now it is broken. Here's my GitLab issue tracking the fix in err-derive:

https://gitlab.com/torkleyy/err-derive/issues/15

**Comment by lu-zero** [comment]
Thank you for the notice, I was pondering to migrate to `thiserror`/`anyhow` if our other dependencies go in that direction.
