### ISSUE TITLE
Create rav1e glue code for dav1d 0.6.0 new ASM

### ISSUE THREAD

**Issue by shssoichiro** [xiph/rav1e#2195]
Follow-up to #2152

- [ ] Use prep_bilin/prep_8tap AVX-512 asm
- [ ] Use HBD put_8tap/prep_8tap/prep_bilin NEON asm
- [ ] Use 10-bit SGR NEON asm (specifically DOES NOT WORK with 12-bit)
- [ ] Use LBD/HBD cdef NEON asm (can we? isn't there a mismatch between our cdef and dav1d's? same for AVX-512 cdef...)

**Comment by lu-zero** [comment]
I prepared already https://github.com/medek/nasm-rs/pull/28

**Comment by shssoichiro** [comment]
Seems to be no response from the maintainer there. I hate to say we might want to fork it... but should we fork it?

**Comment by tdaede** [comment]
We've forked it before. I guess we can fork it again.

**Comment by lu-zero** [comment]
Or we can write the check in build.rs directly. Once I'm fully awake I can send a pr if nobody beats me at it.

**Comment by shssoichiro** [comment]
#2223
