### ISSUE TITLE
Test failures when using the --release option

### ISSUE THREAD

**Issue by dbermond** [xiph/rav1e#2204]
I'm getting the following test failures when running `cargo test --release`:
```
failures:
    asm::x86::mc::test::test_rav1e_prep_8tap_regular_bd_8_avx2
    asm::x86::mc::test::test_rav1e_prep_8tap_regular_bd_8_ssse3
    asm::x86::mc::test::test_rav1e_prep_8tap_regular_sharp_bd_8_avx2
    asm::x86::mc::test::test_rav1e_prep_8tap_regular_sharp_bd_8_ssse3
    asm::x86::mc::test::test_rav1e_prep_8tap_regular_smooth_bd_8_avx2
    asm::x86::mc::test::test_rav1e_prep_8tap_regular_smooth_bd_8_ssse3
    asm::x86::mc::test::test_rav1e_prep_8tap_sharp_bd_8_avx2
    asm::x86::mc::test::test_rav1e_prep_8tap_sharp_bd_8_ssse3
    asm::x86::mc::test::test_rav1e_prep_8tap_sharp_regular_bd_8_avx2
    asm::x86::mc::test::test_rav1e_prep_8tap_sharp_regular_bd_8_ssse3
    asm::x86::mc::test::test_rav1e_prep_8tap_sharp_smooth_bd_8_avx2
    asm::x86::mc::test::test_rav1e_prep_8tap_sharp_smooth_bd_8_ssse3
    asm::x86::mc::test::test_rav1e_prep_8tap_smooth_bd_8_avx2
    asm::x86::mc::test::test_rav1e_prep_8tap_smooth_bd_8_ssse3
    asm::x86::mc::test::test_rav1e_prep_8tap_smooth_regular_bd_8_avx2
    asm::x86::mc::test::test_rav1e_prep_8tap_smooth_regular_bd_8_ssse3
    asm::x86::mc::test::test_rav1e_prep_8tap_smooth_sharp_bd_8_avx2
    asm::x86::mc::test::test_rav1e_prep_8tap_smooth_sharp_bd_8_ssse3
    asm::x86::mc::test::test_rav1e_prep_bilin_bd_8_avx2
    asm::x86::mc::test::test_rav1e_prep_bilin_bd_8_ssse3

test result: FAILED. 352 passed; 20 failed; 0 ignored; 0 measured; 0 filtered out
```

This happens only when using the `--release` option. When running `cargo test` without `--release`, the tests runs fine.

Exporting/setting `RUSTFLAGS='-C target-cpu=native'` does not modify the result.

The last good commit that works for me is 4dfda58791ab7c2406bffc78cd25602fde49feac. A git bisect shows that this is caused by commit 8fa818bce51d42d180cf567d51377aa45b7aca6d.

System Information:
  - OS: Arch Linux x86_64
  - rav1e: git master
  - rust: 1.42.0 (also happened with 1.41.0)
  - NASM: 2.14.02

**Comment by xiphmont** [comment]
note that '--target-cpu=native' should be '--target-cpu=rust'.  You're still building the asm version.

**Comment by xiphmont** [comment]
Oops, I'm told 'wrong part of the build system'.

**Comment by dbermond** [comment]
@xiphmont No problem, thanks for replying and for caring about this :)

**Comment by lu-zero** [comment]
The decode tests do not fail so the problem might be only in the tests.

**Comment by dbermond** [comment]
I can confirm that commit https://github.com/xiph/rav1e/commit/c7884c929ff8f380955eaee1b1823bbc76148fa3 fixes this.

Thank you for fixing this! :)
