### ISSUE TITLE
Panic with high quantizer

### ISSUE THREAD

**Issue by takehirokj** [xiph/rav1e#2219]
```
The application panicked (crashed).
  index out of bounds: the len is 3 but the index is 3
in /home/takehiro/Dev/rav1e/src/rdo.rs, line 2133
thread: <unnamed>
```
with following command:
`cargo run --release --bin rav1e ../mov/input/objective-1-fast/aspen_1080p_60f.y4m -o ../mov/output/aspen_1080p_60f.ivf --quantizer 252` 

This is from the commit 08445210679c1bb89bdc73a0c0831cae5bc34959. Before this commit, it worked fine.

In my testing movie above (1080p), the crash occurred with quantizer with ~150 or above.

The crash might depends on the frame size because the crash did not occurred
with other small movie (320p).

**Comment by shssoichiro** [comment]
We've been discussing this in IRC, I have a fix for this crash and a test around it incoming. We also discovered a debug_assert is being hit [here](https://github.com/xiph/rav1e/blob/master/src/tiling/tile_restoration_state.rs#L367) under similar conditions which originated in #2165.

**Comment by shssoichiro** [comment]
Since #2165 is your PR, do you have input on the best way to handle it? Would a fix be something you could make quickly, or would it make more sense to revert that commit until it can be fixed and readded?

**Comment by takehirokj** [comment]
Thank for the information. The debug_assert is reproduced and I found the solution for that.

Following part of TilingInfo initialization is required for tiling in CDEF in #2165.
https://github.com/xiph/rav1e/blob/7958241f28e75dfcb315daf8ef2fe3a520bf47bc/src/encoder.rs#L617-L643

I confirmed adding above to cdef_filter_tile_group() solve the debug_assert.
I will PR for this.

**Comment by takehirokj** [comment]
It was not solved by the solution above because the above solution turned off the assert by using 1x1 tile for CDEF.
By updating it to 2x2 CDEF tiles more than caused the debug_assert.

However, there's another solution for this.
I will made the issue for this and would like to discuss about the debug_assert there.
