### ISSUE TITLE
Code actual transform sizes for intra frames.

### ISSUE THREAD

**Issue by tdaede** [xiph/rav1e#222]
We currently set the header to TX_LARGEST rather than TX_SELECT. We'd rather use the latter, which means we'll actually need to code TX size symbols. They are coded totally differently for inter and intra sadly, so do this on intra frames only first.

For now, match the behavior by just choosing a TX size that matches the partition size.

**Comment by barrbrain** [comment]
As I understand, this is complete since #1505 was merged.

**Comment by ycho** [comment]
Right, I can recall the PITA when writing code for it! :) Many thanks for cleaning up  missed-to-close issues!
