### ISSUE TITLE
multiple allocations for lookahead intra costs

### ISSUE THREAD

**Issue by KyleSiefring** [xiph/rav1e#2277]
It says here that lookahead intra costs are allocated once per frame.
https://github.com/xiph/rav1e/blob/master/src/encoder.rs#L737
But the only place they are set allocates.
https://github.com/xiph/rav1e/blob/master/src/api/internal.rs#L714
https://github.com/xiph/rav1e/blob/master/src/api/lookahead.rs#L29

**Comment by shssoichiro** [comment]
It's small, but it's something. PR incoming.
