### ISSUE TITLE
Split the context.rs into smaller blocks

### ISSUE THREAD

**Issue by vibhoothiiaanand** [xiph/rav1e#2282]
Currently, [context.rs](https://github.com/xiph/rav1e/blob/master/src/context.rs) is getting larger and larger, now it is having ~4471 Lines of Code, it would be nice if we start breaking functions into smaller functions to increase readability.

~Currently, it has functions for the following:~
- [ ] ~Partitions~
- [ ] ~Blocks~
- [ ] ~CFL~
- [ ] ~Transformations~
- [ ] ~CDF Context~
- [ ] ~Block, Planes offsets~
- [ ] ~Motion Vectors~
and more...

Splitting based on Block hierarchy is a better choice :
- [ ] Frame
- [ ] Tile
- [ ] Block
- [ ] Superblock
- [ ] Partition
- [ ] Transform

**Comment by tdaede** [comment]
I think if you want to split context.rs, the better dividing line is hierarchy in the bitstream. e.g. superblock, partition, block.

**Comment by vibhoothiiaanand** [comment]
@tdaede Yeah that makes more sense, I will try to do it like that.

**Comment by vibhoothiiaanand** [comment]
Fixed with #2303
