### ISSUE TITLE
Overwrite prompt missing.

### ISSUE THREAD

**Issue by qrpnxz** [xiph/rav1e#2295]
Please add something to the effect of

`Are you sure you want to override "preciousbits.ivf"? [y/N]`

I just got burned by the lack of this little tidbit.
Thanks.

**Comment by tdaede** [comment]
We can either do an interactive prompt, with a -y override, or an uninteractive error, with a -f override. Opinions?

**Comment by gnafuthegreat** [comment]
My vote would be for an interactive prompt with a -y override, similar to ffmpeg.

**Comment by Urhengulas** [comment]
Since the issue is assigned to @Dayof I guess it's taken?
