### ISSUE TITLE
4:2:2/4:4:4 desync on 4x4 blocks with intra edge filter

### ISSUE THREAD

**Issue by rzumer** [xiph/rav1e#2299]
Found through [a master branch run](https://beta.arewecompressedyet.com/?job=rav1e-master-s0-422%402020-05-13T17%3A17%3A37.637Z). See the log.

[This](https://beta.arewecompressedyet.com/?job=rav1e-s0-422-prev%402020-05-13T19%3A32%3A47.030Z) run, though incomplete, shows that this was not introduced by #2224.

Also reproduced on 4:4:4 locally.

Probably due to above/left block contexts not properly taking sampling format into account.

**Comment by ycho** [comment]
commit ace686ddb84bf2abb937172093e6ae7b523d593f
./target/release/rav1e ~/sequences/flower_garden_422_ntsc.y4m -o test.ivf -r test_rec.y4m --quantizer 20 --speed=2 --limit=3 --rdo-lookahead-frames=1 --low_latency # mismatch, when sub 8x8 used!

**Comment by rzumer** [comment]
#2083 seems to have caused it.

**Comment by ycho** [comment]
Some more info:
The other smaller frame size video, https://media.xiph.org/video/derf/y4m/football_422_qcif.y4m, also gives the mismatch.
./target/release/rav1e ~/sequences/football_422_qcif.y4m -o test.ivf -r test_rec.y4m --quantizer 20 --speed=2 --limit=3 --rdo-lookahead-frames=1 --low_latency

And, I have diff image for you, which has mismatch in the 1st frame.
<img width="434" alt="Screen Shot 2020-05-15 at 10 55 37 AM" src="https://user-images.githubusercontent.com/10123259/82081322-f18e8280-969a-11ea-98b6-ff167d2ad292.png">
The black grid is 64x64, so there are rowxcol = 3x3 SBs, and the 1st mismatch occur at SB (row, col) = (0,2).
Meanwhile, please note that AOM Analyzer does not decode and display 422 bitstream correctly, adding lots of artifacts, which seems wrong. The aomdec or dav1d decode correctly.

**Comment by ycho** [comment]
To obtain diff image, I have used https://github.com/IENT/YUView.

**Comment by barrbrain** [comment]
I have confirmed that the reproduction in https://github.com/xiph/rav1e/issues/2299#issuecomment-629399836 is resolved by #2313.
