### ISSUE TITLE
v0.3.1 with asm feature doesn't build

### ISSUE THREAD

**Issue by njaard** [xiph/rav1e#2338]
The HEAD version is fine. Can you expedite a v0.3.2 release?

```
$ cargo build --release --no-default-features --features=asm
...
   --> src/asm/x86/transform/inverse.rs:67:33
    |
67  |               out[get_tx_type_idx($ENUM)] = Some([<rav1e_inv_txfm_add_$TYPE2 _$TYPE1 _$W x $H _$OPT_LOWER>]);
    |                                   ^^^^^ expected expression
```

**Comment by rzumer** [comment]
A patch update to the `paste` dependency broke this. Until a v0.3.2 is released, you can either set the version in `Cargo.toml` to 0.1.12 and rebuild, or cherry-pick https://github.com/xiph/rav1e/commit/ee60ee1f52430506a6ac6a1d8e48ce8efcc95fff.

**Comment by paolobarbolini** [comment]
Now that v0.3.2 has been tagged could we also get it on crates.io? @lu-zero

**Comment by shssoichiro** [comment]
Update: If you are on 0.3.1, an update to the `paste` dependency has been published that fixes the breakage. So you can run `cargo update -p paste` to pull the new version, and it should compile.

**Comment by rzumer** [comment]
Since a fresh build even on v0.3.1 will now compile correctly I think this issue can be closed.
