### ISSUE TITLE
Deprecate wiki

### ISSUE THREAD

**Issue by Urhengulas** [xiph/rav1e#2346]
## Change
As briefly talked about in the #daala-weekly yesterday, the wiki is quite outdated and should be deprecated.

The question is: **Which of the pages should be kept and moved to the `doc/` folder?** The others will just be deleted.

## Pages
| file                          | purpose                                              | author(s)         | action |
| :---------------------------- | :--------------------------------------------------- | :---------------- | :----- |
| `Frame-Type-Selection.md`     | Explains frame type selection                        | shssoichiro       | pick   |
| `Home.md`                     | Short hello message                                  | mbebenita         | drop   |
| `Quality-&-Speed-Features.md` | Various features compared to compeititors (outdated) | mbebenita, rzumer |        |
| `Roadmap.md`                  | Feature plan for AV1 Encoder                         | mbebenita, negge  |  drop  |

## Procedure
It's obvious that `Home.md` can be dropped, but for the others I would just like consult the authors (@shssoichiro, @mbebenita, @rzumer, @negge).

Please state if the page should be kept, and if yes, if it needs to be updated :)
Thank you! :smile:

**Comment by shssoichiro** [comment]
We specifically wanted the frame type selection algorithm documented, so I think it makes sense to move it to the doc folder. I updated the version in the wiki just now to accurately reflect the codebase.

**Comment by Urhengulas** [comment]
@mbebenita, @rzumer, @negge: Could you please give a short info about your respective pages?

Thank you a lot! :smiley:

**Comment by Urhengulas** [comment]
@barrbrain 

What is the deal with `doc/regress_log-bitrate_wrt_log-quantizer.ipynb` ? Is it still needed? If yes, what for? If we keep it, I would like to add a brief descrption to it.
