### ISSUE TITLE
CLI asks if you want to overwrite /dev/null

### ISSUE THREAD

**Issue by shssoichiro** [xiph/rav1e#2353]
We should special case /dev/null so no confirmation is required to write to it.

**Comment by rzumer** [comment]
An OS-specific special case sounds hacky.

**Comment by barrbrain** [comment]
I think in general we should check whether the path is a regular file if it exists. While POSIX APIs enable this, I'm not sure whether it would require OS-specific checks to cover all platforms.

**Comment by lu-zero** [comment]
We can use [this](https://doc.rust-lang.org/beta/std/os/unix/fs/trait.FileTypeExt.html) and also provide a `--no-output`/`-no` to make simpler to not produce an output in general.
