### ISSUE TITLE
How to disable loop restoration filter?

### ISSUE THREAD

**Issue by zyue128** [xiph/rav1e#2385]
Hi, 
    I am trying to run some performance comparison with restoration filter ON/OFF. I read that there is no CLI to disable the loop restoration in issue #1671, but could not find the code in the codebase to disable it as in the reply:
https://github.com/xiph/rav1e/issues/1671#issuecomment-534795444
    Could you please let me know how can I disable the lrf? Thank you.

**Comment by shssoichiro** [comment]
As you know we try to keep the settings simple, so most settings are controlled only by the speed level. Right now LRF is enabled at speeds <= 9, and disabled at speed 10.

If you want to manually change any of the settings in the codebase, you can update the presets in [src/api/config/speedsettings.rs](https://github.com/xiph/rav1e/blob/master/src/api/config/speedsettings.rs#L255).

**Comment by zyue128** [comment]
Thank you so much for your help!
