### ISSUE TITLE
Readme links to 404

### ISSUE THREAD

**Issue by DanielHeath** [xiph/rav1e#2392]
https://people.xiph.org/~mbebenita/analyzer/inspect.wasm doesn't seem to exist any more.

**Comment by lu-zero** [comment]
The machine hosting the file had an hardware problem.

Please try https://dev.gentoo.org/~lu_zero/inspect/inspect.wasm meanwhile.

**Comment by vibhoothiiaanand** [comment]
Now it is updated and added a mirror too,

https://github.com/xiph/rav1e/blob/master/doc/AOM_ANALYZER.md
