### ISSUE TITLE
Windows builds

### ISSUE THREAD

**Issue by Uch1haOb1to** [xiph/rav1e#2397]
The button with AppVeyor builds disappeared. Did I understand correctly that Windows builds are no longer being made, or I just can’t find them?

**Comment by Urhengulas** [comment]
See https://github.com/xiph/rav1e/pull/2327

**Comment by Urhengulas** [comment]
Follow up:

You can find the windows builds attached to the releases. E.g. https://github.com/xiph/rav1e/releases/tag/v0.3.2

**Comment by Uch1haOb1to** [comment]
> https://github.com/xiph/rav1e/releases/tag/v0.3.2

Thanks I know, I use this release.
And the solution to the problem in this issue #2404
The question is closed.
