### ISSUE TITLE
Where to get Windows build?

### ISSUE THREAD

**Issue by Draghmar** [xiph/rav1e#2402]
Hi.
Now, when appveyor is removed, where do I get Windows builds?

**Comment by Urhengulas** [comment]
You can find them attached to the releases.

E.g. https://github.com/xiph/rav1e/releases/tag/v0.3.2

**Comment by Draghmar** [comment]
So no cutting edge, frequent releases from now on? :(

**Comment by lu-zero** [comment]
I'll try to get back to make pre-releases more often, sadly I had to focus on something different in the past months.
