### ISSUE TITLE
"Enable NEAR_NEAR1MV compound mode" impacts default speed bdrate

### ISSUE THREAD

**Issue by KyleSiefring** [xiph/rav1e#2439]
Thomas told me 5f6345bbf6b53e36b6fad5ecf9862b1de175a8ad shouldn't have an impact on default speed levels. This is broken according to AWCY.

https://beta.arewecompressedyet.com/?job=master_30aad0e%402020-07-08T16%3A09%3A11.135Z&job=master_5f6345b%402020-07-08T15%3A59%3A13.962Z

**Comment by tdaede** [comment]
This is because the patch caused the near speedlevel setting to be respected, which ended up disabling NEAR_NEAR0 on default speed. We could add a finer control to speed levels to bring it back.
