### ISSUE TITLE
[WIP] Motion Estimation Overhead

### ISSUE THREAD

**Issue by KyleSiefring** [xiph/rav1e#2449]
Written as of 01052fc7121114904501f81f52a234c96373829d.

I'm going to start at the tail end of the call stack and work up from there.
<details>
  <summary>get_mv_rate</summary>

https://github.com/xiph/rav1e/blob/01052fc7121114904501f81f52a234c96373829d/src/me.rs#L1015-L1031
</details>

I think this could use a rewrite. Checking if d == 0 shouldn't be necessary and ilog would work here. Unfortunately, the baseline x86/x86_64 will still have a branch here because bsr is undefined for 0. In a more positive light, the compiler manages to implement the conditional shift without a branch a la `diff >> ((allow_high_precision_mv as i16) ^ 1)`.

<details>
  <summary>compute_mv_rd_cost</summary>

https://github.com/xiph/rav1e/blob/01052fc7121114904501f81f52a234c96373829d/src/me.rs#L852-L869
</details>

We have a branch for calling sad vs satd. We call get_mv_rate here twice. There are definitely places in the code where both pmvs are always the same. There will be some dependency chains when reducing the results in sad/satd, so this might not be super critical. You also have a multiply at the end which will be fairly expensive.

It _might_ be worth skipping rdo for half res and quarter res search. The code already decreases lambda in those cases. I have done awcy runs testing this and the results are seem favorable. My concern is that our coarse search is primitive.

<details>
  <summary>predict_inter, predict_inter_single, predict_inter_compound</summary>

https://github.com/xiph/rav1e/blob/01052fc7121114904501f81f52a234c96373829d/src/predict.rs#L280-L413
</details>

`predict_inter_single` is called from `get_mv_rd_cost` (motion search) and `predict_inter` is called in `motion_compensate`. Every time `predict_inter_single` is called, you need to index three time are and check an `Option`. This is silly. Our motion search is already working on a single reference frame at a time and has the plane loaded. Also, it would be very concerning if the `if let` is not to be taken for most, if not all, the code calling predict_inter and friends. `diamond_search` (I haven't checked full search) even creates an uninitialized buffer for subpel.

After indexing and handling the `Option`, we need to get the appropriate `PlaneSlice` from a `Plane`. First, we get a frame offset from our tile. We are already using frame offsets when calling this from motion search. We have `.slice(qo).clamp().subslice(3, 3)` which is a bit weird. Unless this is in the spec, silently changing the input parameters is probably not the greatest. Doing a bounds check may be preferable.

We have our `PlaneSlice`. Is it over? No. Inside put_8tap (and prep_8tap), we must get the appropriate pointer for the x and y coordinates stored in the `PlaneSlice`. To do this we must compute `base_ptr + row * stride + col`. Once we are searching subpel, the row and col should only change by one and thus wouldn't need to multiply. Here is an untested way to do this.

```
ptr
  + if (((center_mv.1 - diff.1) ^ center_mv.1) & 16) != 0 { neg_stride } else { 0 }
  - (((((center_mv.0 - diff.0) ^ center_mv.0) & 16) != 0) as isize)
```

`predict_inter_compound` needs to do all this twice, but is called through 'motion_compensate'.

To Be Continued...

**Comment by shssoichiro** [comment]
Re "We have a branch for calling sad vs satd." that branch is likely being elided by the compiler since we always inline this function. Other than that these seem like reasonable points of improvement.

**Comment by KyleSiefring** [comment]
`diamond_me_search` passes `use_satd` to `get_mv_rd_cost` and `use_satd` is also determined by a runtime option.
