### ISSUE TITLE
Padded encoded image resolution

### ISSUE THREAD

**Issue by farindk** [xiph/rav1e#2477]
I've recently added rav1e as an AVIF encoder option to libheif. Now, I'm facing the following problem:

When I'm encoding an "odd" input frame size of, e.g., 65x65, rav1e will in fact round this up to multiples of 8. In this case 72x72. In AVIF, I'll then have to specify the crop area to bring this back to 65x65.

However, because of the stupid way the crop area has to be specified (relative to the image center), I need to know the encoded image size. Now, how to I get this? Can I savely assume that rav1e will always round this up to multiples of 8, or can this depend on some encoding parameters (e.g., number of tiles rows)?

Is there any rav1e API to know the output size without having to parse the encoded stream?

**Comment by farindk** [comment]
I parsed the AV1 stream generated by rav1e for a 65x65 image by hand and saw that the sequence header in fact contains `max_image_width', 'max_image_height' = 65. However, when decoding this with libaom, it is decoded to 72x72.

**Comment by farindk** [comment]
Ok, found it. aom_image stores the displayed width in `d_w`. I was using `w.

**Comment by tdaede** [comment]
FWIW rav1e doesn't do any "rounding up" of the image size, the AV1 bitstream contains the exact input resolution.

**Comment by farindk** [comment]
@tdaede Yes, I was looking at the wrong place. I thought that AV1 might have similar restrictions like h265, which always rounds up to the smallest CU size and displayed width can only be specified in terms of chroma resolution. I.e. no odd sizes are possible.
But in fact, I was just reading the wrong size fields from the AOM image structure.
