### ISSUE TITLE
Varying quality per plane

### ISSUE THREAD

**Issue by kornelski** [xiph/rav1e#2513]
When compressing YUV 444 content I would like to quantize UV channels more heavily, since they don't need as much quality as the Y channel. 

This is a trick that can be used in JPEG to get files smaller than with subsampled chroma, without chroma subsampling: (exaggerated example):

 
![foo](https://user-images.githubusercontent.com/72159/90983788-76c1e700-e568-11ea-8b63-77f996869718.jpg)

**Comment by dwbuiten** [comment]
This is something we do internally already internally, see, for example https://github.com/xiph/rav1e/commit/c49c6c40c05fc97ee0109fcffa41a67db35fc78b.

I believe all of @barrbrain's notebooks are availale somewhere for the analysis we did.

Are you saying you would rather set it manually?

**Comment by kornelski** [comment]
Oh, cool. I wasn't aware that's already built-in. In that case it's not necessary to change anything.
