### ISSUE TITLE
crates.io release?

### ISSUE THREAD

**Issue by kornelski** [xiph/rav1e#2515]
Could you make a release to crates.io that contains a fix for writing `Cs400`?

In v0.3.3 use of YUV400 chroma throws `unimplemented!()`, and I need it to write AVIF files with alpha. Git pre-release works fine, but I can't depend on it in a crates.io crate.

If you don't have a stable version ready, it'd be OK to release `0.4.0-alpha` or such.

**Comment by lu-zero** [comment]
We should have a 4.0 soon.

**Comment by lu-zero** [comment]
I guess we could consider releasing an `-alpha` this week.

**Comment by lu-zero** [comment]
from the `-alpha` to `0.4.0` it took a fair amount of time but we are done now :)
