### ISSUE TITLE
Support inputs smaller than 16 pixels

### ISSUE THREAD

**Issue by kornelski** [xiph/rav1e#2518]
Currently rav1e refuses to encode inputs smaller than 16px in width or height. This is problematic for AVIF support, because tiny images like that are sometimes used.

If it's not too hard, could you remove the limitation?

**Comment by barrbrain** [comment]
See https://github.com/xiph/rav1e/pull/1798 for context. The consensus among contributors at the time was that smaller widths and heights were non-conformant.

**Comment by kornelski** [comment]
I see [libaom has inherited](https://docs.rs/libaom-sys/0.6.1/libaom_sys/struct.aom_image.html) from libvpx:

* Stored image width
* Displayed image width
* Intended rendering image width


I presume stored image width would be limited to 16.

I guess displayed/intended width could be smaller than 16? (I'm not sure what's the distinction between these two)

Are these stored in the AV1 stream? Can I instruct rav1e to write to metadata a size other than pixel size of the input?

**Comment by ycho** [comment]
For 15x15 size, 420 input, I've tried to hard code the two places:
https://github.com/xiph/rav1e/blob/0fb9209b8294989db500a48867c6300ea47e56c8/src/api/config/mod.rs#L253
and 
https://github.com/xiph/rav1e/blob/0fb9209b8294989db500a48867c6300ea47e56c8/src/api/config/mod.rs#L256

replacing 16 with 1, then both aomdec and dav1d was able to decode a frame.
(I've only tried this for one frame!)

15x15 size y4m file and output ivf are attached.
[test.ivf.gz](https://github.com/xiph/rav1e/files/5172638/test.ivf.gz)
[test03_15x15.y4m.gz](https://github.com/xiph/rav1e/files/5172641/test03_15x15.y4m.gz)

**Comment by ycho** [comment]
> See #1798 for context. The consensus among contributors at the time was that smaller widths and heights were non-conformant.

Hmm, I found;
"FrameWidth is greater than or equal to 16
FrameHeight is greater than or equal to 16"
in https://aomediacodec.github.io/av1-spec/#levels.
so, minimum frame size 16x16 is a normative.

**Comment by adityapatadia** [comment]
The PR was closed so it means AVIF images can't be encoded with Rav1e in reliable manner for now. Hmm!

**Comment by lu-zero** [comment]
It means that smaller-than-16pixel images have to be encoded as 16x16 images and then cropped down to the smaller resolution, possibly at container level. Can you please attach an aom-produced 1pixel image?

**Comment by adityapatadia** [comment]
@farindk might be able to provide it.

**Comment by farindk** [comment]
Attached is a 1x1 AVIF image encoded with aom. The actual av1 stream starts at 0x148.
I also included the mp4 box dump. The file decodes correctly in Chrome 85, too.

[1x1.zip](https://github.com/xiph/rav1e/files/5223470/1x1.zip)

If sizes < 16 pixels should not be supported by the encoder (even though there seems no hard _technical_ reason as aom can do it), I can alternatively store those images as 16x16 and then crop to the final size in the AVIF container.

**Comment by kornelski** [comment]
The 1x1.avif reports two different image sizes, where "stored" width/height is 8x8, but "displayed" and "intended rendering" sizes are 1x1. How can I set the latter two in rav1e?

```js
aom_image {
    w: 8,
    h: 8,
    d_w: 1,
    d_h: 1,
    r_w: 1,
    r_h: 1,
}
```

**Comment by lu-zero** [comment]
Which tools did you use to extract this information?

**Comment by kornelski** [comment]
That's straight from [libaom's](https://gitlab.com/kornelski/aom-decode) image struct.

**Comment by rzumer** [comment]
I think the specification may allow sub-16x16 frame sizes if the level is set to "unconstrained parameters", but the wording is ambiguous.

**Comment by lu-zero** [comment]
Can you please attach the header decoded?

**Comment by kornelski** [comment]
I'm not sure what you mean. This is information from AV1 payload only, not from MP4 metadata. I don't have an AV1 parser, so I'm reporting what already-parsed `aom_image_t` struct contains.

**Comment by lu-zero** [comment]
I assumed that @rzumer was using this [one](https://github.com/yohhoy/av1parser), tonight hopefully I'll have time to have a look at it.

**Comment by rzumer** [comment]
@lu-zero I just looked at the text file in the archive posted by @farindk above, but av1parser is also fine.

**Comment by farindk** [comment]
The AVIF file structure dump I posted above is generated with `heif-info -d ...`, part of [libheif](https://github.com/strukturag/libheif).

**Comment by kornelski** [comment]
I'd like to clarify that the two differing sizes are both from the AV1 payload, not from HEIF. I have deliberately ignored everything that HEIF says, because it's not relevant in this case. HEIF is a redundant copy of this information. Also Chrome rejects AVIF images that have AV1 state different dimensions than HEIF does, so I can't just fix HEIF implementation without also embedding correct size in AV1 itself.

**Comment by farindk** [comment]
@kornelski: you can encode as 16x16 and add a crop transformation (`clap` box) in the AVIF container to get to 1x1.
