### ISSUE TITLE
An error code

### ISSUE THREAD

**Issue by zhuyu198728** [xiph/rav1e#2542]
> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ParseIntError { kind: InvalidDigit }', src\bin\common.rs:672:26
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

The related script I used:

> C:\FFMpeg\ffmpeg.exe -i "RAW.avs" -f  yuv4mpegpipe -pix_fmt yuv420p -s 3840x1600 - | C:\Encoder\rav1e.exe --quantizer 50 --speed 1 --frame-rate 23.976 --primaries BT2020 --transfer SMPTE2084 --matrix BT2020NCL --mastering-display "G(13250,34500)B(7500,3000)R(34000,16000)WP(15635,16450)L(40000000,50)" --content-light "1242,436" - -o "ERAW.ivf"

**Comment by lu-zero** [comment]
omit the `--frame-rate` or use it with `--time-scale`

**Comment by barrbrain** [comment]
```
--frame-rate <FRAME_RATE>
    Constant frame rate to set at the output (inferred from input when omitted)

--time-scale <TIME_SCALE>
    The time scale associated with the frame rate if provided (ignored otherwise) [default: 1]
```
* `--frame-rate` is inferred from input when omitted. This is best if the source stream has an accurate frame rate.
* The NTSC film frame rate can be precisely expressed: `--frame-rate 24000 --time-scale 1001`

**Comment by zhuyu198728** [comment]
Thanks guys
