### ISSUE TITLE
Confusing error message when inputting video with unsupported bit depth

### ISSUE THREAD

**Issue by zhuyu198728** [xiph/rav1e#2543]
When I use VS as source, it gives me this error code:

> !! Could not input video. Is it a y4m file?

my script is:

> vspipe --y4m RAW.vpy -  | C:\Encoder\rav1e.exe --quantizer 60 --speed 1 --frame-rate 24000 --time-scale 1001 - -o RAW.ivf

**Comment by shssoichiro** [comment]
My first guess is that this would be due to an error in your vapoursynth script. Can you run `vspipe -i RAW.vpy -` to verify that?

**Comment by zhuyu198728** [comment]
> My first guess is that this would be due to an error in your vapoursynth script. Can you run `vspipe -i RAW.vpy -` to verify that?

![test](https://user-images.githubusercontent.com/71317215/93246226-0bfa7900-f7bf-11ea-8549-bdb0326b62e6.jpg)
 I guess this means the script and environment is fine? It could also run properly in VSEditor though.

**Comment by shssoichiro** [comment]
Ah, I believe the issue is that rav1e currently only supports 8, 10, and 12 bit input. We should probably update the error message to indicate that.

**Comment by 123mansha** [comment]
hey!! I am a newbie can you help me in suggesting what's to be done or improved

**Comment by zhuyu198728** [comment]
> hey!! I am a newbie can you help me in suggesting what's to be done or improved

Well, the error code is confusing, when it ask me "is it a y4m file?", but the real issue is that the bit depth of the input file is not in the supported range. So just change the corresponding error code to, like "bit depth is not supported".

**Comment by rzumer** [comment]
There are other cases where the error message is inappropriate, it needs to be reviewed and ideally we would have different error messages for detectable situations like this one.
