### ISSUE TITLE
rav1e silently clips out of range values passed to mastering-display

### ISSUE THREAD

**Issue by jamrial** [xiph/rav1e#2555]
`rav1e input.y4m --mastering-display="G(1.1,1.1)B(1.1,1.1)R(1.1,1.1)WP(1.1,1.1)L(10,1)" -o output.ivf`

Passing out of range values like 1.1 in the above example results in the Metadata OBU containing 65535 as value for all primary_chromaticity_x and primary_chromaticity_y fields, which is the max value that can be written and the equivalent of 0.9999847412109375 in 0.16 fixed point format, as per the spec.

rav1e should warn or abort if the values passed for R, G, B and WP are outside of the 0.0-0.9999847412109375 range (or maybe just 0.0-1.0).

**Comment by jamrial** [comment]
What's with the labels, if you don't mind me asking?

**Comment by vibhoothiiaanand** [comment]
@jamrial Hi,
I thought it wouldn't be a complex task as compared to other issues open, so labelled, so if anyone else who like to start contribution can try to start with this :).

**Comment by jamrial** [comment]
I see, thanks for the clarification.
