### ISSUE TITLE
Protocol "https" not supported or disabled in libcurl

### ISSUE THREAD

**Issue by JonasVautherin** [xiph/rav1e#2579]
I am trying to cross-compile VLCKit for iOS, and I have this error when building rav1e. I first thought it was [a cargo issue](https://github.com/rust-lang/cargo/issues/8788), but it seems like it's running this `cargo capi` extension that they don't know about. I have been tracking this error for a few days, trying to find somebody who may know where it comes from :innocent:. Could it come from rav1e, or a dependency of rav1e?

**Problem**
When cross-compiling VLCKit for iOS (aarch64, though armv7 seems to work), I get the following error:

```
touch .cargo
cd rav1e && export TARGET_CC=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang && export TARGET_AR=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar && export TARGET_CFLAGS="-mios-version-min=9.0 -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.0.sdk -Werror=partial-availability -fno-stack-check -I/Users/jones/Documents/px4/VLCKit/libvlc/vlc/build-iphoneos-arm64/contrib/arm64-iphoneos14.0/include -g -O2" && export RUSTFLAGS="-C lto -C panic=abort -C opt-level=z" && export RUSTUP_USE_HYPER=1 && . /Users/jones/Documents/px4/VLCKit/libvlc/vlc/contrib/bin/.cargo/env && RUSTUP_HOME=/Users/jones/Documents/px4/VLCKit/libvlc/vlc/contrib/bin/.rustup CARGO_HOME=/Users/jones/Documents/px4/VLCKit/libvlc/vlc/contrib/bin/.cargo cargo capi install --target=aarch64-apple-ios --prefix=/Users/jones/Documents/px4/VLCKit/libvlc/vlc/build-iphoneos-arm64/contrib/arm64-iphoneos14.0 --library-type staticlib --release --locked --no-default-features --features=asm
Error: CliError { error: Some(failed to download from `https://crates.io/api/v1/crates/time/0.1.44/download`

Caused by:
    [1] Unsupported protocol (Protocol "https" not supported or disabled in libcurl)), exit_code: 101 }
```

As can be seen above, the command that fails is: `cargo capi install --target=aarch64-apple-ios --prefix=/Users/jones/Documents/px4/VLCKit/libvlc/vlc/build-iphoneos-arm64/contrib/arm64-iphoneos14.0 --library-type staticlib --release --locked --no-default-features --features=asm`

**Steps**

1. Clone VLCKit (https://code.videolan.org/videolan/VLCKit)
2. Run the script: `./compileAndBuildVLCKit.sh -a aarch64 -v`. May need some patches as reported in [my report here](https://code.videolan.org/videolan/VLCKit/-/issues/437).
3. Observe that the error happens

**Notes**

Running on macOS Catalina 10.15.7

**Comment by lu-zero** [comment]
You seem to have an incomplete libcurl around and it is being used to build the cargo crate used by cargo-c.
What does 
```
otool -L `which cargo-cinstall`
```
say?

**Comment by JonasVautherin** [comment]
It says: `error: 'cargo-cinstall': No such file or directory`. Could it be the issue, or is it just that the VLCKit toolchain somehow gets it for me during the build?

**Comment by lu-zero** [comment]
It seems a problem in the VLCKit toolchain, please report the problem there.

**Comment by JonasVautherin** [comment]
Right, I did, but I thought I could help more than that. It seems like it happens when building rav1e (`cd rav1e && ...`), so I thought I would ask here. But if rav1e does not use `cargo capi`, I guess I'll stop here.

Thanks for the help!

**Comment by lu-zero** [comment]
Please open an issue there so I can debug it, tomorrow I'll try to reproduce locally. It looks like this:
``` diff
+++ b/contrib/src/cargo/rules.mak
@@ -29,10 +29,10 @@ endif
 # installation should go in a different package
 .cargo: rustup
        cd $< && RUSTUP_INIT_SKIP_PATH_CHECK=yes \
          RUSTUP_HOME=$(RUSTUP_HOME) CARGO_HOME=$(CARGO_HOME) \
          ./rustup-init.sh --no-modify-path -y
        $(RUSTUP) default stable
        $(RUSTUP) target add $(RUST_TARGET)
        unset PKG_CONFIG_LIBDIR PKG_CONFIG_PATH CFLAGS CPPFLAGS LDFLAGS; \
-               $(CARGO) install $(CARGOC_FEATURES) cargo-c
+               $(CARGO) install $(CARGOC_FEATURES) cargo-c --features curl-sys/static-curl
        touch $@
```
may solve your problem

**Comment by JonasVautherin** [comment]
I opened it here: https://code.videolan.org/videolan/VLCKit/-/issues/438. Should we continue the discussion there?

In the meantime, I will try your patch on my macOS.

**Comment by lu-zero** [comment]
I didn't check, looks like it would require a change in cargo as well since feature forwarding isn't working for more than 1 level.
