### ISSUE TITLE
Linking error when cross compiling to aarch64-apple-darwin target

### ISSUE THREAD

**Issue by EwoutH** [xiph/rav1e#2601]
I tried cross-compiling rav1e from `x86_64-apple-darwin` to the `aarch64-apple-darwin` target (on Rustc 1.49.0-beta.2), and it failed while on linking rav1e. 

The full log can be found in this run [starting at line 92](https://github.com/EwoutH/rav1e/runs/1487102011#step:12:92) of the build step.
```
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-arch" "arm64" "-L" "/Users/runner/.rustup/toolchains/beta-x86_64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib" "/Users/runner/work/rav1e/rav1e/target/aarch64-apple-darwin/release/deps/rav1e.10utxkcv71e68b7c.rcgu.o" "/Users/runner/work/rav1e/rav1e/target/aarch64-apple-darwin/release/deps/rav1e.10yus5ksl057ygch.rcgu.o" "/Users/runner/work/rav1e/rav1e/target/aarch64-apple-darwin/release/deps/rav1e.11al8o6kw9fhx7gc.rcgu.o" 
....
```
And from [line 95](https://github.com/EwoutH/rav1e/runs/1487102011#step:12:95):
```
  = note: Undefined symbols for architecture arm64:
            "_rav1e_inv_txfm_add_flipadst_flipadst_4x4_16bpc_neon", referenced from:
                rav1e::asm::aarch64::transform::inverse::INV_TXFM_HBD_FNS::hbad123e9dd01a6df in rav1e.rav1e-2481e4f9553b2a72.icqhj6knk353rpc.rcgu.o.rcgu.o
            "_rav1e_inv_txfm_add_flipadst_dct_4x4_16bpc_neon", referenced from:
                rav1e::asm::aarch64::transform::inverse::INV_TXFM_HBD_FNS::hbad123e9dd01a6df in rav1e.rav1e-2481e4f9553b2a72.icqhj6knk353rpc.rcgu.o.rcgu.o
...
```
Exact details about the build environment [here](https://github.com/EwoutH/rav1e/runs/1487102011#step:1:1) and about the Rust installation and toolchain [here](https://github.com/EwoutH/rav1e/runs/1487102011#step:7:1).

**Comment by EwoutH** [comment]
@lu-zero Thanks for implementing a fix so quickly! On my [CI branch](https://github.com/EwoutH/rav1e/tree/ci-ub) the cargo build and cargo-c builds now pass, but one of the tests [still fails](https://github.com/EwoutH/rav1e/runs/1499389018?check_suite_focus=true#step:13:377):
```
error: test failed, to rerun pass '-p ivf --lib'

Caused by:
  could not execute process `/Users/runner/work/rav1e/rav1e/target/aarch64-apple-darwin/debug/deps/ivf-1558c2c4a7d89135` (never executed)
```

**Comment by lu-zero** [comment]
Seems that the binary is not working, can you try to put the same CI on a tiny project and see if the problem is just something upstream rust-lang (or github) has to tackle?

**Comment by EwoutH** [comment]
Hmmm I will give it a try. Could it be that it tries to execute aarch64 code on a x86_64 host?

**Comment by nilleb** [comment]
Hey, I have just executed a `cargo test` on `master` (`64051920e674af6fe56f52c2a4cf99bc3a7287e8`) and everything
works like a charm.

**Comment by lu-zero** [comment]
> Hmmm I will give it a try. Could it be that it tries to execute aarch64 code on a x86_64 host?

I think so. Thanks to @nilleb for confirming :)

**Comment by EwoutH** [comment]
In that case let's wait until macOS runners with Apple Silicon become available to test the aarch64 builds on. 

For now I opened a PR to add cargo build and cargo-c build jobs to GitHub Actions (#2605).

**Comment by fxcoudert** [comment]
We're trying to build at Homebrew: https://github.com/Homebrew/homebrew-core/pull/67767
including the commit at https://github.com/xiph/rav1e/commit/64051920
