### ISSUE TITLE
Some tests occasionally fail due to non-determinism(?)

### ISSUE THREAD

**Issue by primeos** [xiph/rav1e#2625]
I already noticed this once and another such example is here: https://github.com/NixOS/nixpkgs/pull/107751#issuecomment-751573997

<details>
<summary>---- asm::x86::quantize::test::dequantize_test stdout ----</summary>
<pre>
thread 'asm::x86::quantize::test::dequantize_test' panicked at 'assertion failed: `(left == right)`

�[1mDiff�[0m �[31m< left�[0m / �[32mright >�[0m :
 [
     -22816,
     20280,
     -26168,
     -23800,
     15816,
     -7512,
     -26448,
     23280,
     2728,
     -6648,
     -21544,
     14528,
     -14120,
     -21480,
     32536,
     7816,
     -25216,
     22456,
     5696,
     18568,
     12816,
     28864,
     -19688,
     30408,
     30936,
     -20744,
     26072,
     25416,
     26432,
     2560,
     23456,
     30568,
     -15272,
     -4072,
     1792,
     3120,
     -8704,
     -20640,
     -10400,
     -24064,
     -27480,
     -9544,
     -29328,
     13160,
     19520,
     5112,
     32240,
     -12184,
     -4064,
     11120,
     -17952,
     23808,
     -25544,
     32280,
�[31m<�[0m�[31m    -3276�[0m�[1;48;5;52;31m7�[0m�[31m,�[0m
�[32m>�[0m�[32m    -3276�[0m�[1;48;5;22;32m8�[0m�[32m,�[0m
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
 ]

', src/asm/x86/quantize.rs:84:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

failures:
    asm::x86::quantize::test::dequantize_test

test result: FAILED. 391 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
</pre>
</details>

The failure isn't really reproducible (e.g. the next 4 rebuilds succeeded in my case) and I suspect the failures are due to some non-determinism in the code.

Are you already aware of this (I didn't see any other issues that mention determinism) and do such reports help (I assume the actual causes are unfortunately difficult to track down so I can simply ignore these failures in the future if you want)?

**Edit:** Here is the output from the other failure that I noticed a month ago (I saved the output in case it could be useful):

<details>
<summary>---- asm::x86::quantize::test::dequantize_test stdout ----</summary>
<pre>
test rate::test::blog64_bexp64_round_trip ... ok

failures:

---- asm::x86::quantize::test::dequantize_test stdout ----
thread 'asm::x86::quantize::test::dequantize_test' panicked at 'assertion failed: `(left == right)`

Diff < left / right > :
 [
     18992,
     13944,
     -19264,
     26984,
     4336,
     14264,
     -16272,
     -19832,
     -11432,
     23248,
     -7584,
     27848,
     1240,
     24264,
     10368,
     24328,
     -21976,
     -17368,
     -24000,
     -13000,
     5544,
     13576,
     1880,
     -4168,
     -30696,
     -24832,
     -24208,
     -30352,
     11016,
     14032,
     7872,
     -20496,
     -4432,
     -29800,
     -13016,
     25992,
     -1016,
     -18152,
     27752,
     18208,
     6096,
     26336,
     -32120,
     880,
     448,
     -22512,
     -5456,
     -21352,
     -4552,
     -26040,
     23560,
     8264,
     11472,
     176,
     -26488,
     -5072,
     18272,
     -12024,
     -912,
     8912,
     31320,
     4568,
     9000,
     16736,
     -15840,
     12968,
     9648,
     -8688,
     -15848,
     -1184,
     -25552,
     5264,
     -30640,
     -4480,
     19800,
     -10240,
     -9536,
     24560,
     -18816,
     29096,
     26448,
     -29816,
     -28488,
     3544,
     -28112,
     17624,
     -1424,
     15816,
     -31728,
     -1912,
     -27384,
     -15448,
     31912,
     -28376,
     -16432,
     -29688,
     2752,
     -13160,
     -29432,
     -32128,
     30560,
     21160,
     23688,
     3368,
     -31944,
     22288,
     32752,
     18216,
     16376,
     -7144,
     -5864,
     8752,
     -32136,
     7704,
     20280,
     -7216,
     31344,
     20184,
     20928,
     -5016,
     -16488,
     13208,
     -1856,
     -21560,
     -30016,
     -5616,
     -31272,
     13368,
     15304,
     14136,
     -30480,
     15144,
     27848,
     27936,
     26856,
     21120,
     -7016,
     -16856,
     -30448,
     -28160,
     3192,
     1352,
     -14272,
     2656,
     8376,
     32672,
     24304,
     11800,
     6136,
     -13216,
     -27424,
     976,
     31984,
     -20616,
     14792,
     21720,
     -30808,
     25216,
     -896,
     -4480,
     31776,
     -9520,
     -4336,
     29592,
     16112,
     2088,
     -7848,
     784,
     -22528,
     624,
     13360,
     -5560,
     -28472,
     7912,
     3408,
     6720,
     -3992,
     -15232,
     32088,
     22632,
     2944,
     -1304,
     -5472,
<    -32767,
>    -32768,
     -21816,
     -8232,
     -31328,
     -26016,
     -8480,
     26176,
     4280,
     19032,
     -26392,
     -23464,
     -9240,
     23168,
     4288,
     -12440,
     -15408,
     -12440,
     -472,
     -16912,
     -13688,
     -28200,
     -11632,
     6952,
     -528,
     -25256,
     -10184,
     -16560,
     -24752,
     1472,
     31448,
     -26536,
     -29608,
     -9584,
     -31952,
     8688,
     30872,
     29320,
     -11864,
     -15272,
     12392,
     -15768,
     -26608,
     15176,
     -30632,
     11864,
     -26640,
     9224,
     31272,
     -21040,
     26872,
     29264,
     25768,
     -10160,
     -11160,
     4456,
     -30568,
     -16088,
     32040,
     21848,
     -30256,
     25000,
     -28160,
     -64,
     -9592,
     -12424,
     -31752,
     -18664,
     19936,
     15264,
     -12392,
     0,
     0,
     0,
 ]

', src/asm/x86/quantize.rs:84:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

failures:
    asm::x86::quantize::test::dequantize_test

test result: FAILED. 391 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--lib'
</pre>
</details>

**Comment by lu-zero** [comment]
Can you please provide more context (e.g. rustc version, environment)? I never experienced this error locally and on the CI.

**Comment by lu-zero** [comment]
Apparently I'm lucky: https://github.com/xiph/rav1e/pull/2312 should address it.

**Comment by primeos** [comment]
For the additional context:
- rustc/cargo version: 1.47.0
- OS: NixOS (builds run inside a sandbox)
- Anything else that would help / be important?

[I could also attach the complete build dependency tree but GitHub objects ("You can't comment at this time — your comment is too long (maximum is 65536 characters)." :D - I could of course use a Gist but I doubt that it's important anyway).]

> Apparently I'm lucky: #2312 should address it.

Great! :) I guess we can close this issue then given that there's already another one (I forgot to search issues by the test name, sorry about that).

**Comment by lu-zero** [comment]
No problem, thank you a lot for reminding us.
