### ISSUE TITLE
Build of rav1e 0.3.5 on Alpine Linux fails for aarch64 and ppc64le with bus error

### ISSUE THREAD

**Issue by OTLabs** [xiph/rav1e#2637]
Build for Alpine Linux [1] fails with same error for both architectures: 

```
365    Finished release [optimized + debuginfo] target(s) in 13m 46s
366 Bus error (core dumped)
367 >>> ERROR: rav1e: build failed

```

Build log for aarch64 is here [2], for ppc64le is here [3].

[1] https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/16346
[2] https://gitlab.alpinelinux.org/otlabs/aports/-/jobs/292026#L366
[3] https://gitlab.alpinelinux.org/otlabs/aports/-/jobs/283623#L369

**Comment by lu-zero** [comment]
Can you please provide the stand alone command that is failing? Which kind of hardware is used to run those jobs?

**Comment by OTLabs** [comment]
Sure, with pleasure.

I use:
```
build() {
	cargo build --release --frozen
	cargo cbuild --release --frozen --prefix /usr
}
```

It is the same build procedure used to successfully build rav1e 0.3.4.

I will investigate about used hardware and comment later.

**Comment by lu-zero** [comment]
So to reproduce it I'd have to run `cargo cbuild` (which cargo-c version?) on native power9 and aarch64?

**Comment by OTLabs** [comment]
cargo-c (0.7.0-r0) was used.

Sorry, I still have no info about hardware.

**Comment by barrbrain** [comment]
From the build logs:
```
(12/15) Installing cargo-c (0.7.0-r0)
```

**Comment by Ikke** [comment]
Running this on our CI host (qemu) as our builders (LXC on baremetal) results in the same:

```gdb
Program received signal SIGILL, Illegal instruction.
0x0000fffff7be64d0 in ?? () from /usr/bin/../lib/libcrypto.so.1.1
```
Our builder runs on Ampere eMAG servers, but as this seems to happen on both qemu as baremetal, it does not seem to be hardware related.

**Comment by lu-zero** [comment]
It seems that the openssl provider is doing something fishy.

**Comment by Ikke** [comment]
It's strange though that we get a SIGBUS normally, and a SIGILL when running under gdb.

**Comment by lu-zero** [comment]
Can you confirm that the current cargo-c release does not show the problem?

**Comment by OTLabs** [comment]
Currently rav1e 0.4.0 was built with cago-c 0.7.1 without any problem.

**Comment by OTLabs** [comment]
Tried to build rav1e 0.4.1 with cargo-c 0.8.0 and got no any .so libraries built. I was expecting to get: librav1e.so.0 and librav1e.so.0.4.1.

**Comment by lu-zero** [comment]
Could you please open an issue on [cargo-c](https://github.com/lu-zero/cargo-c) ? I think it is due how the musl target is managed, if you want shared libraries on a musl-based distribution it requires probably some cli overrides.

**Comment by OTLabs** [comment]
Done! https://github.com/lu-zero/cargo-c/issues/180

**Comment by OTLabs** [comment]
rav1e 0.4.1 with cargo-c 0.8.0  builds as expected with `--library-type staticlib --library-type cdylib`.
