### ISSUE TITLE
Squared artefacts on image when converting to AVIF 

### ISSUE THREAD

**Issue by vatsaljrathod** [xiph/rav1e#2662]
Getting square artefacts at the right edge of the image while converting jpg to avif using av1 compression. Adding some example it might be useful.

[Already checked with libheif,](https://github.com/strukturag/libheif/issues/424#issuecomment-770804317) as per them bug should be in encoding application.  One observation is, if we scale down speed setting then we are not getting these artefacts.

[squared_artefacts_samples.zip](https://github.com/xiph/rav1e/files/5920307/squared_artefacts_samples.zip)

**Comment by adityapatadia** [comment]
I should mention that this issue only comes with version 0.4.0. Everything works fine with 0.3.4.

**Comment by lu-zero** [comment]
Could you please provide more information on how you produced the file?

**Comment by adityapatadia** [comment]
It was produces using https://github.com/strukturag/libheif library. That library was in turn used inside https://github.com/lovell/sharp to generate image.

When we downgraded Rav1e, the issue went away hence reported here.

**Comment by lu-zero** [comment]
If you can provide the settings in use and, even better a command line, it would be great.

**Comment by vatsaljrathod** [comment]
Apologies for the delayed response.

Here is the setting I have used. Here speed >5 is causing the issue. 
sharp: 0.27.0
libvips: 8.10.5
libheif: 1.10.0
```
let image = await sharp(inputImage)

  let resizeOptions = {
    kernel: 'lanczos3',
    fastShrinkOnLoad: true,
    width: 388,
    height: null,
    withoutEnlargement: true,
    fit: 'inside'
  };

  let heifOptions = {
    quality: 60,
    compression: 'av1',
    lossless: false,
    speed: 8
  }

  let imageBuffer = await image
    .rotate()
    .resize(resizeOptions)
    .sharpen()
    .heif(heifOptions)
    .toBuffer({resolveWithObject: true});
```
