### ISSUE TITLE
Allow to use the global threadpool

### ISSUE THREAD

**Issue by RReverser** [xiph/rav1e#2684]
Currently, the encoder only allows to create its own dedicated threadpool and use it for encoding operations.

However, in a larger app it would be useful to reuse the globally preconfigured threadpool so that 1) same config could be used for all threads and 2) threads could be shared not just within the encoder itself, but with other tasks in the app equally.

More generally, does the lib part of the encoder really need an API to create its own threadpool? It seems like something that belongs to the application code, as it's normally configured globally for all threads for reasons outlined above.

**Comment by lu-zero** [comment]
> Currently, the encoder only allows to create its own dedicated threadpool and use it for encoding operations.
> 
> However, in a larger app it would be useful to reuse the globally preconfigured threadpool so that 1) same config could be used for all threads and 2) threads could be shared not just within the encoder itself, but with other tasks in the app equally.

There is already an unstable API `Config::with_thread_pool(mut self, pool: Arc<ThreadPool>) -> Self` that will be probably part of the stable API with `0.5`. 

We are testing it in rav1e-by-gop already, does it work for your use case?

> More generally, does the lib part of the encoder really need an API to create its own threadpool? It seems like something that belongs to the application code, as it's normally configured globally for all threads for reasons outlined above.

You assume that the application is already using rayon, this may or may not be the case.

Adding the support for the rayon global threadpool while not breaking the currently supported use-cases requires quite a large refactoring, help would be very welcome.

**Comment by RReverser** [comment]
> You assume that the application is already using rayon, this may or may not be the case.

Not really, why? If it doesn't, then Rayon - being the dependency of rav1e - will initialise global thread pool automatically anyway, with default settings (number of threads == CPUs), while applications (including rav1e's own CLI) can configure rayon only if they want to.

I've seen the API above, but it doesn't solve this issue because it doesn't allow to reuse the rayon's implicit global thread pool, and requires user application to still create their own explicit instance.

**Comment by RReverser** [comment]
> Adding the support for the rayon global threadpool while not breaking the currently supported use-cases requires quite a large refactoring, help would be very welcome.

If that would be accepted, I can take a look at it, yeah.

**Comment by negge** [comment]
> If that would be accepted, I can take a look at it, yeah.

Absolutely. We would also welcome discussing the design with you, feel free to join us on freenode IRC in #daala.

**Comment by lu-zero** [comment]
> > You assume that the application is already using rayon, this may or may not be the case.
> 
> Not really, why? If it doesn't, then Rayon - being the dependency of rav1e - will initialise global thread pool automatically anyway, with default settings (number of threads == CPUs), while applications (including rav1e's own CLI) can configure rayon only if they want to.

The application might want to restrict the number of threads used even if it does not want to know about rayon. rav1e is used from non-rust language as well and in that case the application does not have the option :)

**Comment by lu-zero** [comment]
> > Adding the support for the rayon global threadpool while not breaking the currently supported use-cases requires quite a large refactoring, help would be very welcome.
> 
> If that would be accepted, I can take a look at it, yeah.

That's great! Thank you a lot :)

**Comment by RReverser** [comment]
> rav1e is used from non-rust language as well and in that case the application does not have the option :)

Then it can be part of the C API, just not Rust API?

I just think that the Rust part should be a bit more idiomatic in this regard :)

**Comment by lu-zero** [comment]
> > rav1e is used from non-rust language as well and in that case the application does not have the option :)
> 
> Then it can be part of the C API, just not Rust API?

No, applications should not have to be aware of the use of rayon as much as possible. 

Right now rayon and wasi do not mix so the least application have to deal with it the easier is for them to build for the wasi target without concerns.

> I just think that the Rust part should be a bit more idiomatic in this regard :)

I implemented the support for the global/current threadpool in the channel-api, let me know if it works well enough for your use-case.

(help in fixing https://github.com/xiph/rav1e/pull/2665 is very welcome if you want it for the current send/receive API)

**Comment by RReverser** [comment]
> No, applications should not have to be aware of the use of rayon as much as possible.

If anything, this change will / would make applications even _less_ aware of Rayon if they don't want any special config. Right now, number of threads is part of rav1e's `Config` API, whereas with Rayon you don't normally need to set this.

Either way, let me prototype it as mentioned above and let's discuss on the actual PR - it's a bit easier than in abstract :)

**Comment by RReverser** [comment]
> I implemented the support for the global/current threadpool in the channel-api, let me know if it works well enough for your use-case.

Btw, looking at the PR you linked, it makes it Wasm-incompatible, but it's in fact exactly the usecase I'm interested in (want to try to add rav1e to [Squoosh](https://squoosh.app/)). We have adapter code that allows to use Rayon on the Web and planning to OSS it soon, but it only works as a global threadpool, and hence incompatible with current API.

**Comment by lu-zero** [comment]
rav1e for the wasm target mocks away rayon completely, but if you have an implementation of rayon that works you should be able to use the channel api.

**Comment by RReverser** [comment]
@lu-zero Haha, that's literally what I did in my branch in the end, oh well.

**Comment by RReverser** [comment]
> @lu-zero Haha, that's literally what I did in my branch in the end, oh well.

Even the differences in conflicts are rather small 😅 I was going to send a PR after some testing.

![image](https://user-images.githubusercontent.com/557590/110638140-1877f100-81a6-11eb-91b6-f5b95bdb29cd.png)


![image](https://user-images.githubusercontent.com/557590/110638114-0eee8900-81a6-11eb-8773-824aa42a9a5c.png)
