### ISSUE TITLE
pre-transform diff function not autovectorizing

### ISSUE THREAD

**Issue by KyleSiefring** [xiph/rav1e#2695]
https://github.com/xiph/rav1e/blob/d5df5b7b5a106e7430f8d285a50d1f9ddd9f4413/src/encoder.rs#L1052

Last time I checked, this method isn't autovectorizing. Don't feel like checking again, but it should be the same.

**Comment by shssoichiro** [comment]
There does seem to be some autovectorizing going on when I run cargo asm. Not as good as handrolled asm but I think it's good enough to close this ticket.
