### ISSUE TITLE
error[E0596]: cannot borrow data in a `&` reference as mutable

### ISSUE THREAD

**Issue by jiapei100** [xiph/rav1e#2700]
`cargo install cargo-c` gives the following **ERROR** message:

```
error[E0596]: cannot borrow data in a `&` reference as mutable
   --> ~/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-0.51.0/src/cargo/ops/registry/auth.rs:179:22
    |
179 |             writeln!(child.stdin.as_ref().unwrap(), "{}", token).chain_err(|| {
    |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ cannot borrow as mutable

error: aborting due to previous error

For more information about this error, try `rustc --explain E0596`.
error: failed to compile `cargo-c v0.7.3+cargo-0.51`, intermediate artifacts can be found at `/tmp/cargo-install744pgj`

Caused by:
  could not compile `cargo`.

To learn more, run the command again with --verbose.
```

**Comment by lu-zero** [comment]
Please report issues about `cargo` to the [project](https://github.com/rust-lang/cargo/issues) and provide more information such as what toolchain you are using. I looked at the code and it did not change in master.

**Comment by lu-zero** [comment]
Please make sure you have a toolchain that is at least `1.48.0`, better if it is the current stable.

**Comment by lu-zero** [comment]
Our own toolchain requirement is now at least `1.51.0`. Please reopen if you have problems after you update the toolchain.
