### ISSUE TITLE
nasm fails to find the linker

### ISSUE THREAD

**Issue by kornelski** [xiph/rav1e#2712]
**Describe the bug**
Build failure on Windows 10 with NASM version 2.15.05 compiled on Aug 28 2020

**To Reproduce**
`cargo install cavif`

**Required Information**
rustc 1.51.0 
rav1e-0.5.0-alpha

**Console Output**

```text
  C:\Users\Nikon the Third\.cargo\registry\src\github.com-1ecc6299db9ec823\rav1e-0.5.0-alpha\src/x86/sse.asm:472: warning: trailing garbage after macro name ignored [-w+other]
  C:\Users\Nikon the Third\.cargo\registry\src\github.com-1ecc6299db9ec823\rav1e-0.5.0-alpha\src/x86/sse.asm:442: ... from macro `WEIGHTED_SSE' defined here
  thread 'main' panicked at 'NASM build failed. Make sure you have nasm installed. https://nasm.us: "failed to spawn process: The system cannot find the file specified. (os error 2)"', C:\Users\Nikon the Third\.cargo\registry\src\github.com-1ecc6299db9ec823\rav1e-0.5.0-alpha\build.rs:120:6
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Originally reported here:

https://github.com/kornelski/cavif-rs/issues/26

**Comment by lu-zero** [comment]
You do not have `lib.exe` in your path. nasm-rs people should copy what cc-rs is doing I'm afraid.

**Comment by kornelski** [comment]
Ahh, I overlooked the actual message due to an earlier warning.

I suggest that you copy mozjpeg-sys approach to use nasm for .o files, and then cc to link them:

https://github.com/kornelski/mozjpeg-sys/blob/master/src/build.rs#L276

https://github.com/kornelski/mozjpeg-sys/blob/aefcf66f3a338fe902e06ac7271ea96af03d1e97/src/build.rs#L176

**Comment by lu-zero** [comment]
Sounds an interesting workaround, do you have time to send a patch ? ^^
