### ISSUE TITLE
Migrate to Travis-CI.com

### ISSUE THREAD

**Issue by Minoru** [xiph/rav1e#2753]
Hi! Travis-ci.org [is shutting down](https://blog.travis-ci.com/2021-05-07-orgshutdown) in a week, on June 15th. Repositories are advised to move to Travis-ci.com; repo owner can just go to https://github.com/xiph/rav1e and sign up there — everything will be migrated automatically (I did this to my own project a while ago). The only thing left to update would be the badge address in the README.

Travis also has [a new pricing system](https://docs.travis-ci.com/user/billing-overview/) where OSS projects get a limited amount of "credits" to spend on their builds. There is a non-automatic way to request more. It doesn't look like rav1e spends a lot of Travis CI time, so it might be okay with the default amount of credits.

**Comment by shssoichiro** [comment]
Closing this as this seems to have been resolved by moving to Github Actions.
