### ISSUE TITLE
Incorrectly encoded edge of a frame

### ISSUE THREAD

**Issue by kornelski** [xiph/rav1e#2757]
**Describe the bug**
Artifacts at the right edge of the frame:
<img width="147" alt="Screen Shot 2021-06-27 at 14 35 02" src="https://user-images.githubusercontent.com/72159/123546548-eb4f4e80-d754-11eb-974e-b1e2c57595d2.png">

**To Reproduce**
Encode ![resized](https://user-images.githubusercontent.com/72159/123546468-898ee480-d754-11eb-94e2-4865778828ea.jpg) (I've used `cavif --speed=10 -f image.jpg`)

**Expected behavior**
There should be no dashed lines at the edge.

**Required Information**
This has regressed in cfb9ef1773e8cd288523575febb944d6e3009733

**Comment by vibhoothi** [comment]
On the quick debugging from @barrbrain , in the Watercooler meeting today(02/07) it was noted that, it might be a corner case of the Open-partition implementation with not-common ratio of the image.

**Comment by kornelski** [comment]
It's the same issue as #2662

**Comment by barrbrain** [comment]
I was able to reproduce this pattern of artefacts with the rav1e binary:
```
ffmpeg -i issue-2757.jpg issue-2757.y4m
rav1e --tile-cols 4 -s 10 -o issue-2757.ivf issue-2757.y4m
```

**Comment by barrbrain** [comment]
The underlying issue appears to be in how we calculate the residual when the visible width of a transform block is less than the transform width.
