### ISSUE TITLE
rav1e 0.5.0 beta GIT panics on the slow scene-detection 

### ISSUE THREAD

**Issue by BlueSwordM** [xiph/rav1e#2793]
**Describe the bug**
Encoding any file with the slow speed detection flag/preset active makes the encoder panic.

**To Reproduce**
1. Build rav1e git normally.
2. Encode any file using the slow scene detection or anything speed 6 or below(`--speed 6` or `--scd_speed 0`)

**Expected behavior**
It should be encoding normally.

**Required Information**

$ rav1e --version
rav1e 0.5.0-beta (p20210831-2-g9dba7a3d) (release)

Operating system:
Openmandriva 4.3 RC with Kernel 5.13

**Console Output**

Command line output with backtrace:
https://pastebin.com/pMbtQEWz

Command line output with backtrace using this PR:
https://github.com/xiph/rav1e/pull/2792
https://patch-diff.githubusercontent.com/raw/xiph/rav1e/pull/2792.patch

**Comment by lu-zero** [comment]
https://github.com/xiph/rav1e/pull/2792 should fix it.

**Comment by BlueSwordM** [comment]
It works now. Thank you for the fix.

**Comment by BlueSwordM** [comment]
Well, I've noticed something else now.

When using slow speed detection, the encoding speed is now massively reduced on the default speed 6.

**Comment by BlueSwordM** [comment]
The issue has been fixed entirely.
