### ISSUE TITLE
example populating frame with actual (non zero) data

### ISSUE THREAD

**Issue by whiterabbit42k** [xiph/rav1e#2799]
I cannot figure out how to populate a frame with data. The example explicitly calls out that it is sending 0'd data. I assume I'm supposed to use something in Plane to populate with yuv data, but it isn't clear to me how to do this, and the documentation there is thin. I also don't know if I'm supposed to continually assign to each plane in the frame after calling `new_frame()` or should i store the frame and copy data to it then do `send_frame`

An example encoding say, 1-10 frames of RGBA data (can just be random noise), using the Encoder api would be extremely helpful.

**Comment by barrbrain** [comment]
> I also don't know if I'm supposed to continually assign to each plane in the frame after calling `new_frame()` or should i store the frame and copy data to it then do `send_frame()`

This might have been closed early. The existing example sends a single frame repeatedly but an example of sending different frames was requested.
