### ISSUE TITLE
Problem with C api

### ISSUE THREAD

**Issue by sati32** [xiph/rav1e#2815]
Visual Studio linker can't find the C api function.
I think this is a problem like mentioned here:
https://githubmemory.com/repo/lu-zero/cargo-c/issues/58

**Comment by lu-zero** [comment]
which version of cargo-c are you using ? How are you producing the library?

**Comment by sati32** [comment]
sorry, I think, I used an old one.
I now switched to the latest one. At the moment the linker is missing GetUserProfileDirectory().

**Comment by sati32** [comment]
OK, I added UserEnv.lib to my project and now I can save AVIF images with rav1e encoding :-)
But it takes much time to code. Is this library a release or debug version?

**Comment by sati32** [comment]
Still a little bit slow, but I managed to save pictures with metadata and transparency.

**Comment by lu-zero** [comment]
> But it takes much time to code. Is this library a release or debug version?

You should give us more information `cargo cbuild`, as `cargo build` does, defaults to debug profile, you may pass `--release` to request a release build.

`cargo cinstall`, as `cargo install` does, defaults to `--release`. Which version of cargo-c are you using?

**Comment by sati32** [comment]
sorry, but I work with Visual Studio with Windows.
So I am not able to compile the library myself. I used the download version from here.

**Comment by shssoichiro** [comment]
Given that this is a support question rather than a bug, I'm going to close this. If you still need help, I recommend you stop by our IRC channel #daala on [Libera.Chat](https://libera.chat/). You can also use a [web client](https://web.libera.chat/?channel=#daala) to join with a web browser.
