### ISSUE TITLE
Boundary behavior worst-case

### ISSUE THREAD

**Issue by tdaede** [xiph/rav1e#2823]
![extensiontest](https://user-images.githubusercontent.com/1308314/135982277-d8e9f401-5353-4736-ac2c-97a1a3cf8528.png)

```
cargo run -- extensiontest.y4m -r extensiontest_rec.y4m -o extensiontest.ivf -y --quantizer 200
```

Before #2822:
![extensiontest_before2822](https://user-images.githubusercontent.com/1308314/135982866-6805a2a3-e0c3-4356-8eda-7b294cc4d745.png)

After #2822:
![extensiontest_after2822](https://user-images.githubusercontent.com/1308314/135982976-6491661d-3c26-4ed8-b129-2716a5e8aadf.png)

After #2821:
![extensiontest_after2821](https://user-images.githubusercontent.com/1308314/135983163-cf6bc9ce-7c1b-45f7-8978-7c6e0eb63f42.png)

**Comment by tdaede** [comment]
Here's an alternative, simpler but non-worst-case image:

![extensiontest2](https://user-images.githubusercontent.com/1308314/135985366-8f75bcb2-7e8e-43e5-a9e6-791e036dbd3b.png)

![extensiontest2_master](https://user-images.githubusercontent.com/1308314/135985272-bc1e2944-eae6-4c8d-8c5d-a3a098a98226.png)

**Comment by tdaede** [comment]
With rav1e speed 0 it's oddly asymmetric:

![extensiontest_speed0](https://user-images.githubusercontent.com/1308314/136007181-ef812745-6895-4eff-a519-c0803fe9812c.png)

**Comment by barrbrain** [comment]
Adjusting my aggregation method, here is relative MSE partitioned by distance from the boundary, up to a superblock.
This result is the current values versus computing the residual with simple padding of the input image.
![relative_mse](https://user-images.githubusercontent.com/220594/136345816-8abc7947-1b2b-42c6-86be-11ff252fc0de.png)
