### ISSUE TITLE
Fails to build with the latest nightly rust toolchain

### ISSUE THREAD

**Issue by luigi311** [xiph/rav1e#2845]
**Describe the bug**
Rav1e will not build with the newest rust nightly toolchain due to using an old version of vergen with the following error message error[E0658]: the `must_not_suspend` lint is unstable. Vergen needs to be updated to the latest version to fix the issue https://github.com/rustyhorde/vergen/releases/tag/5.1.17

**To Reproduce**
Install rust nightly and build rav1e. In my case im building in github action using this to install rust nightly
 - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
            profile: default
            default: true
            components: rustfmt, clippy

**Expected behavior**
rav1e builds successfully

**Required Information**
Toolchain (if is a build problem):
```
  /github/home/.cargo/bin/rustc -V
  rustc 1.58.0-nightly (baba6687d 2021-11-03)
  /github/home/.cargo/bin/cargo -V
  cargo 1.58.0-nightly (94ca096af 2021-10-29)
  /github/home/.cargo/bin/rustup -V
  rustup 1.24.3 (ce5817a94 2021-05-31)
```
Version:
```
$ rav1e --version
```
Operating system:
```
$ uname -a
```

**Console Output**
Please paste the console output below if it is relevant,
<Details>
Snippet here
</Details>

**Comment by lu-zero** [comment]
I used `rustc 1.58.0-nightly (baba6687d 2021-11-03)` and I couldn't reproduce the problem.

**Comment by luigi311** [comment]
Your right i just built it clean on a docker image from rust nightly and it works. Closing the ticket.
