### ISSUE TITLE
core dump encoding on a xeon  e5-2670 running ubuntu 20.04

### ISSUE THREAD

**Issue by confusedcharlotte** [xiph/rav1e#2859]
Getting this in syslog after a core dump of the release target
rav1e[25990] trap invalid opcode ip:559e3f4f9426 sp:7fb9c9d86258 error:0 in rav1e[559e3f247000+2d4000]

Prologue in the encoding terminal looks like this:

>  CPU Feature Level: SSE4_1
>  Using y4m decoder: 3840x2160p @ 24000/1001 fps, 4:2:0, 10-bit
>  Encoding settings: keyint_min=12 keyint_max=240 quantizer=100 bitrate=0 min_quantizer=0 low_latency=false tune=Psychovisual rdo_lookahead_frames=40 min_block_size=4x4 max_block_size=64x64 multiref=true fast_deblock=false reduced_tx_set=false tx_domain_distortion=false tx_domain_rate=false encode_bottomup=true rdo_tx_decision=true prediction_modes=Complex-All include_near_mvs=true scene_detection_mode=Standard cdef=true use_satd_subpel=true non_square_partition=false enable_timing_info=false fine_directional_intra=true
>  Using 1 tile

What else do you need to diagnose what's going on?

Edit: disabling feature asm allows the encoding to proceed, though more slowly
Edit: tag v0.4.1 works as expected.

**Comment by lu-zero** [comment]
Can you please provide a backtrace using gdb or lldb?

**Comment by confusedcharlotte** [comment]
from gdb
>Thread 2 "rav1e" received signal SIGILL, Illegal instruction.
[Switching to Thread 0x7f2c4ad86700 (LWP 80540)]
0x000056063b1b9426 in rav1e_put_8tap_16bpc_avx2 ()

**Comment by lu-zero** [comment]
It seems that's the problem. We need to check why the dispatcher picked the avx2 variant.

**Comment by lu-zero** [comment]
Great! thank you!
