### ISSUE TITLE
Feature Request: Scalable Video Coding for Frame Rate and Resolution

### ISSUE THREAD

**Issue by jnnks** [xiph/rav1e#2925]
My use-case for this library is ultra-low bandwidth streaming with no more than 20kbit/s throughput. We need every bit of quality that we can with that target bitrate and would like decide whether to drop frames or reduce the video quality.

There is a parameter `--frame-rate`. I understand the behavior, but the use-case is not quite clear to me.

I would therefore suggest an extension to the CLI API like `--allow-drops`. That would in combination with `--frame-rate` drop frames, until the passed value is met. Of course this works only if the frame rate is lower that the source video.

I saw a mechanism for frame drops, but I was not able to trigger it. It seems to be disabled.

So far I was using a short snippet here: https://github.com/xiph/rav1e/blob/1f48795da71693378b0d5a2aef940253726758e5/src/bin/rav1e.rs#L128

<details>
<summary>My Snippet</summary>

```rust        
        // also use --frame-rate 10, otherwise video will be too fast
        let fps_target = 10;
        let fps_now = video_info.time_base.den / video_info.time_base.num;
        let keep_every = if fps_now < fps_target { 1.0 }
                         else { fps_now as f32 / fps_target as f32 };
        let rem = self.count as f32 % keep_every;
        if (keep_every - rem) <= 1.0 {
          let _ = ctx.send_frame(Some(Arc::new(frame)));
        }
```

</details>

To drop frames from the input video. This works, but is not an optimal change. Since the frames are removed entirely they will not be used for anything clever that the encoder may be able to do with it. (I am not an expert on that topic)

What is your opinion on this?

_I should probably add that I am willing to make all necessary changes, but wanted to inquire first. Maybe there are concerns or unforeseen issues regarding the topic._

**Comment by ngcthuong** [comment]
frame-rate usually specifies the input frame rate of the input video (may be used) to control the target rate. So, if your capture video is 30fps, this frame-rate is 30. 

What you mentioned is temporal scalability. I believe AV1 does support this feature.

**Comment by jnnks** [comment]
At least the [wikipedia article](https://en.wikipedia.org/wiki/AV1#Scalable_video_coding) mentions scalability in both resolution and frame rate.
I left the topic untouched for a while, but I remember seeing a resolution scaling implementation somewhere in this repo.
Thanks for the clarification!

**Comment by ngcthuong** [comment]
Temporal scalibility is a kind of default feauture in the main profile, MPEG standard included. Spatial scalability is something require extension. It's what MPEG usually doing. Not sure it the same here, but certainly not the default one.

**Comment by jnnks** [comment]
I solved both features externally for now and will close this, as the issue is becoming stale anyway.
At some point this may become relevant again.
