### ISSUE TITLE
Assertion failed when encoding blank image at low quantizers

### ISSUE THREAD

**Issue by quietvoid** [xiph/rav1e#2985]
**Describe the bug**
```
thread 'main' panicked at 'assertion failed: `(left != right)`
  left: `0`,
 right: `0`', rav1e/src/encoder.rs:2243:3
```

**To Reproduce**
Version: `rav1e p20220802-15-g725c941 (Release)`
Sample input file: https://0x0.st/o2LY.y4m

Failing command line: `rav1e test.y4m --bitrate 1000 --min-quantizer 0 --output out.ivf`
Working: `rav1e test.y4m --bitrate 1000 --min-quantizer 50 --output out.ivf`

**Expected behavior**
The encode should not fail.
Version 0.4.1 also works.

**Required Information**
Version:
```
rav1e p20220802-15-g725c941 (Release)
```
Operating system:
```
Linux user 5.18.16-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 03 Aug 2022 11:25:04 +0000 x86_64 GNU/Linux
```

**Console Output**
Trace: [trace.txt](https://github.com/xiph/rav1e/files/9328742/trace.txt)

<Details>

> CPU Feature Level: AVX2
Using y4m decoder: 640x480p @ 24/1 fps, 4:2:0, 8-bit
Encoding settings: keyint_min=12 keyint_max=240 quantizer=255 bitrate=1000000 min_quantizer=0 low_latency=false tune=Psychovisual rdo_lookahead_frames=20 multiref=true fast_deblock=false scene_detection_mode=Standard cdef=true lrf=true enable_timing_info=false min_block_size=8x8 max_block_size=64x64 encode_bottomup=false non_square_partition_max_threshold=8x8 reduced_tx_set=true tx_domain_distortion=false tx_domain_rate=false rdo_tx_decision=false prediction_modes=Complex-KFs fine_directional_intra=true include_near_mvs=false use_satd_subpel=true

</Details>

**Comment by barrbrain** [comment]
Running git bisect with the reproduction identified #2933 as commit that introduced this assertion failure.
Curiously, it no longer reproduces after #2981. I will continue analysis to ensure the underlying issue is resolved.

**Comment by quietvoid** [comment]
Patch works for my sample. Thanks!
