### ISSUE TITLE
Early termination during a search for RDO based mode decision

### ISSUE THREAD

**Issue by ycho** [xiph/rav1e#299]
When doing a search for RDO based mode decision, if current rd_cost is already higher than current best, then stop searching for that mode. The mode is usually the partition split type, for ex if you want to compare the rd_cost of 8x8 and 4x4 partitions, then assume you have rd_cost for 8x8 computed. When computing rd_cost for each of four 4x4 partitions, if the sum of rd_cost for 4x4 is higher than current best rd_cost (i.e. that of 8x8), then stop computing rd_cost for remaining 4x4s.

**Comment by rzumer** [comment]
@ycho Is this now implemented in `rdo_partition_decision` via `early_exit` and `cached_block`?

**Comment by ycho** [comment]
@rzumer, yes this is implemented for both topdown (i.e. rdo_partition_decision()) and bottomup partition search. I forgot to close the opened issue for this.
