### ISSUE TITLE
 [feature request] Support RGB formats

### ISSUE THREAD

**Issue by CartoonFan** [xiph/rav1e#3035]
It would be great to have support for RGB pixel formats. ~Aomenc can already handle them, so this is also related to #2759.~

Thanks!

EDIT: It's actually ffmpeg's libaom-av1 that can do that, not aomenc proper.

**Comment by CartoonFan** [comment]
I didn't notice the blank issue template, so this probably isn't exactly a "bug". Sorry for the mix-up :sweat_smile:  :pray:

**Comment by tdaede** [comment]
This is already supported - all you need to do is use the "Identity" matrix coefficients.

We should probably add YCoCg-R though now, which is much preferred...
