### ISSUE TITLE
Segfault in rav1e_idct_8x16_internal_16bpc_sse4

### ISSUE THREAD

**Issue by atourem3** [xiph/rav1e#3066]
**Describe the bug**
Encoder crashes when trying to encode 10-bit video at --speed ≤ 1 on an Ivy Bridge Xeon E3-1245 v2.

**To Reproduce**
Run RAV1E_CPU_TARGET=SSE4.1 rav1e --speed 1 with 10-bit input.

**Expected behavior**
It should encode.

**Required Information**
Version:
```
$ rav1e --version
rav1e 0.6.0 (p20221123) (release)
rustc 1.65.0 (897e37553 2022-11-02) x86_64-unknown-linux-gnu
Compiled CPU Features: aes,avx,fxsr,pclmulqdq,popcnt,rdrand,sse,sse2,sse3,sse4.1,sse4.2,ssse3,xsave,xsaveopt
Assembly: Enabled
Threading: Enabled
Unstable Features: Disabled
Compiler Flags: -Ctarget-cpu=native
Built Thu, 24 Nov 2022 05:37:03 +0000
```
Operating system:
```
$ uname -a
Linux arch 6.0.8-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 10 Nov 2022 21:14:24 +0000 x86_64 GNU/Linux
```

**Console Output**
```
Thread 1 "rav1e" received signal SIGSEGV, Segmentation fault.
0x0000555555840432 in rav1e_idct_8x16_internal_16bpc_sse4 ()
```
<Details>
$ rust-gdb rav1e
GNU gdb (GDB) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from rav1e...
(gdb) r --speed 1 --output Netflix_FoodMarket_4096x2160_60fps_10bit_420.ivf Netflix_FoodMarket_4096x2160_60fps_10bit_420.y4m
Starting program: /usr/bin/rav1e --speed 1 --output Netflix_FoodMarket_4096x2160_60fps_10bit_420.ivf Netflix_FoodMarket_4096x2160_60fps_10bit_420.y4m
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
>  CPU Feature Level: SSE4_1
>  Using y4m decoder: 4096x2160p @ 60/1 fps, 4:2:0, 10-bit
>  Encoding settings: keyint_min=12 keyint_max=240 quantizer=100 bitrate=0 min_quantizer=0 low_latency=false tune=Psychovisual rdo_lookahead_frames=40 multiref=true fast_deblock=false scene_detection_mode=Standard cdef=true lrf=true enable_timing_info=false min_block_size=4x4 max_block_size=64x64 encode_bottomup=true non_square_partition_max_threshold=64x64 reduced_tx_set=false tx_domain_distortion=false tx_domain_rate=false rdo_tx_decision=true prediction_modes=Complex-All fine_directional_intra=true include_near_mvs=true use_satd_subpel=true
>  Using 1 tile
[New Thread 0x7fffe01086c0 (LWP 15330)]
[New Thread 0x7fffdff076c0 (LWP 15331)]
[New Thread 0x7fffdfd066c0 (LWP 15332)]
[New Thread 0x7fffdfb056c0 (LWP 15333)]
[New Thread 0x7fffdf9046c0 (LWP 15334)]
[New Thread 0x7fffdf7036c0 (LWP 15335)]
[New Thread 0x7fffdf5026c0 (LWP 15336)]
[New Thread 0x7fffdf3016c0 (LWP 15337)]

Thread 1 "rav1e" received signal SIGSEGV, Segmentation fault.
0x0000555555840432 in rav1e_idct_8x16_internal_16bpc_sse4 ()
</Details>

**Comment by lu-zero** [comment]
An import had another typo @barrbrain ? :/

**Comment by barrbrain** [comment]
I can reproduce the segfault at 984515f4eda3b3f22c9fc6d0525d8e3857cce5cb

**Comment by Gramner** [comment]
The underlying problem is that the function is being called with an invalid (out-of-range) `eob` value. The value should in the interval `[0,w*h-1]`, but it's being called with an `eob` value of 128 despite the maximum valid value for an 8x16 transform being 127.

As a result, the following loop will not terminate as 128 is being interpreted as a negative signed value. `r6` then ends up underflowing to 0xffffffff which causes a segfault when used as an offset to the `tbl_8x16_2d` table in `r5`.
```nasm
    mov                 r6d, 4
.zero_loop:
    dec                 r6d
    cmp                eobb, byte [r5+r6]
    jl .zero_loop
```

**Comment by barrbrain** [comment]
Noting that this issue can be quickly reproduced with the parent commit of #3067 and:
```sh
RAV1E_CPU_TARGET=SSE4.1 cargo test --lib --features=decode_test \
  test_encode_decode::high_bit_depth_10_aom
```

**Comment by tmatth** [comment]
> Noting that this issue can be quickly reproduced with the parent commit of #3067 and:
> 
> ```shell
> RAV1E_CPU_TARGET=SSE4.1 cargo test --lib --features=decode_test \
>   test_encode_decode::high_bit_depth_10_aom
> ```

Yeah also got it here on a Sandy Lake Xeon E3-1505M v6

**Comment by tmatth** [comment]
I'm not sure how involved the fix is but maybe a debug_assert would be a good place to start?

**Comment by tmatth** [comment]
> Noting that this issue can be quickly reproduced with the parent commit of #3067 and:
> 
> ```shell
> RAV1E_CPU_TARGET=SSE4.1 cargo test --lib --features=decode_test \
>   test_encode_decode::high_bit_depth_10_aom
> ```

FWIW I needed to append `-- --ignored` too.

**Comment by lu-zero** [comment]
Looks like there is an off by one in one range. setting an assert before calling that function and get the backtrace should be a quick way to find it.
