### ISSUE TITLE
dependabot is too sensitive and frequent

### ISSUE THREAD

**Issue by vibhoothi** [xiph/rav1e#3139]
At the moment it is too noisy with per-dependency change in a PR and it is creating weekly PRs for patch updates like bumping 0.0.1 to 0.0.2, which seems to be too sensitive with 4/5 PRs every week. 

Maybe we should,
+ Avoid minor bumps at the least,
+ Program in a way it creates one PR with squashed changes for all the deps updates since we do not want the git history to be filled with dep updates for an encoder project.  
+ Increase sensitivity.

Or we can ignore every other week and call it a feature too?

**Comment by lu-zero** [comment]
we can aggregate all of them once per week.

**Comment by shssoichiro** [comment]
Closed by #3153
