### ISSUE TITLE
Segfault when running cfl_rdo bench with BLOCK_8X8 (AVX2)

### ISSUE THREAD

**Issue by FreezyLemon** [xiph/rav1e#3175]
**Describe the bug**
When running the `cfl_rdo(BLOCK_8X8)` bench, I get the following output:

```
Running benches/bench.rs (target/release/deps/bench-2a88af624d4460eb)
Benchmarking cfl_rdo(BLOCK_8X8): Warming up for 3.0000 serror: bench failed, to rerun pass `--bench bench`

Caused by:
  process didn't exit successfully: `/home/user/Development/rav1e/target/release/deps/bench-2a88af624d4460eb BLOCK_8X8 --bench` (signal: 11, SIGSEGV: invalid memory reference)
```

The other block sizes run without a problem.

Running the benches with a debugger attached breaks on `rav1e_ipred_cfl_ac_420_16bpc_avx2`, what I think is [this line](https://github.com/xiph/rav1e/blob/0b4d0ed3191d75930f26a959996f1ab0971674ce/src/x86/ipred16_avx2.asm#L4442). Reducing the runtime CPU feature level (`RAV1E_CPU_TARGET`) to SSE4.1 or less "fixes" the error. I can't test the AVX512 version because my CPU doesn't support it.

**To Reproduce**
`cargo bench --features bench -- BLOCK_8X8`

**Required Information**
Toolchain:
```
$ cargo --version
cargo 1.68.1 (115f34552 2023-02-26)
$ rustc --version
rustc 1.68.1 (8460ca823 2023-03-20)
$ nasm --version
NASM version 2.16.01 compiled on Mar 18 2023
```
Version: git master

Operating system:
```
$ uname -a
Linux arch-pc 6.2.8-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Wed, 22 Mar 2023 22:52:38 +0000 x86_64 GNU/Linux
```

**Comment by barrbrain** [comment]
The new assembly in #3085 has stricter expectations of memory layout than the current benchmark design.
