### ISSUE TITLE
Implement CONFIG_KF_CTX

### ISSUE THREAD

**Issue by tdaede** [xiph/rav1e#320]

**Comment by tdaede** [comment]
We still compile with KF_CTX=0, if it works without that flag then we can open a PR to remove it.

**Comment by ycho** [comment]
Sure- if you check the ./aom_test/aom_config.h, the flag is already disappeared, which means it is turned on by default. I remember I had no option to enable level_map, so I wrote the code for it.

**Comment by ycho** [comment]
Confirmed this is already there.
