### ISSUE TITLE
Update rustc 

### ISSUE THREAD

**Issue by JaydenElliott** [xiph/rav1e#3256]
**Describe the bug**

I'm unable to update rav1e to latest (`0.6.6`) due to my clap dependency (`4.4.5`). 
I had a look and it looks like this [pipeline action](https://github.com/xiph/rav1e/actions/runs/6322606964/job/17168542136?pr=3249) and it failed due an outdated `rustc` version. 

Would it be possible to update this? If it's a simple change I can do it. Just [this](https://github.com/xiph/rav1e/blob/21bb4cb033208cd975f1c481501b3f4f9cb2ede2/build.rs#L236) / check for breaking changes?

**Comment by lu-zero** [comment]
Probably it is a good idea do bump the minimum version.
