### ISSUE TITLE
Read of uninitialized data

### ISSUE THREAD

**Issue by kornelski** [xiph/rav1e#3257]
https://github.com/xiph/rav1e/blob/21bb4cb033208cd975f1c481501b3f4f9cb2ede2/src/encoder.rs#L2246

https://github.com/xiph/rav1e/blob/21bb4cb033208cd975f1c481501b3f4f9cb2ede2/src/encoder.rs#L2288

This uses the unsafe and theoretically UB `Aligned::uninitialized()` (#1572) and passes it first for *reading* to `encode_tx_block`, and only later writes to it in `luma_ac`.

Besides the unsafety, this looks like a logic bug.

**Comment by lu-zero** [comment]
ac is used only when in CFL mode so it is populated before it is used, we can make it a bit more apparent.

**Comment by lu-zero** [comment]
Thank you for spotting it :)
