### ISSUE TITLE
Multiple-borrow PlaneSlice

### ISSUE THREAD

**Issue by tdaede** [xiph/rav1e#335]
We should make PlaneSlice have a pixel-row iterator and the like, then we can implement a multiple-borrow version of PlaneSlice for threading purposes.

**Comment by lu-zero** [comment]
[bytes](https://github.com/carllerche/bytes) has a the mt sharing logic we could probably reuse.

**Comment by lu-zero** [comment]
https://gist.github.com/lu-zero/8349e47b04b5af26a1d61d2455db541e here a prototype.

**Comment by tdaede** [comment]
This is fixed by @rom1v 's tiling work.
