### ISSUE TITLE
What WebAssembly targets should be supported?

### ISSUE THREAD

**Issue by FreezyLemon** [xiph/rav1e#3366]
Currently looking into WASM tests, and it's not clear what WebAssembly targets are actively supported. I think it's only `wasm32-unknown-unknown`, but I am not sure.

There are 2-3 main WASM targets I am aware of:
- `wasm32-unknown-unknown`
- (maybe) `wasm32-unknown-emscripten`
- `wasm32-wasi`

All of these have a maintenance burden of some sort, but I'd like to know what the goal is before starting to fix things.

**Comment by lu-zero** [comment]
wasi should work out of box w/out anything special. wasm32-unknown-unknown is the target that was worked on during the gsoc and the one that would be nice that keeps working even if it means some additional care.

**Comment by FreezyLemon** [comment]
Alright, that's all I wanted to know. Thanks
