### ISSUE TITLE
Fix or remove grcov-coverage CI job

### ISSUE THREAD

**Issue by shssoichiro** [xiph/rav1e#3394]
The CI job for code coverage has been broken for quite some time. It is allowed to fail, but still annoying to show as a red X on every PR. We should either fix the job or remove it.

Example: https://github.com/xiph/rav1e/actions/runs/10392532069/job/28780308261

**Comment by FreezyLemon** [comment]
Maybe exclude the `binary` tests from codecov? Seems like it's only those that are failing, and those don't contribute to coverage stats anyways, right?
