### ISSUE TITLE
Not currently compatible with reference streams from AV1 ver 1.0.0

### ISSUE THREAD

**Issue by Min1123** [xiph/rav1e#351]
**Current bitstream does not decode with reference decoder (aomdec) 
(enc_file.ivf is from the nyan.y4m test file)**

> 
aomdec -k -v -o out.y4m enc_file.ivf 
AOMedia Project AV1 Decoder 1.0.0-135-g000f2f686
Warning: Failed to decode frame 1: Corrupt frame detected
Warning: Failed to decode frame 2: Corrupt frame detected
Warning: Failed to decode frame 3: Corrupt frame detected
Warning: Failed to decode frame 4: Corrupt frame detected
Warning: Failed to decode frame 5: Corrupt frame detected
Warning: Failed to decode frame 6: Corrupt frame detected
Warning: Failed to decode frame 7: Corrupt frame detected
Warning: Failed to decode frame 8: Corrupt frame detected
Warning: Failed to decode frame 9: Corrupt frame detected
Warning: Failed to decode frame 10: Corrupt frame detected
Warning: Failed to decode frame 11: Corrupt frame detected
Warning: Failed to decode frame 12: Corrupt frame detected
Warning: Failed to decode frame 13: Corrupt frame detected
Warning: Failed to decode frame 14: Corrupt frame detected
Warning: Failed to decode frame 15: Corrupt frame detected
Warning: Failed to decode frame 16: Corrupt frame detected
Warning: Failed to decode frame 17: Corrupt frame detected
Warning: Failed to decode frame 18: Corrupt frame detected
Warning: Failed to decode frame 19: Corrupt frame detected
Warning: Failed to decode frame 20: Corrupt frame detected

**MKVMerge gives a bit more information that may be helpful.**

>
mkvmerge --engage enable_av1 -o out.mkv output.ivf 
mkvmerge v24.0.0 ('Beyond The Pale') 64-bit
'output.ivf': Using the demultiplexer for the format 'IVF (AV1, VP8, VP9)'.
'output.ivf' track 0: Using the output module for the format 'AV1'.
The file 'out.mkv' has been opened for writing.
terminate called after throwing an instance of 'mtx::av1::obu_without_size_unsupported_x'
  what():  Raw OBUs without a size field are not supported.
Aborted (core dumped)

**Comment by ycho** [comment]
Hi, this is expected behavior.
Since rav1e  generates bitstream that can be decodable  by an earlier than 1.0 version of aomdec yet.

**Comment by Min1123** [comment]
So this should work once the aom submodule is a 1.0.0 version or newer?

**Comment by ycho** [comment]
YES!

**Comment by tdaede** [comment]
If you want to help out or follow along, the issues tagged "conformance" are the ones that block us from updating to v1.0.0.

**Comment by rzumer** [comment]
Done as of #404.
