### ISSUE TITLE
libaom does not have SIMD code for IDTX and several other TXs for inv_txfm_add_4x4()

### ISSUE THREAD

**Issue by ycho** [xiph/rav1e#372]
So, when rav1e is built in SIMD mode, it need to add one more layer to check this as in libaom.
I think several other TXs are also affected.

Only detectable by libaom's assert in debug mode, but just passed in release mode.

The end function in libaom side is : av1_inv_txfm2d_add_4x4_sse4_1(), which does not have IDTX code.

av1_highbd_inv_txfm_add()
-->
av1_highbd_inv_txfm_add_4x4()  // In this function, C version is called for below TXs.
 case V_DCT:
    case H_DCT:
    case V_ADST:
    case H_ADST:
    case V_FLIPADST:
    case H_FLIPADST:
    case IDTX:
      av1_inv_txfm2d_add_4x4_c()

--> av1_inv_txfm2d_add_4x4_sse4_1() // For IDTX, assert fail after assert(0) met.

**Comment by lu-zero** [comment]
since 79b01bffb4a7fe6d84c4897616077cae02613eee we have already:
``` rust
fn iht4x4_add(
  input: &[i32], output: &mut [u16], stride: usize, tx_type: TxType
) {
  // SIMD code may assert for transform types beyond TxType::IDTX.
  if tx_type < TxType::IDTX {
    unsafe {
      av1_inv_txfm2d_add_4x4(
        input.as_ptr(),
        output.as_mut_ptr(),
        stride as libc::c_int,
        tx_type as libc::c_int,
        8
      );
    }
  } else {
    unsafe {
      av1_inv_txfm2d_add_4x4_c(
        input.as_ptr(),
        output.as_mut_ptr(),
        stride as libc::c_int,
        tx_type as libc::c_int,
        8
      );
    }
  }
}
```

**Comment by ycho** [comment]
False alarm, master already has the fix.
