### ISSUE TITLE
Move skip RDO inner loop than prediction RDO

### ISSUE THREAD

**Issue by ycho** [xiph/rav1e#373]
Otherwise, exactly the same prediction is done twice for skip and non-skip modes.
Best place  to compare skip/non-skip would be inside encode_block(), which will 
return the RDO decision for skip flag together with rd_cost.

**Comment by rzumer** [comment]
I'm not sure what this means, but as mentioned before, testing skip after making a decision for the prediction mode results in lower quality than not even testing skip at all, with current RD modelling.

**Comment by ycho** [comment]
I see, I will take care of this task.

**Comment by ycho** [comment]
New skip RDO #474 has landed, https://github.com/xiph/rav1e/commit/c2d7b6af3bb081b85dbde6adccab5522802390a9 and it works flawlessly.

**Comment by rzumer** [comment]
I assume this was fulfilled by #474, so closing.
