### ISSUE TITLE
--quantizer 0 encoded files fail to decode due to corrupt frames

### ISSUE THREAD

**Issue by mateon1** [xiph/rav1e#376]
```bash
$ target/release/rav1e --quantizer 0 test.y4m test.ivf
Frame 0 - Key frame

$ aom_test test.ivf -o test-dec.y4m
Warning: Failed to decode frame 1: Corrupt frame detected
```

The test.y4m file here contains one frame of size 256x256.

Tested on git commits 4f109775a2bca6fe71384150acfe8a7441fb0d90 and a978c221897d4cc5cd858f13043ccf48638a2609 (current master)

**Comment by tdaede** [comment]
Yeah, quantizer 0 is lossless mode, which needs a bunch of special support. #151 can track that, but before that we should just not accept quantizer 0.
