### ISSUE TITLE
Use msvc to build rav1e error.

### ISSUE THREAD

**Issue by tnti** [xiph/rav1e#383]
I installed pthreads-win32. Also installed unistd.h.
At the time of construction, the following error message is also prompted.
error: failed to run custom build command for `rav1e v0.1.0 (file:///E:/rav1e)`
process didn't exit successfully: `e:\rav1e\target\release\build\rav1e-b1a9cf9f57d90f10\build-script-build` (exit code: 101)
--- stderr
--- aom_configure: Detected CPU: x86_64
CMake Warning at build/cmake/util.cmake:47 (message):
  --- Enabled CONFIG_OBU_NO_IVF, required for CONFIG_SCALABILITY.
Call Stack (most recent call first):
  build/cmake/aom_experiment_deps.cmake:28 (change_config_and_warn)
  build/cmake/aom_configure.cmake:180 (fix_experiment_configs)
  CMakeLists.txt:67 (include)

Running C compiler test: inline_check_1
Running CXX compiler test: inline_check_1
Running C compiler test: pthread_check
Running CXX compiler test: pthread_check
Running C compiler test: unistd_check
Running CXX compiler test: unistd_check
Checking C compiler flag support for: /W3
Checking C++ compiler flag support for: /W3
Checking C compiler flag support for: /wd4996
Checking C++ compiler flag support for: /wd4996
thread 'main' panicked at '
command did not execute successfully, got: exit code: 1

build script failed, must exit now', C:\Users\TNTI\.cargo\registry\src\github.com-1ecc6299db9ec823\cmake-0.1.31\src\lib.rs:643:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

Error message in CMakeError.log.

Determining if the pthread_create exist failed with the following output:
Change Dir: E:/rav1e/target/release/build/rav1e-1d73d62b7fa6c386/out/build/CMakeFiles/CMakeTmp

Run Build Command: "D:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/MSBuild/15.0/Bin/MSBuild.exe" "cmTC_f56a1.vcxproj" "/p:Configuration=Debug" "/p:VisualStudioVersion =15.0"
Microsoft (R) build engine version 15.7.180.61344 for the .NET Framework

Copyright (C) Microsoft Corporation. all rights reserved.

The build start time is 2018/7/30 3:46:15.

The project "E:\rav1e\target\release\build\rav1e-1d73d62b7fa6c386\out\build\CMakeFiles\CMakeTmp\cmTC_f56a1.vcxproj" on node 1 (default target).

PrepareForBuild:

  The directory "cmTC_f56a1.dir\Debug\" is being created.

  The directory "E:\rav1e\target\release\build\rav1e-1d73d62b7fa6c386\out\build\CMakeFiles\CMakeTmp\Debug\" is being created.

  The directory "cmTC_f56a1.dir\Debug\cmTC_f56a1.tlog\" is being created.

InitializeBuildStatus:

  "cmTC_f56a1.dir\Debug\cmTC_f56a1.tlog\unsuccessfulbuild" is being created because "AlwaysCreate" has been specified.

ClCompile:

  D:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.14.26428\bin\HostX86\x64\CL.exe /c /Zi /nologo /W1 /WX- /diagnostics: Classic /Od /Ob0 /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_f56a1.dir \Debug\\" /Fd"cmTC_f56a1.dir\Debug\vc141.pdb" /Gd /TC /FC /errorReport:queue "E:\rav1e\target\release\build\rav1e-1d73d62b7fa6c386\out\build\CMakeFiles\ CMakeTmp\CheckSymbolExists.c"

  CheckSymbolExists.c

Link:

  D:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.14.26428\bin\HostX86\x64\link.exe /ERRORREPORT:QUEUE /OUT:"E:\rav1e\target \release\build\rav1e-1d73d62b7fa6c386\out\build\CMakeFiles\CMakeTmp\Debug\cmTC_f56a1.exe" /INCREMENTAL /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid. Lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"E:/rav1e/target/release/build/rav1e-1d73d62b7fa6c386/out /build/CMakeFiles/CMakeTmp/Debug/cmTC_f56a1.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"E:/rav1e/target/release/build/rav1e-1d73d62b7fa6c386/out/build/CMakeFiles/ CMakeTmp/Debug/cmTC_f56a1.lib" /MACHINE:X64 /machine:x64 cmTC_f56a1.dir\Debug\CheckSymbolExists.obj

CheckSymbolExists.obj : error LNK2019: Unresolved external symbol __imp_pthread_create, which is referenced in function main[E:\rav1e\target\release\build\rav1e-1d73d62b7fa6c386\out\build\CMakeFiles\CMakeTmp\cmTC_f56a1.vcxproj ]

E:\rav1e\target\release\build\rav1e-1d73d62b7fa6c386\out\build\CMakeFiles\CMakeTmp\Debug\cmTC_f56a1.exe : fatal error LNK1120: 1 unresolvable external command [E:\rav1e\target\release\ Build\rav1e-1d73d62b7fa6c386\out\build\CMakeFiles\CMakeTmp\cmTC_f56a1.vcxproj]

The operation of generating the project "E:\rav1e\target\release\build\rav1e-1d73d62b7fa6c386\out\build\CMakeFiles\CMakeTmp\cmTC_f56a1.vcxproj" (default target) has been completed - failed.

The build failed.

"E:\rav1e\target\release\build\rav1e-1d73d62b7fa6c386\out\build\CMakeFiles\CMakeTmp\cmTC_f56a1.vcxproj" (default target) (1) ->

(Link target) ->

  CheckSymbolExists.obj : error LNK2019: Unresolved external symbol __imp_pthread_create, which is referenced in function main[E:\rav1e\target\release\build\rav1e-1d73d62b7fa6c386\out\build\CMakeFiles\CMakeTmp\cmTC_f56a1.vcxproj ]

  E:\rav1e\target\release\build\rav1e-1d73d62b7fa6c386\out\build\CMakeFiles\CMakeTmp\Debug\cmTC_f56a1.exe : fatal error LNK1120: 1 unresolvable external command [E:\rav1e\target\release\ Build\rav1e-1d73d62b7fa6c386\out\build\CMakeFiles\CMakeTmp\cmTC_f56a1.vcxproj]

    0 warnings

    2 errors

Elapsed time 00:00:01.00

File E:/rav1e/target/release/build/rav1e-1d73d62b7fa6c386/out/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <pthread.h>

Int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  Return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  Return 0;
#endif
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: E:/rav1e/target/release/build/rav1e-1d73d62b7fa6c386/out/build/CMakeFiles/CMakeTmp

Run Build Command: "D:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/MSBuild/15.0/Bin/MSBuild.exe" "cmTC_d33f1.vcxproj" "/p:Configuration=Debug" "/p:VisualStudioVersion =15.0"
Microsoft (R) build engine version 15.7.180.61344 for the .NET Framework

Copyright (C) Microsoft Corporation. all rights reserved.

The build start time is 2018/7/30 3:46:16.

The project "E:\rav1e\target\release\build\rav1e-1d73d62b7fa6c386\out\build\CMakeFiles\CMakeTmp\cmTC_d33f1.vcxproj" on node 1 (default target).

PrepareForBuild:

  The directory "cmTC_d33f1.dir\Debug\" is being created.

  The directory "E:\rav1e\target\release\build\rav1e-1d73d62b7fa6c386\out\build\CMakeFiles\CMakeTmp\Debug\" is being created.

  The directory "cmTC_d33f1.dir\Debug\cmTC_d33f1.tlog\" is being created.

InitializeBuildStatus:

  "cmTC_d33f1.dir\Debug\cmTC_d33f1.tlog\unsuccessfulbuild" is being created because "AlwaysCreate" has been specified.

ClCompile:

  D:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.14.26428\bin\HostX86\x64\CL.exe /c /Zi /nologo /W1 /WX- /diagnostics: Classic /Od /Ob0 /D CHECK_FUNCTION_EXISTS=pthread_create /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline / Fo"cmTC_d33f1.dir\Debug\\" /Fd"cmTC_d33f1.dir\Debug\vc141.pdb" /Gd /TC /FC /errorReport:queue "D:\Program Files\CMake\share\cmake-3.12\Modules\ CheckFunctionExists.c"

  CheckFunctionExists.c

Link:

  D:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.14.26428\bin\HostX86\x64\link.exe /ERRORREPORT:QUEUE /OUT:"E:\rav1e\target \release\build\rav1e-1d73d62b7fa6c386\out\build\CMakeFiles\CMakeTmp\Debug\cmTC_d33f1.exe" /INCREMENTAL /NOLOGO pthreads.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32. Lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"E:/rav1e/target/release/build/rav1e- 1d73d62b7fa6c386/out/build/CMakeFiles/CMakeTmp/Debug/cmTC_d33f1.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"E:/rav1e/target/release/build/rav1e-1d73d62b7fa6c386/out/build /CMakeFiles/CMakeTmp/Debug/cmTC_d33f1.lib" /MACHINE:X64 /machine:x64 cmTC_d33f1.dir\Debug\CheckFunctionExists.obj

LINK : fatal error LNK1104: Unable to open file "pthreads.lib" [E:\rav1e\target\release\build\rav1e-1d73d62b7fa6c386\out\build\CMakeFiles\CMakeTmp\cmTC_d33f1.vcxproj]

The operation of generating the project "E:\rav1e\target\release\build\rav1e-1d73d62b7fa6c386\out\build\CMakeFiles\CMakeTmp\cmTC_d33f1.vcxproj" (default target) has been completed - failed.

The build failed.

"E:\rav1e\target\release\build\rav1e-1d73d62b7fa6c386\out\build\CMakeFiles\CMakeTmp\cmTC_d33f1.vcxproj" (default target) (1) ->

(Link target) ->

  LINK : fatal error LNK1104: Unable to open file "pthreads.lib" [E:\rav1e\target\release\build\rav1e-1d73d62b7fa6c386\out\build\CMakeFiles\CMakeTmp\cmTC_d33f1.vcxproj]

    0 warnings

    1 error

Elapsed time 00:00:00.80

Determining if the function pthread_create exists in the pthread failed with the following output:
Change Dir: E:/rav1e/target/release/build/rav1e-1d73d62b7fa6c386/out/build/CMakeFiles/CMakeTmp

Run Build Command: "D:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/MSBuild/15.0/Bin/MSBuild.exe" "cmTC_c89d8.vcxproj" "/p:Configuration=Debug" "/p:VisualStudioVersion =15.0"
Microsoft (R) build engine version 15.7.180.61344 for the .NET Framework

Copyright (C) Microsoft Corporation. all rights reserved.

The build start time is 2018/7/30 3:46:17.

The project "E:\rav1e\target\release\build\rav1e-1d73d62b7fa6c386\out\build\CMakeFiles\CMakeTmp\cmTC_c89d8.vcxproj" on node 1 (default target).

PrepareForBuild:

  The directory "cmTC_c89d8.dir\Debug\" is being created.

  The directory "E:\rav1e\target\release\build\rav1e-1d73d62b7fa6c386\out\build\CMakeFiles\CMakeTmp\Debug\" is being created.

  The directory "cmTC_c89d8.dir\Debug\cmTC_c89d8.tlog\" is being created.

InitializeBuildStatus:

  "cmTC_c89d8.dir\Debug\cmTC_c89d8.tlog\unsuccessfulbuild" is being created because "AlwaysCreate" has been specified.

ClCompile:

  D:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.14.26428\bin\HostX86\x64\CL.exe /c /Zi /nologo /W1 /WX- /diagnostics: Classic /Od /Ob0 /D CHECK_FUNCTION_EXISTS=pthread_create /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline / Fo"cmTC_c89d8.dir\Debug\\" /Fd"cmTC_c89d8.dir\Debug\vc141.pdb" /Gd /TC /FC /errorReport:queue "D:\Program Files\CMake\share\cmake-3.12\Modules\ CheckFunctionExists.c"

  CheckFunctionExists.c

Link:

  D:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.14.26428\bin\HostX86\x64\link.exe /ERRORREPORT:QUEUE /OUT:"E:\rav1e\target \release\build\rav1e-1d73d62b7fa6c386\out\build\CMakeFiles\CMakeTmp\Debug\cmTC_c89d8.exe" /INCREMENTAL /NOLOGO pthread.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32. Lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"E:/rav1e/target/release/build/rav1e- 1d73d62b7fa6c386/out/build/CMakeFiles/CMakeTmp/Debug/cmTC_c89d8.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"E:/rav1e/target/release/build/rav1e-1d73d62b7fa6c386/out/build /CMakeFiles/CMakeTmp/Debug/cmTC_c89d8.lib" /MACHINE:X64 /machine:x64 cmTC_c89d8.dir\Debug\CheckFunctionExists.obj

LINK : fatal error LNK1104: Unable to open file "pthread.lib" [E:\rav1e\target\release\build\rav1e-1d73d62b7fa6c386\out\build\CMakeFiles\CMakeTmp\cmTC_c89d8.vcxproj]

The operation of generating the project "E:\rav1e\target\release\build\rav1e-1d73d62b7fa6c386\out\build\CMakeFiles\CMakeTmp\cmTC_c89d8.vcxproj" (default target) has been completed - failed.

The build failed.

"E:\rav1e\target\release\build\rav1e-1d73d62b7fa6c386\out\build\CMakeFiles\CMakeTmp\cmTC_c89d8.vcxproj" (default target) (1) ->

(Link target) ->

  LINK : fatal error LNK1104: Unable to open file "pthread.lib" [E:\rav1e\target\release\build\rav1e-1d73d62b7fa6c386\out\build\CMakeFiles\CMakeTmp\cmTC_c89d8.vcxproj]

    0 warnings

    1 error

Elapsed time 00:00:00.85

Determining if compiler accepts -pthread failed with the following output:
Change Dir: E:/rav1e/target/release/build/rav1e-1d73d62b7fa6c386/out/build/CMakeFiles/CMakeTmp

Run Build Command: "D:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/MSBuild/15.0/Bin/MSBuild.exe" "cmTC_30f6b.vcxproj" "/p:Configuration=Debug" "/p:VisualStudioVersion =15.0"
Microsoft (R) build engine version 15.7.180.61344 for the .NET Framework

Copyright (C) Microsoft Corporation. all rights reserved.

The build start time is 2018/7/30 3:46:18.

The project "E:\rav1e\target\release\build\rav1e-1d73d62b7fa6c386\out\build\CMakeFiles\CMakeTmp\cmTC_30f6b.vcxproj" on node 1 (default target).

PrepareForBuild:

  The directory "cmTC_30f6b.dir\Debug\" is being created.

  The directory "E:\rav1e\target\release\build\rav1e-1d73d62b7fa6c386\out\build\CMakeFiles\CMakeTmp\Debug\" is being created.

  The directory "cmTC_30f6b.dir\Debug\cmTC_30f6b.tlog\" is being created.

InitializeBuildStatus:

  "cmTC_30f6b.dir\Debug\cmTC_30f6b.tlog\unsuccessfulbuild" is being created because "AlwaysCreate" has been specified.

ClCompile:

  D:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.14.26428\bin\HostX86\x64\CL.exe /c /Zi /nologo /W1 /WX- /diagnostics: Classic /Od /Ob0 /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_30f6b.dir \Debug\\" /Fd"cmTC_30f6b.dir\Debug\vc141.pdb" /Gd /TC /FC /errorReport:queue "D:\Program Files\CMake\share\cmake-3.12\Modules\CheckForPthreads.c"

  CheckForPthreads.c

Link:

  D:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.14.26428\bin\HostX86\x64\link.exe /ERRORREPORT:QUEUE /OUT:"E:\rav1e\target \release\build\rav1e-1d73d62b7fa6c386\out\build\CMakeFiles\CMakeTmp\Debug\cmTC_30f6b.exe" /INCREMENTAL /NOLOGO "-pthread" kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32 .lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"E:/rav1e/target/release/build/rav1e -1d73d62b7fa6c386/out/build/CMakeFiles/CMakeTmp/Debug/cmTC_30f6b.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"E:/rav1e/target/release/build/rav1e-1d73d62b7fa6c386/out/ Build/CMakeFiles/CMakeTmp/Debug/cmTC_30f6b.lib" /MACHINE:X64 /machine:x64 cmTC_30f6b.dir\Debug\CheckForPthreads.obj

LINK : warning LNK4044: Unrecognized option "/pthread"; ignored [E:\rav1e\target\release\build\rav1e-1d73d62b7fa6c386\out\build\CMakeFiles\CMakeTmp\cmTC_30f6b.vcxproj]

CheckForPthreads.obj : error LNK2019: Unresolved external symbol __imp_pthread_create, which is referenced in function main[E:\rav1e\target\release\build\rav1e-1d73d62b7fa6c386\out\build\CMakeFiles\CMakeTmp\cmTC_30f6b.vcxproj ]

CheckForPthreads.obj : error LNK2019: Unresolved external symbol __imp_pthread_join, which is referenced in function main[E:\rav1e\target\release\build\rav1e-1d73d62b7fa6c386\out\build\CMakeFiles\CMakeTmp\cmTC_30f6b.vcxproj ]

E:\rav1e\target\release\build\rav1e-1d73d62b7fa6c386\out\build\CMakeFiles\CMakeTmp\Debug\cmTC_30f6b.exe : fatal error LNK1120: 2 external commands that cannot be resolved [E:\rav1e\target\release\ Build\rav1e-1d73d62b7fa6c386\out\build\CMakeFiles\CMakeTmp\cmTC_30f6b.vcxproj]

The operation of generating the project "E:\rav1e\target\release\build\rav1e-1d73d62b7fa6c386\out\build\CMakeFiles\CMakeTmp\cmTC_30f6b.vcxproj" (default target) has been completed - failed.

The build failed.

"E:\rav1e\target\release\build\rav1e-1d73d62b7fa6c386\out\build\CMakeFiles\CMakeTmp\cmTC_30f6b.vcxproj" (default target) (1) ->

(Link target) ->

  LINK : warning LNK4044: Unrecognized option "/pthread"; ignored [E:\rav1e\target\release\build\rav1e-1d73d62b7fa6c386\out\build\CMakeFiles\CMakeTmp\cmTC_30f6b.vcxproj]

"E:\rav1e\target\release\build\rav1e-1d73d62b7fa6c386\out\build\CMakeFiles\CMakeTmp\cmTC_30f6b.vcxproj" (default target) (1) ->

(Link target) ->

  CheckForPthreads.obj : error LNK2019: Unresolved external symbol __imp_pthread_create, which is referenced in function main[E:\rav1e\target\release\build\rav1e-1d73d62b7fa6c386\out\build\CMakeFiles\CMakeTmp\cmTC_30f6b.vcxproj ]

  CheckForPthreads.obj : error LNK2019: Unresolved external symbol __imp_pthread_join, which is referenced in function main[E:\rav1e\target\release\build\rav1e-1d73d62b7fa6c386\out\build\CMakeFiles\CMakeTmp\cmTC_30f6b.vcxproj ]

  E:\rav1e\target\release\build\rav1e-1d73d62b7fa6c386\out\build\CMakeFiles\CMakeTmp\Debug\cmTC_30f6b.exe : fatal error LNK1120: 2 external commands that cannot be resolved [E:\rav1e\target\release\ Build\rav1e-1d73d62b7fa6c386\out\build\CMakeFiles\CMakeTmp\cmTC_30f6b.vcxproj]

    1 warning

    3 errors

Elapsed time 00:00:01.12

how to solve this problem?
thank.

**Comment by tnti** [comment]
Maybe we need to rewrite the cmake file in aom.
Add support link pthreadVC2.lib to solve this problem?

**Comment by tnti** [comment]
I am just to satisfy my curiosity.
The result is a failure.
Using gun mode, I have successfully built it.
Thanks to lu-zero.
I should start using rav1e happily.

**Comment by lu-zero** [comment]
Ideally those issues would happen on a normal libaom build.

We plan to avoid relying on libaom in the future, so all of this won't be necessary though :)

**Comment by tdaede** [comment]
If you want to try again, we just landed msvc support, so you should be able to do a native Windows build if you like.

**Comment by tnti** [comment]
There is an error in the latest libaim that will cause the build to fail.
36>e:\rav1e\aom_build\aom\apps\aomdec.c(653): error C2065: "STDOUT_FILENO": Undeclared identifier
You may need to notify Google, and modify the libaom rav1e.

**Comment by rzumer** [comment]
Please make sure that you are running the latest version of CMake and the submodule version of libaom initialized via `git submodule update --init` for the current master version. Then run `cargo build --release --bin rav1e`.

**Comment by tnti** [comment]
I also have the same error in using the official google libaom.
It can be seen that this is not an error generated by rav1e.

**Comment by tnti** [comment]
https://bugs.chromium.org/p/aomedia/issues/detail?id=2088
A question has been submitted.
Waiting for Google's reply.

**Comment by tnti** [comment]
After removing the extra unistd.h everything is normal
