### ISSUE TITLE
Convert to the bench built-in once it is ready

### ISSUE THREAD

**Issue by lu-zero** [xiph/rav1e#398]
Tracking issue: https://github.com/rust-lang/rust/issues/29553

**Comment by lu-zero** [comment]
Related issue https://github.com/rust-lang/rust/issues/50297

**Comment by djrenren** [comment]
Heads up, the most likely case is that following https://github.com/rust-lang/rust/issues/50297 bench will be made an external crate that consumes those  APIs (shouldn't really change the heart of this issue though)

**Comment by lu-zero** [comment]
Hopefully the change would be still minimal :)

**Comment by lu-zero** [comment]
I opened https://github.com/xiph/rav1e/pull/507 as an alternative path. Criterion offers quite a number of good features out of box and seems a good fit since we plan to give a try at native SIMD now that at least some of it is available on stable rust.

**Comment by rzumer** [comment]
Closing this issue since the alternative solution was merged.
