### ISSUE TITLE
Simple User API

### ISSUE THREAD

**Issue by lu-zero** [xiph/rav1e#410]
## Status
API:
- [x] `Config` struct with all the configuration items
  - [ ] `FromStr` to parse a x264-like string
  - [ ] `Display` to produce a x264-like string
  - [x] `parse_option(o: &str)` to update the configuration using a x264-like `key:value` string
  - [x] `new_context() -> Context` 
- [x] `Context`: opaque struct embedding the existing FrameInvariants, Sequence
  - [x] `new_frame() -> Arc<Frame>`
  - [x] `receive_obu_header() -> Vec<u8>`
  - [x] `send_frame(frame: Arc<Frame>)`/`receive_packet() -> Packet`
  - [ ] flush support
- [ ] Packet
  - [x] data buffer
  - [ ] user private data
  - [ ] timestamp

Usage:
- [x] Used in the `cli` tools
- [x] Used in the `decode_tests`

### Single Context
- Hide from the user the number of contexts we use, per-frame, per-sequence, etc.
#### In the future
- Shuffle the fields so FrameInvariants isn't so big
- Consider making the `Config` follow the builder pattern.

### Frame allocator
- Give the user a simple way to have the `Frame`
#### In the future
- Consider using a pool of frames 
- Add mean to have a custom allocation option

### Send/Receive/Flush model
- Split the encoding process from taking in/taking out the frames
- Have a clear way to signal we want to complete the current sequence with an explicit function
- Multithread-friendly
#### In the future
- Consider adding an optional `Future`-based API on top of this.

``` rust
// TODO: use the num crate?
#[derive(Clone, Copy, Debug)]
struct Ratio {
    pub num: usize,
    pub den: usize,
}

/// Here we store all the information we might receive from the cli
#[derive(Clone, Copy, Debug)]
struct Config {
    pub width: usize,
    pub height: usize,
    pub timebase: Ratio
    pub enc: EncoderConfig,
}

#[derive(Clone, Copy, Debug)]
struct Context {
    fi: FrameInvariants,
    seq: Sequence,
    timebase: Ratio,
    frame_q: VecDeque<Frame>,
    packet_q: VecDeque<Packet>
}

#[derive(Clone, Copy, Debug)]
enum EncoderStatus {
    /// The encoder needs more Frames to produce an output Packet
    NeedMoreData,
    /// There are enough Frames queue
    EnoughData,
    /// 
    Failure,
}

impl Context {
    pub fn from_config(cfg: Config) -> Self {
        let Config { width, height, timebase, enc } = cfg;
        let fi = FrameInvariants::new(width, height, enc);
        let seq = Sequence::new(width, height);

        Context { fi, seq, timebase }
    }

    pub fn get_config(&self) -> Config {
    
    }

    pub fn new_frame(&self) -> Frame {
        Frame::new(self.fi.padded_w, self.fi.padded_h)
    }

    pub fn send_frame(&mut self, frame: Arc<Frame>) -> Result<(), EncoderStatus> {
        
    }

    pub fn receive_frame(&mut self) -> Result<Packet, EncoderStatus> {
    
    }

    pub fn flush(&mut self) {
    
    }
}
```

**Comment by lu-zero** [comment]
Since @atomnuker has a strong opinion regarding having a separate `flush()` function, here how it looks the other way:

``` rust
pub fn send_frame(&mut self, frame: F) 
  where F: Into<Option<Arc<Frame>>>) -> Result<(), EncoderStatus> {
  // ... 
  self.q.push_back(frame.into());
  // ...
}
```
You can pass either `None` or `Arc<Frame>`.

Usage example in the [playground](https://play.rust-lang.org/?gist=4dd9d85b893943c4202f3d47de6d2fa6&version=stable&mode=debug&edition=2015)

**Comment by lu-zero** [comment]
**Watercooler feedback**: do not make the libaom mistakes, muxing information should be available
  - [Keyframe Dependent Recovery Point](https://bugs.chromium.org/p/aomedia/issues/detail?id=2084)
  - [Switch frame signaling](https://bugs.chromium.org/p/aomedia/issues/detail?id=2085)
  - [Multiframe TU](https://bugs.chromium.org/p/aomedia/issues/detail?id=2086)
  - [OBU Header support](https://bugs.chromium.org/p/aomedia/issues/detail?id=2087)

TODO:
- [ ] Make sure the most common information is in `Packet` structure
- [ ] Add a function to craft the OBU Header

**Comment by lu-zero** [comment]
@robUx4 would you expand what you'd like to have from the encoder here regarding [this issue](https://github.com/AOMediaCodec/av1-isobmff/issues/101#issuecomment-420942417) ?

**Comment by robUx4** [comment]
An encoder should provide the structure in the CodecPrivate https://github.com/Matroska-Org/matroska-specification/blob/master/codec/av1.md#codecprivate-1
And to do so it would also need to provide the `initial_presentation_delay_minus_one` if `initial_presentation_delay_present` is set. But that seems tricky.

**Comment by lu-zero** [comment]
The api landed last august, this issues can be closed (and we can discuss later if we want to extend the API)
