### ISSUE TITLE
Swap forward transforms with the Daala ones.

### ISSUE THREAD

**Issue by tdaede** [xiph/rav1e#417]

**Comment by ycho** [comment]
This seems interesting idea.
At first, I thought it would not work, but it will work. So far, the video codec standard only states about inverse tx steps.
Then, can you further describe what would be benefits with this? Like smaller sizecode for fwd tx functions?

**Comment by lu-zero** [comment]
IIRC those transforms are faster and more compact, I guess we could add a set of benchmarks around it so we have some numbers.

**Comment by ycho** [comment]
We also have a brand-new full suite of SIMD code for daala txs, right?

**Comment by tdaede** [comment]
This is done.
