### ISSUE TITLE
show_existing_frame does not work

### ISSUE THREAD

**Issue by ycho** [xiph/rav1e#423]
Most likely bcz of not using frame and frame_header OBUs differently.
As I know, for show_existing_frame, encoder need to signal FRAME_HEADER OBU only.

**Comment by rzumer** [comment]
Going through the specification I could not find any mistake in our implementation. Unless I missed something there it might be easier to compare with `libaom`'s implementation, but it is too complex for me to commit to that right now.

**Comment by ycho** [comment]
As I stated above, I think the likely reason is, our code does not signal OBU_FRAME_HEADER only, which I know is required for show_existing_frame, since show_existing_frame should not encode actual tile data. Currently, our code always signal obu frame header + frame data(i.e. tile group).

**Comment by rzumer** [comment]
Fixed by #629.
