### ISSUE TITLE
Add partition splitting to RDO

### ISSUE THREAD

**Issue by tmatth** [xiph/rav1e#44]
Currently in `encode_tile` for every superblock, we search for the intra mode with the best RD (based on a 64x64 SSE), for PARTITION_NONE. We should extend this search to one-level of split.

**Comment by tmatth** [comment]
e.g., find the best combination of intra modes for the partitioned blocks and compare that to the PARTITION_NONE case, and pick the winner.

**Comment by tmatth** [comment]
Reference: http://av1-spec.argondesign.com/av1-spec/av1-spec.html#decode-partition-syntax

**Comment by negge** [comment]
The reference link has changed: http://av1-spec.argondesign.com/av1-spec/av1-spec.html#decode-partition-semantics

**Comment by rzumer** [comment]
This is mostly done as of #255. There is still no RDO decision made on frame edges, and not all partition types are supported, but these issues are covered by #226, #227, #258, and #175.
