### ISSUE TITLE
CDEF causing desyncs at high bit depth

### ISSUE THREAD

**Issue by rzumer** [xiph/rav1e#458]
The `high_bd()` decode test reveals that enabling CDEF causes desynchronization between the reconstruction and the decoder output at high bit depths following recent changes committed around August 9 or 10. These should be resolved, and `enable_cdef` set to true for all bit depths in the sequence header.

**Comment by xiphmont** [comment]
Thanks for filing the issue, I'm on it.

**Comment by xiphmont** [comment]
Fixed by PR #459
