### ISSUE TITLE
Windows build produces undecodable frames

### ISSUE THREAD

**Issue by gnafuthegreat** [xiph/rav1e#471]
Encoded this:

https://media.xiph.org/video/derf/y4m/sintel_trailer_2k_720p24.y4m

Using this build:

https://ci.appveyor.com/project/tdaede/rav1e/build/1.0.11/artifacts

The resulting file (https://themayhaks.com/~gideon/sintel-rav1e-80-4.ivf, ~15MB) appears to not be decodable by libaom.  It looks like it's at the 25th frame ("Warning: Failed to decode frame 25: Corrupt frame detected").  This was with 'rav1e.exe sintel_trailer_2k_720p24.y4m --output sintel-rav1e-80-4.ivf --quantizer 80 --speed 4'.

**Comment by gnafuthegreat** [comment]
Quick update: this does not appear to happen with rav1e b5b787a or 6c76fbd (just two commits I had built) on Linux, or at least not at frame 25 (both encodes are still going, but at least what has been encoded so far has been decodable).

**Comment by tdaede** [comment]
Can you try on this one, which is the first version that Appveyor landed in master?

https://ci.appveyor.com/api/buildjobs/trgstfyiklsdyn4n/artifacts/target%2Frelease%2Frav1e.exe

I expect it to still be broken, but hey.

**Comment by tdaede** [comment]
It would also be useful to know if this replicates at other speed levels. You can limit to 25 frames with --limit.

**Comment by gnafuthegreat** [comment]
I did a quick encode with "--limit 30" using the new build, and it seems to decode fine.  I'm running another without --limit just in case that makes a difference.

**Comment by gnafuthegreat** [comment]
Seems fine now.  Unless you want to dig into the original file to see what happened, I guess we can close this :-).  Thanks!

**Comment by tdaede** [comment]
OK. If you see it happen again, make sure to report it!
