### ISSUE TITLE
Implement rav1eenc.c for libavcodec

### ISSUE THREAD

**Issue by Kagami** [xiph/rav1e#472]
This issue rather belongs to ffmpeg's bugtracker but I suppose it would be useful to have tracking issue here as well.

Right now ffmpeg supports encoding to AV1 only via libaom. Would be nice to add encoding support via rav1e as well.

**Comment by lu-zero** [comment]
A C API is in the work, it depends on #410 and wouldn't be limited to libavcodec. :)

**Comment by tdaede** [comment]
This is especially useful because ivf to mp4 muxing in ffmpeg doesn't currently work due to the lack of an av1 parser.

**Comment by kodabb** [comment]
this is on my todo plate for march

**Comment by farindk** [comment]
+1 from me.
I started an AV1 plugin for libheif in order to support AVIF images (https://github.com/strukturag/libheif).
Since libaom is way too slow, I would like to use rav1e instead, but I depend on a C API for that.

**Comment by lu-zero** [comment]
The C API [exists](https://github.com/lu-zero/crav1e), you are welcome to use it and provide feedback :)

**Comment by farindk** [comment]
Thanks for the link. I will have a look.

Offtopic question: is there support for encoding with `still_picture` and `reduced_still_picture_header` set in the sequence header?

**Comment by tdaede** [comment]
We're missing an API call to set it. When that's added, still_picture should work. There's also some support for reduced_still_picture_header but it's never been tested so we may need to fix a few bugs.

**Comment by farindk** [comment]
Sounds good. As soon as I find some time, I'll try to integrate rav1e to libheif.

**Comment by dwbuiten** [comment]
WIP: https://github.com/dwbuiten/FFmpeg/tree/rav1e

**Comment by xuguangxin** [comment]
@dwbuiten , any update on this? I want to use ffmpeg+rav1e to do some RD curve comparison. Is your patch ready for target bitrate setting?
thanks

**Comment by lu-zero** [comment]
@xuguangxin what do you have in mind?

**Comment by dwbuiten** [comment]
@xuguangxin It's a few extra lines of code to update the patch to properly map bitrate options from FFmpeg to rav1e.

However, rav1e's bitrate mode is a WIP. I am, in fact, working on updating some of the empiracally derived values in the bitrate RC code to work properly with AV1 (one of tons of low hanging fruit for rav1e).

If you *really* want to test it within FFmpeg, you can apply the patch as-is and build; it will work fine, but you have to specify stuff like bitrate via `-rav1e-params quantizer=<maxqaunt>:bitrate=<bps>`.

**Comment by xuguangxin** [comment]
@lu-zero ,  just want to draw some RD curve for all AV1 encoders and compare it with x264 and x265. But current rav1e's ivf muxer did not write bitrate information to headers.

@dwbuiten. I had use some workaround to get the bitrate. I used ffmpeg remux the ivf to mp4. ffmpeg will calc the bitrate for me. 
I got the basic RD curve now. As you said, seems it still WIP.

Also, I want to double confirm you with params. To make sure I did not make a mistake. 
Here is command for one pass abr:


encoder | params
--------- | -------
x264|ffmpeg -i $INPUT  -c:v libx264 -tune psnr -b:v $RATE -bufsize 2*$RATE -vframes 600 $OUTPUT
x264|ffmpeg -i $INPUT  -c:v libx265 -tune psnr -b:v $RATE -bufsize 2*$RATE -vframes 600 $OUTPUT
libaom |ffmpeg -i $INPUT  -c:v libaom-av1 -b:v $RATE -bufsize 2*$RATE -vframes 600 $OUTPUT
rav1e| rav1e --tune Psnr -b $RATE $INPUT -o $OUTPUT

thanks for help

**Comment by Kagami** [comment]
Offtopic, but can't you get bitrate just by diving file size to the number of seconds in resulting video which should be known in your case?

**Comment by xuguangxin** [comment]
Sorry for off topic :). int his case, I need query fps and frame count from ivf. Then to the calc by my self. But ffmpeg can help me do this :). 
Just need one line, "ffmpeg -i out.ivf -c:v copy out.mp4 && ffprobe -v error -select_streams v:0 -show_entries stream=bit_rate -of default=noprint_wrappers=1 out.mp4"

**Comment by dwbuiten** [comment]
This is done an upstreamed.

**Comment by peters** [comment]
https://github.com/FFmpeg/FFmpeg/commit/d8bf24459b694338de4ceb2a2e6d4d2949d6658d
