### ISSUE TITLE
The build system should check whether `pkg-config` is installed

### ISSUE THREAD

**Issue by Yoric** [xiph/rav1e#494]
I had a few difficulties building rav1e, which showed up as `$git_desc` being undefined in some Perl script. Turns out I had forgotten to install `pkg-config`.

It would be a bit nicer if the configure step could check that.

**Comment by Yoric** [comment]
I'm on macOS, I just ran 

1. `git clone ...`
2. `git submodule update --init`
3. `cargo build`

Here's the output:
[backtrace.log](https://github.com/xiph/rav1e/files/2314215/backtrace.log)

Installing `pkg-config` with homebrew seems to have fixed the issue.

**Comment by lu-zero** [comment]
On readme we have:
> In order to build, test and link to the codec on UNIX, you need Perl, Yasm, CMake, Clang and pkg-config. To install this on Ubuntu or Linux Mint, run:
>
> sudo apt install perl yasm cmake clang pkg-config
>
> On Windows, pkg-config is not required. A Perl distribution such as Strawberry Perl, CMake, and a Yasm binary in your system PATH are required.

Might be a good idea reporting to pkg-config that it should provide a friendlier error message.

**Comment by lu-zero** [comment]
https://github.com/alexcrichton/pkg-config-rs/issues/56 is tracking this issue already.

**Comment by rzumer** [comment]
Closing, as this should be fixed on `pkg-config-rs`'s end if the error message is not displayed as expected (it should be, based on the `probe` function).
