### ISSUE TITLE
Failed to decode tile data

### ISSUE THREAD

**Issue by f11894** [xiph/rav1e#558]
I use google translation.
When encoding with rav1e with the following command, it becomes a frame which can not be decoded correctly.

```rav1e --quantizer 100 pedestrian_area_1080p25.y4m --output pedestrian_area_1080p25_q100.ivf```

The error messages of libaom are as follows.

> Warning: Failed to decode frame 6: Corrupt frame detected
> Warning: Additional information: Failed to decode tile data

Input video
https://media.xiph.org/video/derf/
pedestrian_area_1080p25.y4m

Output video
https://www.dropbox.com/s/8behoitm2g6k10f/pedestrian_area_1080p25_q100.ivf?dl=0

rav1e b3283b8

**Comment by ycho** [comment]
@xiphmont , hi Monty, can you check this pls? It seems someone still see desync right after your fix.
