### ISSUE TITLE
Port changes from ibc_optimize branches to master rav1e, guarded under speed levels.

### ISSUE THREAD

**Issue by tdaede** [xiph/rav1e#590]
https://github.com/KyleSiefring/rav1e/tree/ibc_optimize_6

**Comment by rzumer** [comment]
I would suggest thinking of a way to fulfill #290 as well in order to avoid making speed-based decisions too spread out and hard to find.

**Comment by tdaede** [comment]
Don't think this is useful anymore with the speed level retuning.
