### ISSUE TITLE
decode_test seems broken

### ISSUE THREAD

**Issue by ycho** [xiph/rav1e#595]
If I run "cargo test --release --features=decode_test -- --ignored"
I've got error like below:

lassen:rav1e yushin$ cargo test --release --features=decode_test -- --ignored
   Compiling rav1e v0.1.0 (file:///Users/yushin/workspace/rav1e)                                                          
**error: failed to run custom build command for `rav1e v0.1.0 (file:///Users/yushin/workspace/rav1e)`**
process didn't exit successfully: `/Users/yushin/workspace/rav1e/target/release/build/rav1e-9ccff9518ec43e20/build-script-build` (exit code: 101)
--- stdout
CMake project was already configured. Skipping configuration step.

......
Checking C compiler flag support for: -mavx2
Checking C compiler flag support for: -std=c++11
Use of uninitialized value $git_desc in numeric gt (>) at /Users/yushin/workspace/rav1e/aom_build/aom/build/cmake/version.pl line 63.
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang**/9.0.0/include/inttypes.h:30:15: fatal error: 'inttypes.h' file not found
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/include/inttypes.h:30:15: fatal error: 'inttypes.h' file not found, err: true
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.**

**Comment by ycho** [comment]
Same error even after "cargo clean".

**Comment by lu-zero** [comment]
your clang toolchain seems to have a problem. On my macos I have:
```
clang --version
Apple LLVM version 9.1.0 (clang-902.0.39.2)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by lu-zero** [comment]
also, there is a problem with debug tests:
```
---- test_encode_decode::high_bd stdout ----
Encoding 64x80 speed 0 quantizer 100
thread 'test_encode_decode::high_bd' panicked at 'attempt to subtract with overflow', src/deblock.rs:419:19
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

But I guess it is known already

**Comment by ycho** [comment]
Ok, it seems because my clang points to the one from emscripten. Look below.

lassen:rav1e yushin$ clang --version
clang version 6.0.1  (emscripten 1.38.11 : 1.38.11)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Users/yushin/emsdk-portable/clang/e1.38.11_64bit
lassen:rav1e yushin$

**Comment by lu-zero** [comment]
Did you fix it?

**Comment by ycho** [comment]
Yes! It only broke on my sides.
After commenting out:
#source $HOME/emsdk-portable/emsdk_env.sh
and
lassen:rav1e yushin$source ~./bash_profile
then
lassen:rav1e yushin$ which clang
/usr/bin/clang
fixed it.
Thanks!
