### ISSUE TITLE
decode error at 12 bit caused by 1d697a41fdf7ebb56549cc766a6597228917dac9

### ISSUE THREAD

**Issue by xiphmont** [xiph/rav1e#622]
bisection reveals 1d697a41fdf7ebb56549cc766a6597228917dac9 introduces a decode desync (though not stream desync) at 12 bit -s3 nyancat (the test run in build.sh, though not run by default).

**Comment by xiphmont** [comment]
Mispasted the hash; the correct commit (the one that introduces the error) is 1d697a41fdf7ebb56549cc766a6597228917dac9

**Comment by xiphmont** [comment]
(I had originally pasted the wrong commit; edited subject and message to correct)

**Comment by KyleSiefring** [comment]
https://github.com/xiph/rav1e/commit/1d697a41fdf7ebb56549cc766a6597228917dac9#diff-6bf6ee78a7cbe6be71ea17a596ce07d2R700

These shifts should change for different bit depths. I don't know if this is the problem.

**Comment by xiphmont** [comment]
Note that the 10-bit nyancat passes, as do (apparently) the Travis tests.  The 12-bit nyancat encode is visibly corrupt (a few solid-colored blocks in output).
