### ISSUE TITLE
Migrating to Gitlab

### ISSUE THREAD

**Issue by tterribe** [xiph/rav1e#633]
These are the things that need to be done to migrate to Gitlab:
1) Mirroring updates
  A) The current mirroring scripts are located here: https://git.xiph.org/xiph-mirror.git
  B) They have intermittently been reported as broken, although when I attempted to test them, they worked fine. Today mark4o was able to track down one potential issue to the use of $(cd ...) || exit, which causes the script to attempt to execute anything output on stdout by the git commands (which fails). That prevents the mirroring of any other repositories after the first one to fail. Both issues (executing stdout and failure in one repository breaking all others) need to be addressed. An additional theory is that the Docker image may be running out of disk space (this hasn't been confirmed, but it shouldn't be hard to).
  C) Right now rav1e is not being automatically mirrored at all. The scripts are currently hard-coded to assume that all repos use the same source (git.xiph.org) and mirror to the same set of remotes (gitlab,xiph.org, github.com). Ideally these need to be generalized to allow us to migrate repos on an individual basis (or we need to be sure that all Xiph projects are ready to make the switch). I have an untested rewrite that allows them to do this that I should push somewhere, although if someone else wants to look at this, it may be easier to just write new scripts from scratch than to try to find my bugs.
  D) The Docker image on catfish.xiph.org needs to be rebuilt and re-started. Currently the source for this image lives in /home/giles/xiph-mirror and the id of the actual instance is b1ea9b5df42c. I have no idea how it is intended to be started (e.g., if catfish gets rebooted). It may currently be a manual process.
2) CI: I don't know how this is currently set up on Github. Presumably Gitlab-CI can do something similar.
3) AWCY integration: I know someone was working on this for Github, but I don't know the current status. The end goal here would be per-commit AWCY runs like we had for daala. Ideally we shouldn't regress anything that people have already managed to get working.

**Comment by shssoichiro** [comment]
I've some experience setting up Gitlab CI and integrations and can help with this. What is the current status of this issue? Is there an existing project/group in Gitlab?

**Comment by tdaede** [comment]
We have a self hosted instance here: https://gitlab.xiph.org/xiph

There is a rav1e project there, but it probably needs to be deleted and re-mirrored.

**Comment by Luni-4** [comment]
@shssoichiro 

Are we still interested in this one?

**Comment by shssoichiro** [comment]
At this point, I think we're cemented enough in Github that it doesn't really make sense to move to Gitlab, unless someone wanted to set up a mirror for redundancy reasons.
