### ISSUE TITLE
Write tests for the transforms

### ISSUE THREAD

**Issue by lu-zero** [xiph/rav1e#635]
in `src/transform.rs`

- [ ] av1_fwd_txfm2d_4x4
- [ ] av1_fwd_txfm2d_8x8
- [ ] av1_fwd_txfm2d_16x16
- [ ] av1_fwd_txfm2d_32x32

- [ ] av1_inv_txfm2d_add_4x4
- [ ] av1_inv_txfm2d_add_8x8
- [ ] av1_inv_txfm2d_add_16x16
- [ ] av1_inv_txfm2d_add_32x32

**Comment by tmatth** [comment]
@lu-zero would something equivalent to these make sense?
https://aomedia.googlesource.com/aom/+/067e984254e658863b8c6dc335e26f92ecc32c1c/test/transform_test_base.h#47

Namely: accuracy tests and bit exactness tests.

**Comment by lu-zero** [comment]
It feels relatively overkill for an easy task. 
We can have it with [proptest](https://docs.rs/crate/proptest/), but it is harder than just do what we have for `get_sad`.

**Comment by lu-zero** [comment]
Solved by #697

**Comment by rzumer** [comment]
Closing as resolved.
