### ISSUE TITLE
Comparison with x265/hevc

### ISSUE THREAD

**Issue by grill02** [xiph/rav1e#648]
I wanted to test the current rav1e on a few video files to see if the encoding time and bitrate reduction made it worthwhile to encode new videos in av1 instead of ffmpeg+libx265. There are a few parameters that I am unsure about. 

1) ffmpeg+libx265 uses a default crf of 28 and a default preset of 'medium'. The corresponding parameters in rav1e seem to be `--tune Psychovisual` and `--speed` . Now in x265 one can vary the crf to increase/reduce bitrate depending on the use case. Is there a way to do this with  `--tune Psychovisual` ?
 `--quantizer` seems to be tunable, but is changing the quantizer comparable to changing crf in x265/x264?

2) ffmpeg+libx265 uses all cores on my machine, and the recent aomenc also has some degree of multithreading. The current rav1e only seems to be running on a single core. Am I missing something or is this the current design?

thanks

**Comment by tdaede** [comment]
1. --quantizer is the current analog to crf on x265. I would love to add a crf option, someone just needs to figure out a mapping of quantizer to crf values. Making the values "approximately" match 264 seems like a good idea.

--tune psychovisual doesn't seem to work very well yet. see https://github.com/xiph/rav1e/issues/519

2. It's part of the design, but not final. That said, you're generally expected to use something like this: https://github.com/nergdron/dve or my fork https://github.com/tdaede/dve if you are doing offline encoding.

**Comment by grill02** [comment]
Ok.

In all cases I tested (180p,240p,480p) the default settings (--speed 3 --quantizer 100) produce files with bitrate higher than latest x265 (2.9). The bitrates seem to be 50-75% higher for rav1e compared with x265.
quantizer levels below 130 seem to bring bitrate down to roughly the same as x265 but the deterioration in video quality is quite apparent ,especially below 140-150.

These are my subjective observations on the basis of testing with quite a few files (live action/animation). I guess it'll be a while before I can use av1 as default in place of x265.

thanks.

**Comment by tdaede** [comment]
Yeah that's expected. We're improving rapidly though.
You should also consider using libaom (at higher speed levels than necessary). rav1e is mostly useful at the moment when libaom speed 8 isstill too slow, though we're working on changing that.

If you're interested, it would be great to have visual testing and feedback on some new features we're working on.

**Comment by grill02** [comment]
@tdaede I would love to help. However, I am not on a very fast connection. So downloading large datasets regularly would'nt work. 

ffmpeg+libaom-av1 has crf (default 30) but no --row-mt,--row-column, --tile-columns, or --tile-rows . aomenc only seems to have vbr,cbr,cq,q as rate control  methods.

**Comment by arpu** [comment]
i think it would be cool to add the ecoder to the https://arewecompressedyet.com/?  tests

**Comment by theChaosCoder** [comment]
Here are some results for x264/x265/rav1e with different quality metrics https://forum.doom9.org/showthread.php?p=1867137#post1867137
(scroll up for more context)

**Comment by tdaede** [comment]
Closing this in favor of #1248.
