### ISSUE TITLE
Remove the depencency on libaom in encoder.rs

### ISSUE THREAD

**Issue by lu-zero** [xiph/rav1e#651]
- [ ] av1_rtcd
- [ ] aom_dsp_rtcd 

Used mainly to plug in the [transform.rs](https://github.com/xiph/rav1e/issues/652) functions.

**Comment by shssoichiro** [comment]
These methods set up the function pointers based on CPU architecture. It may be difficult to remove this dependency until all the dependent C code has been ported (the items in #652 are among those but there may be others).

**Comment by lu-zero** [comment]
That's correct :) and since they would be still used in tests it would make sense to move those calls there and not just remove them.
