### ISSUE TITLE
Build error related to nasm

### ISSUE THREAD

**Issue by ycho** [xiph/rav1e#659]
On Ubuntu 16.04 LTS (Thinkpad W540), (It works well on my MacBook)
NASM version 2.11.08

yushin@maui:~/workspace/rav1e$ ./build.sh 
File ‘nyan.y4m’ already there; not retrieving.

   Compiling cc v1.0.18
   Compiling libc v0.2.43
   Compiling pkg-config v0.3.13
   Compiling num-traits v0.2.5
   Compiling unicode-width v0.1.5
   Compiling nasm-rs v0.1.3 (https://github.com/tdaede/nasm-rs.git#7c01c74c)
   Compiling bitflags v1.0.3
   Compiling rand_core v0.2.1
   Compiling vec_map v0.8.1
   Compiling rustc-demangle v0.1.9
   Compiling strsim v0.7.0
   Compiling cfg-if v0.1.4
   Compiling ansi_term v0.11.0
   Compiling y4m v0.3.0
   Compiling bitstream-io v0.8.1
   Compiling textwrap v0.10.0
   Compiling atty v0.2.11
   Compiling rand v0.5.4
   Compiling clap v2.32.0
   Compiling backtrace-sys v0.1.23
   Compiling cmake v0.1.32
   Compiling rav1e v0.1.0 (file:///home/yushin/workspace/rav1e)
   Compiling backtrace v0.3.9
error: failed to run custom build command for `rav1e v0.1.0 (file:///home/yushin/workspace/rav1e)`
process didn't exit successfully: `/home/yushin/workspace/rav1e/target/release/build/rav1e-db3e9a27f5ce9405/build-script-build` (exit code: 101)
--- stdout
running: "nasm" "-felf64" "-I/home/yushin/workspace/rav1e/target/release/build/rav1e-b6e338580dfa27c6/out/" "-Isrc/" "/home/yushin/workspace/rav1e/src/x86/mc.asm" "-o" "/home/yushin/workspace/rav1e/target/release/build/rav1e-b6e338580dfa27c6/out/src/x86/mc.o"

--- stderr
/home/yushin/workspace/rav1e/src/x86/mc.asm:141: error: beroset-p-637-invalid effective address
/home/yushin/workspace/rav1e/src/x86/mc.asm:245: error: beroset-p-637-invalid effective address
/home/yushin/workspace/rav1e/src/x86/mc.asm:378: error: beroset-p-637-invalid effective address
/home/yushin/workspace/rav1e/src/x86/mc.asm:540: error: beroset-p-637-invalid effective address
/home/yushin/workspace/rav1e/src/x86/mc.asm:743: error: beroset-p-637-invalid effective address
/home/yushin/workspace/rav1e/src/x86/mc.asm:871: error: beroset-p-637-invalid effective address
/home/yushin/workspace/rav1e/src/x86/mc.asm:1033: error: beroset-p-637-invalid effective address
/home/yushin/workspace/rav1e/src/x86/mc.asm:1222: error: beroset-p-637-invalid effective address
/home/yushin/workspace/rav1e/src/x86/mc.asm:1461: error: beroset-p-637-invalid effective address
/home/yushin/workspace/rav1e/src/x86/mc.asm:1483: error: beroset-p-637-invalid effective address
/home/yushin/workspace/rav1e/src/x86/mc.asm:1484: error: beroset-p-637-invalid effective address
/home/yushin/workspace/rav1e/src/x86/mc.asm:1485: error: beroset-p-637-invalid effective address
/home/yushin/workspace/rav1e/src/x86/mc.asm:1492: error: beroset-p-637-invalid effective address
/home/yushin/workspace/rav1e/src/x86/mc.asm:1512: error: beroset-p-637-invalid effective address
/home/yushin/workspace/rav1e/src/x86/mc.asm:1608: error: beroset-p-637-invalid effective address
/home/yushin/workspace/rav1e/src/x86/mc.asm:1610: error: beroset-p-637-invalid effective address
/home/yushin/workspace/rav1e/src/x86/mc.asm:1823: error: beroset-p-637-invalid effective address
/home/yushin/workspace/rav1e/src/x86/mc.asm:1828: error: beroset-p-637-invalid effective address
/home/yushin/workspace/rav1e/src/x86/mc.asm:1963: error: beroset-p-637-invalid effective address
/home/yushin/workspace/rav1e/src/x86/mc.asm:1964: error: beroset-p-637-invalid effective address
/home/yushin/workspace/rav1e/src/x86/mc.asm:1969: error: beroset-p-637-invalid effective address
/home/yushin/workspace/rav1e/src/x86/mc.asm:2123: error: beroset-p-637-invalid effective address
/home/yushin/workspace/rav1e/src/x86/mc.asm:2143: error: beroset-p-637-invalid effective address
/home/yushin/workspace/rav1e/src/x86/mc.asm:2144: error: beroset-p-637-invalid effective address
/home/yushin/workspace/rav1e/src/x86/mc.asm:2145: error: beroset-p-637-invalid effective address
/home/yushin/workspace/rav1e/src/x86/mc.asm:2151: error: beroset-p-637-invalid effective address
/home/yushin/workspace/rav1e/src/x86/mc.asm:2246: error: beroset-p-637-invalid effective address
/home/yushin/workspace/rav1e/src/x86/mc.asm:2429: error: beroset-p-637-invalid effective address
/home/yushin/workspace/rav1e/src/x86/mc.asm:2435: error: beroset-p-637-invalid effective address
/home/yushin/workspace/rav1e/src/x86/mc.asm:2521: error: beroset-p-637-invalid effective address
/home/yushin/workspace/rav1e/src/x86/mc.asm:2522: error: beroset-p-637-invalid effective address
/home/yushin/workspace/rav1e/src/x86/mc.asm:2527: error: beroset-p-637-invalid effective address
thread 'main' panicked at 'nonzero exit status: exit code: 1', /home/yushin/.cargo/git/checkouts/nasm-rs-4e8d02e8a0db2eea/7c01c74/src/lib.rs:340:9
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:511
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:426
   6: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:413
   7: nasm_rs::run
   8: nasm_rs::Build::compile_objects
   9: nasm_rs::Build::compile
  10: build_script_build::main
  11: std::rt::lang_start::{{closure}}
  12: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  13: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  14: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  15: main
  16: __libc_start_main
  17: _start

warning: build failed, waiting for other jobs to finish...
error: build failed
yushin@maui:~/workspace/rav1e$

**Comment by lu-zero** [comment]
Are you on mac?

**Comment by ycho** [comment]
It is fine on my mac os, but failing on Ubuntu.

**Comment by lu-zero** [comment]
which version of nasm do you have installed?

**Comment by ycho** [comment]
NASM on ubuntu is version 2.11.08

**Comment by lu-zero** [comment]
You need 2.13.

**Comment by ycho** [comment]
Thanks, works after installing nasm 2.13. 
(On Ubuntu 16.04, apt-get does not have that version, so manually installed)
