### ISSUE TITLE
The assembler changed to use nasm error

### ISSUE THREAD

**Issue by tnti** [xiph/rav1e#661]
TNTI@DESKTOP-4I1KMV3 /e/rav1e
$ cargo build --release
    Compiling rav1e v0.1.0 (file:///E:/rav1e)
Error: failed to run custom build command for rav1e v0.1.0 (file:///E:/rav1e)
Process didn't exit successfully: e:\rav1e\target\release\build\rav1e-ecb1cf6943cb39f1\build-script-build (exit code: 101)
--- stdout
Running: "nasm" "-fwin64" "-Ie:\rav1e\target\release\build\rav1e-63dbf1bcd1d6ad4d\out/" "-Isrc/" "e:\rav1e\src/ X86/mc.asm" "-o" "e:\rav1e\target\release\build\rav1e-63dbf1bcd1d6ad4d\out\src/x86\mc.o"
Running: "lib" "/NAME:rav1easm.lib" "e:\rav1e\target\release\build\rav1e-63dbf1bcd1d6ad4d\out\src/x86\mc.o"

--- stderr
Thread 'main' panicked at 'failed to spawn process: The system cannot find the file specified. (os error 2)', C:\Users\TNTI.cargo\git\checkouts\nasm-rs-4e8d02e8a0db2eea\7c01c74\src\lib.rs:336:19
Note: Run with RUST_BACKTRACE=1 for a backtrace.

The above message appears when using x86_64-pc-windows-msvc.

**Comment by tnti** [comment]
error: failed to run custom build command for `rav1e v0.1.0 (file:///E:/rav1e)`
process didn't exit successfully: `e:\rav1e\target\release\build\rav1e-8f1a93b0b6501a3d\build-script-build` (exit code: 101)
--- stdout
running: "nasm" "-fwin64" "-Ie:\\rav1e\\target\\release\\build\\rav1e-748a63817d424d0b\\out/" "-Isrc/" "e:\\rav1e\\src/x86/mc.asm" "-o" "e:\\rav1e\\target\\release\\build\\rav1e-748a63817d424d0b\\out\\src/x86\\mc.o"
running: "ar" "crus" "e:\\rav1e\\target\\release\\build\\rav1e-748a63817d424d0b\\out\\librav1easm.a" "e:\\rav1e\\target\\release\\build\\rav1e-748a63817d424d0b\\out\\src/x86\\mc.o"
cargo:rustc-flags=-L e:\rav1e\target\release\build\rav1e-748a63817d424d0b\out
running: "cmake" "e:\\rav1e\\aom_build/aom" "-G" "MSYS Makefiles" "-DCONFIG_DEBUG=0" "-DCONFIG_ANALYZER=0" "-DENABLE_DOCS=0" "-DENABLE_NASM=1" "-DENABLE_TESTS=0" "-DCMAKE_INSTALL_PREFIX=e:\\rav1e\\target\\release\\build\\rav1e-748a63817d424d0b\\out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -m64" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -m64" "-DCMAKE_BUILD_TYPE=Release"
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: E:/MSYS/mingw/bin/gcc.exe
-- Check for working C compiler: E:/MSYS/mingw/bin/gcc.exe -- broken
-- Configuring incomplete, errors occurred!
See also "E:/rav1e/target/release/build/rav1e-748a63817d424d0b/out/build/CMakeFiles/CMakeOutput.log".
See also "E:/rav1e/target/release/build/rav1e-748a63817d424d0b/out/build/CMakeFiles/CMakeError.log".

--- stderr
CMake Error at D:/Program Files/CMake/share/cmake-3.12/Modules/CMakeTestCCompiler.cmake:52 (message):
  The C compiler

    "E:/MSYS/mingw/bin/gcc.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: E:/rav1e/target/release/build/rav1e-748a63817d424d0b/out/build/CMakeFiles/CMakeTmp

    Run Build Command:"E:/MSYS/bin/make.exe" "cmTC_dc4bc/fast"
    /usr/bin/make -f CMakeFiles/cmTC_dc4bc.dir/build.make CMakeFiles/cmTC_dc4bc.dir/build
    make[1]: Entering directory `/e/rav1e/target/release/build/rav1e-748a63817d424d0b/out/build/CMakeFiles/CMakeTmp'
    Building C object CMakeFiles/cmTC_dc4bc.dir/testCCompiler.c.obj
    /E/MSYS/mingw/bin/gcc.exe   -ffunction-sections -fdata-sections -m64    -o CMakeFiles/cmTC_dc4bc.dir/testCCompiler.c.obj   -c /E/rav1e/target/release/build/rav1e-748a63817d424d0b/out/build/CMakeFiles/CMakeTmp/testCCompiler.c
    cc1.exe: sorry, unimplemented: 64-bit mode not compiled in
    make[1]: *** [CMakeFiles/cmTC_dc4bc.dir/testCCompiler.c.obj] Error 1
    make[1]: Leaving directory `/e/rav1e/target/release/build/rav1e-748a63817d424d0b/out/build/CMakeFiles/CMakeTmp'
    make: *** [cmTC_dc4bc/fast] Error 2




  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:60 (project)


thread 'main' panicked at '
command did not execute successfully, got: exit code: 1

build script failed, must exit now', C:\Users\TNTI\.cargo\registry\src\github.com-1ecc6299db9ec823\cmake-0.1.35\src\lib.rs:778:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

warning: build failed, waiting for other jobs to finish...
The above message appears when using x86_64-pc-windows-gnu.

**Comment by uswoods** [comment]
For me it works. Just install nasm.

**Comment by moisesmcardona** [comment]
I had to run first ` "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"` and then run `cargo build --release` which built rav1e successful

**Comment by tnti** [comment]
Thank @moisesmcardona tnti
I have successfully built rav1e.
