### ISSUE TITLE
linker warnings

### ISSUE THREAD

**Issue by ycho** [xiph/rav1e#699]
Tried this on Ubuntu 16.04 LTS

yushin@maui:~/workspace/rav1e$ uname -a
Linux maui 4.4.0-131-generic #157-Ubuntu SMP Thu Jul 12 15:51:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

yushin@maui:~/workspace/rav1e$ cargo clean
yushin@maui:~/workspace/rav1e$ cargo build --bin rav1e --release
   Compiling cc v1.0.18
   Compiling libc v0.2.43
   Compiling nasm-rs v0.1.3 (https://github.com/tdaede/nasm-rs.git#7c01c74c)
   Compiling num-traits v0.2.5
   Compiling unicode-width v0.1.5
   Compiling pkg-config v0.3.13
   Compiling vec_map v0.8.1
   Compiling bitflags v1.0.3
   Compiling strsim v0.7.0
   Compiling rustc-demangle v0.1.9
   Compiling ansi_term v0.11.0
   Compiling cfg-if v0.1.4
   Compiling rand_core v0.2.1
   Compiling y4m v0.3.0
   Compiling bitstream-io v0.8.1
   Compiling textwrap v0.10.0
   Compiling atty v0.2.11
   Compiling rand v0.5.4
   Compiling clap v2.32.0
   Compiling backtrace-sys v0.1.23
   Compiling cmake v0.1.32
   Compiling rav1e v0.1.0 (file:///home/yushin/workspace/rav1e)
   Compiling backtrace v0.3.9
warning: redundant linker flag specified for library `m`

warning: redundant linker flag specified for library `pthread`

    Finished release [optimized] target(s) in 1m 28s
yushin@maui:~/workspace/rav1e$

**Comment by kodabb** [comment]
those are pulled by libaom, I don't think there is anything actionable here

**Comment by ycho** [comment]
Thanks, also I confirm that the warninhs has luckily gone since sometime ago. Don't know when.
