### ISSUE TITLE
Adaptive keyframe placement

### ISSUE THREAD

**Issue by shssoichiro** [xiph/rav1e#717]
rav1e appears to currently use a constant interval between keyframes. Many other encoders, including aomenc, set a configurable "min" and "max" distance between keyframes, and use scenecut detection to determine the optimal location for a keyframe. This can provide a considerable boost to compression.

**Comment by tdaede** [comment]
To implement this, we need a first pass or lookahead. Basically encode the frame once (at a fast speed level), look at metrics (such as # of intra blocks, # of skip, or even just bitrate), then decide whether to make it a keyframe or not for the real encode.

**Comment by shssoichiro** [comment]
I think we could implement this without the need for lookahead if we use a simple scene-change mechanism, e.g. if a frame is "different enough" from the previous frame then code it as a keyframe. I think there's a question of quality vs. speed tradeoffs in the different implementations. A lookahead pass could be useful for future improvements as well.

**Comment by SmilingWolf** [comment]
While I'm sure there's 1001 good papers about scene change detection, I tried my hand at implementing this one (http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.84.6062&rep=rep1&type=pdf) in python a while back.
Works well enough for VN galleries, altough the thresholds needed some tweaking in my case.
I think I only needed the past 2 frames in addition to the current one to detect a change, and the code came out rather compact too.

My python implementation: https://github.com/SmilingWolf/JustPythonThings/blob/master/SceneChangeDetect/SceneChangeDetect.PIL.py

**Comment by shssoichiro** [comment]
I'll work on this later tonight. Thanks for the link @SmilingWolf. I've also been looking at https://github.com/Breakthrough/PySceneDetect/tree/master/scenedetect/detectors which has a couple of different algorithms. This doesn't seem like it should be too difficult to implement with low performance impact.

**Comment by shssoichiro** [comment]
I'm having difficulty getting the results I expect, and I think I need help understanding how the data is stored within a `Frame`. There are 3 planes (YUV presumably?) but the first plane is about 4 times the length of the other two planes, and neither match the `width * height` of the video.

Is there a method I can use to get the whole data for a plane as a slice? (I've been using `.data_origin` and am not sure if this is correct) and,
How do I reconcile the three planes to line them up pixel-to-pixel?

**Comment by tdaede** [comment]
The video is normally 4:2:0, so yeah the planes 1 and 2 are one quarter the size of plane 0. When we add 4:4:4, we will need to add xdec and ydec variables to keep track of the relative sizes.

The size of the actual frame and of the stride is in width/height/padded_w/padded/h of FrameInvariants.

**Comment by tdaede** [comment]
If you're doing a simple plane difference, then you shouldn't need to convert to RGB either, the data in YUV will be equivalent.

**Comment by shssoichiro** [comment]
I'm a bit stuck trying to wrap around how the `idx` in the `receive_packet` method is incrementing. My branch works wonderfully with default settings, but with low_latency == false exhibits issues ranging from dropping frames, to panics, to infinite loops. I know the issue is that, in low latency mode, the `idx` in the `Context` doesn't match the real frame number, but I'm struggling to figure out how to resolve this. Essentially, we need to know the frame number in order to decide the frame type, but in low latency mode we need to know the frame type in order to decide the frame number.

**Comment by shssoichiro** [comment]
I think I've found an approach that works. It's kind of ugly, but in my limited test cases it works. Going to write some automated tests, do some more manual testing, and hopefully open a PR tonight.
