### ISSUE TITLE
Support chroma sampling other than 4:2:0

### ISSUE THREAD

**Issue by yushincho** [xiph/rav1e#72]
Would be happy if we can do this by 2020.

**Comment by rzumer** [comment]
Started in #453.

**Comment by rzumer** [comment]
More progress in #908, #911, #914. Remaining issue seems related to motion compensation, which causes blocking in chroma on inter frames in the restoration buffer. Inter frames are also not decodable, perhaps for the same reason.

**Comment by rzumer** [comment]
Encoding is supported as of #947 with features disabled (inter frames, restoration, CfL prediction, <8X8 blocks).
