### ISSUE TITLE
Support Color config 

### ISSUE THREAD

**Issue by lu-zero** [xiph/rav1e#728]
[6.4.2. Color config semantics](https://aomediacodec.github.io/av1-spec/av1-spec.pdf#page=128) let you express colorspace details.

y4m does not provide a mean to add the information in itself currently, so we should be able to provide a mean to set it. (or support raw-video in mkv)

- [ ] Add the API surface for it
- [ ] Provide CLI arguments for it

**Comment by dwbuiten** [comment]
Yes, please!

**Comment by tdaede** [comment]
@rzumer do you want to do this? It's basically the rest of #781

**Comment by lu-zero** [comment]
I have already the enums in rust-av, I can copy them now.
