### ISSUE TITLE
A better name?

### ISSUE THREAD

**Issue by mbebenita** [xiph/rav1e#73]
rav1e is great and all, but it doesn't quite roll off the tongue. Let's comment on this issue with name ideas, and then vote on them using 👍.

**Comment by mbebenita** [comment]
Rave

**Comment by yushincho** [comment]
The 'r' of rav1e made me think of the R of Racing version. If #1 goal of this project is SPEED.
So, I'd propose 'av1R'  or 'av1Rus'.

Btw, I guess you mean the 'Rave', the English word?

**Comment by tmatth** [comment]
The 1 is silent, I'm ok with rav1e.

**Comment by negge** [comment]
I still like ravioli (with or without the i as 1).  I would also support xav1 :)

**Comment by mbebenita** [comment]
> ravioli

Is not a serious enough encoder name. I guess Android names are not serious either, ...

**Comment by yushincho** [comment]
Yes, we wanna go sth like: 2F2F, Need For Speed.

**Comment by yushincho** [comment]
So, nobody likes av1Rus (didn't mean 'toysRus' in the beginning :)

**Comment by lu-zero** [comment]
`rav1e` seems search friendly so far. 

It can be pronounced as `rave` or `ravìe` for additional confusion points during the presentations.

I'm sure we can come up with enough shape of pasta for the release codenames. (I book the first pre release as [plin](https://en.wikipedia.org/wiki/Agnolotti))

**Comment by smarter** [comment]
TGV encoder, as in The Greatest Video encoder, but mostly as a reference to the [Train à Grande Vitesse](https://en.wikipedia.org/wiki/TGV).

**Comment by gnafuthegreat** [comment]
I like another suggestion of smarter's, "zeppelin":

    <smarter> ltrudeau: we could call the encoder zeppelin

**Comment by yushincho** [comment]
Or, I can even name it from the Street name where TDLinux's apartment is located.
What was it, TD?

**Comment by luctrudeau** [comment]
Metropole

as an hommage to the best hotel in Brussels. When in Brussels, any self respecting person stays at the Metropole as it not only the best but it is not a family friendly hotel, and thus does not inherit all the faults of family friendly hotels.

**Comment by luctrudeau** [comment]
ROFLCoder
```
         ________________
         \  [ROFLCoder]   \
1010101   \                \   L0L
           \ ________________]
```

**Comment by rzumer** [comment]
Closing for now since it does not seem like a name change is expected, but feel free to suggest more very serious and professional names. For everyone's consideration there is also @smarter's latest suggestion Ramen.
