### ISSUE TITLE
Adaptive Quantization

### ISSUE THREAD

**Issue by shssoichiro** [xiph/rav1e#752]
Many encoders, including AOM, implement an adaptive quantization algorithm, which is a psychovisual algorithm designed to distribute bitrate among the macroblocks in a frame in a way that improves perceived quality.

AOM implements three different algorithms: 
- variance-based
- complexity-based
- cyclic refresh. 

There are also variations on these implemented by other encoders; e.g. x264 implements three variations of a variance-based AQ, one of which also uses a complexity mask. 

We should select which AQ algorithms we would like to implement, and select one to begin with as a "default".

**Comment by ycho** [comment]
I think it should be corrected that the reference implementation of AV1 encoder, i.e. libaom specifically, implements those three AQ algorithms, not the AOM itself. How to decide the QPs are not standardized by AV1 spec, and I believe many view the method of how as experimental and some folks like HW encoder makers take it even skeptical.

**Comment by ycho** [comment]
Also atomnuker (Rostslav) is working on it currently, so you may want to ask him about the plan.

**Comment by ycho** [comment]
Maybe you know, #771 is addressing on this.

**Comment by utack** [comment]
Is the spatial aq similar to variance aq?

**Comment by rzumer** [comment]
I believe that #1263 is relevant to this issue.

**Comment by dwbuiten** [comment]
Yes, after #1263 and #1323 are working/in, work on adapting block-level quants can start.

**Comment by vibhoothiiaanand** [comment]
#2247 Implements Spatial AQ
