### ISSUE TITLE
Add a dav1d-based decode test

### ISSUE THREAD

**Issue by lu-zero** [xiph/rav1e#764]
Once dav1d has a release.

- [x] write the bindings (dav1d-rs)
- [x] make an option for it
- [x] have the tests run using aom and/or dav1d depending on the options.

**Comment by tmatth** [comment]
dav1d now has a release: https://code.videolan.org/videolan/dav1d/tags/0.1.0

**Comment by lu-zero** [comment]
I started working on it and I prepared a crate so the amount of code in the tree is small.

Hopefully within the week I'll have it landed :)

**Comment by lu-zero** [comment]
The integration works but dav1d seems to decode 1 pixel wrong per frame.
