### ISSUE TITLE
GPU encoding acceleration

### ISSUE THREAD

**Issue by Johnreidsilver** [xiph/rav1e#766]
Any plans to add GPU encoding acceleration as in open sourced general purpose computing (not fixed function), like OpenCL ?

**Comment by tdaede** [comment]
Not right now. There haven't been any successful attempts to add GPGPU to a video encoder yet. It would be an interesting project for someone, with the caveat that many of the obvious methods have been tried and don't work (as in, they aren't faster than doing it on a CPU).

**Comment by dvc94ch** [comment]
I believe Intel/Nvidia/AMD have support for encoding in their latest models now...
