### ISSUE TITLE
Switch adaptive keyframe placement algorithm to a cost-based one + tweaks

### ISSUE THREAD

**Issue by dwbuiten** [xiph/rav1e#794]
Filing a bug as encouraged by peeps on IRC.

Realistically, this will (should) yeild much, much better results than just a basic diff-like algorithm, and is what most reasonable encoders for various codecs seem to use. And, at least to me, most cost-efficient placement makes more sense for an encoder than just 'different', or what a human may call a scene change.

x264's placement decision code is pretty short (by encoder standards), easy to read, and a good reference, IMO: The [scenecut](https://git.videolan.org/?p=x264.git;a=blob;f=encoder/slicetype.c;h=8c3ef3ba172c1283c727398e6b8b795b8a7c0b7a;hb=HEAD#l1423) and [scenecut_internal](https://git.videolan.org/?p=x264.git;a=blob;f=encoder/slicetype.c;h=8c3ef3ba172c1283c727398e6b8b795b8a7c0b7a;hb=HEAD#l1377) functions are the relevant ones.

Also of note in those are some simple tweaks that can improve perf quite a lot, I think, like [avoiding problems with flashes/strobes](https://git.videolan.org/?p=x264.git;a=blob;f=encoder/slicetype.c;h=8c3ef3ba172c1283c727398e6b8b795b8a7c0b7a;hb=HEAD#l1429).

Of course, I don't know how hard this is to integrate into rav1e with its current code structure, or if it falls under "wait for trellis / aq / etc", etc.

Apologies if this is obvious or not useful to file as a bug.

**Comment by tdaede** [comment]
It's not dependent on aq, it's purely a frame level decision. The existing code importantly added the support for variable GOP structures, but there are definitely much better detection methods.

Basically, we need a lookahead or 2 pass with cost estimates for both a P and I frame.

**Comment by dwbuiten** [comment]
Lookahead would be better (and what x264 uses), no? (So as to support e.g. streaming.) Unless by 2-pass, you mean something more akin to a lookahead-y small 2-pass rather than full stream?

**Comment by tdaede** [comment]
Lookahead and 2-pass are basically equivalent (one stores the results in memory, one stores the results in a file), I would like to support them with the same code.

**Comment by dwbuiten** [comment]
Yeah, that's fair.

**Comment by shssoichiro** [comment]
Thanks for creating an issue to track this. I do have a branch in development that's using lookahead, based on the x264/x265 approach. It is a relatively large endeavour due to not having lookahead yet, but I'm hoping, as mentioned, that the same code could be used for two-pass encoding in the future.

**Comment by shssoichiro** [comment]
The flash detection was added a while back, and #1528 represents the remaining work on this. I'm going to close this and track the remaining work in #1528.
