### ISSUE TITLE
Will This tool Have Bitrate Encoding for Reduce Size

### ISSUE THREAD

**Issue by vus7294** [xiph/rav1e#802]
Title is description. Thanks.

**Comment by tdaede** [comment]
There is no rate control to choose an exact bitrate yet, but you can use the --quantizer option to change the size of the output already (higher numbers = smaller output)

**Comment by vus7294** [comment]
I Tried, but 720x480'd AVC Video that is 77mb, i Tried QT 100 and got 250mb Size Video, QT 30 with 440mb Size with Same Largement.
It Really needs Bitrate Control to Actually Reduce Size.

**Comment by tdaede** [comment]
The quantizer actually goes up to 255, try a higher value.

**Comment by shssoichiro** [comment]
It also sounds like you might be dealing with a particularly noisy or grainy video, if the size is going up significantly after reencoding. Any codec is not going to be good at reducing the size of grainy video, unless you denoise it first through some utility like Vapoursynth.

**Comment by grill02** [comment]
I had encountered similar results as well as mentioned here (https://github.com/xiph/rav1e/issues/648). Check tdeade's comment in that issue as well

**Comment by rzumer** [comment]
Since there is rough rate control integrated now, I will close this issue. See #1166 for further work that needs to be done to stabilize/improve rate control.
