### ISSUE TITLE
Warnings with "cargo bench"

### ISSUE THREAD

**Issue by yushincho** [xiph/rav1e#83]
yushin@maui:~/workspace/rav1e$ cargo test
   Compiling bitstream-io v0.6.3
   Compiling bitflags v1.0.1
   Compiling bencher v0.1.5
   Compiling bitflags v0.4.0
   Compiling encode_unicode v0.1.3
   Compiling vec_map v0.8.0
   Compiling unicode-width v0.1.4
   Compiling ansi_term v0.10.2
   Compiling y4m v0.1.1
   Compiling byteorder v1.2.1
   Compiling libc v0.2.36
   Compiling strsim v0.7.0
   Compiling textwrap v0.9.0
   Compiling nix v0.5.1
   Compiling atty v0.2.6
   Compiling rand v0.4.2
   Compiling clap v2.30.0
   Compiling rustyline v1.0.0
   Compiling rav1e v0.1.0 (file:///home/yushin/workspace/rav1e)
    Finished dev [unoptimized + debuginfo] target(s) in 9.73 secs
     Running target/debug/deps/rav1e-9b00cc822757fb1d

running 6 tests
test ec::test::booleans ... ok
test ec::test::cdf ... ok
test ec::test::mixed ... ok
test predict::test::pred_max ... ok
test predict::test::pred_same ... ok
test predict::test::pred_matches ... ok

test result: ok. 6 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/rav1e-5895d273f770ce9f

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/rav1repl-81dcf9202be56248

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

   Doc-tests rav1e

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

yushin@maui:~/workspace/rav1e$ cargo bench
   Compiling bencher v0.1.5
   Compiling rav1e v0.1.0 (file:///home/yushin/workspace/rav1e)
warning: unused import: `rav1e::predict::*;`
  --> benches/bench.rs:95:5
   |
95 | use rav1e::predict::*;
   |     ^^^^^^^^^^^^^^^^^^
   |
   = note: #[warn(unused_imports)] on by default

warning: unused variable: `mode`
   --> benches/bench.rs:111:9
    |
111 |     let mode = PredictionMode::DC_PRED;
    |         ^^^^
    |
    = note: #[warn(unused_variables)] on by default
    = note: to avoid this warning, consider using `_mode` instead

warning: foreign function is never used: `highbd_dc_left_predictor`
  --> benches/bench.rs:15:5
   |
15 | /     fn highbd_dc_left_predictor(dst: *mut u16, stride: libc::ptrdiff_t, bw: libc::c_int,
16 | |                            bh: libc::c_int, above: *const u16,
17 | |                            left: *const u16, bd: libc::c_int);
   | |______________________________________________________________^
   |
   = note: #[warn(dead_code)] on by default

warning: foreign function is never used: `highbd_dc_top_predictor`
  --> benches/bench.rs:18:5
   |
18 | /     fn highbd_dc_top_predictor(dst: *mut u16, stride: libc::ptrdiff_t, bw: libc::c_int,
19 | |                            bh: libc::c_int, above: *const u16,
20 | |                            left: *const u16, bd: libc::c_int);
   | |______________________________________________________________^

warning: foreign function is never used: `highbd_h_predictor`
  --> benches/bench.rs:21:5
   |
21 | /     fn highbd_h_predictor(dst: *mut u16, stride: libc::ptrdiff_t, bw: libc::c_int,
22 | |                            bh: libc::c_int, above: *const u16,
23 | |                            left: *const u16, bd: libc::c_int);
   | |______________________________________________________________^

warning: foreign function is never used: `highbd_v_predictor`
  --> benches/bench.rs:24:5
   |
24 | /     fn highbd_v_predictor(dst: *mut u16, stride: libc::ptrdiff_t, bw: libc::c_int,
25 | |         bh: libc::c_int, above: *const u16,
26 | |         left: *const u16, bd: libc::c_int);
   | |___________________________________________^

warning: function is never used: `pred_h_4x4`
  --> benches/bench.rs:37:1
   |
37 | fn pred_h_4x4(output: &mut [u16], stride: usize, above: &[u16], left: &[u16]) {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: function is never used: `pred_v_4x4`
  --> benches/bench.rs:44:1
   |
44 | fn pred_v_4x4(output: &mut [u16], stride: usize, above: &[u16], left: &[u16]) {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    Finished release [optimized] target(s) in 3.83 secs
     Running target/release/deps/rav1e-c60027f9b9bd002f

running 6 tests
test ec::test::booleans ... ignored
test ec::test::cdf ... ignored
test ec::test::mixed ... ignored
test predict::test::pred_matches ... ignored
test predict::test::pred_max ... ignored
test predict::test::pred_same ... ignored

test result: ok. 0 passed; 0 failed; 6 ignored; 0 measured; 0 filtered out

     Running target/release/deps/rav1e-ab1af7a55ae80597

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/release/deps/rav1repl-b79447a2b246d724

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/release/deps/bench-741fd4a6e67fa1d0

running 4 tests
test aom           ... bench:   1,188,882 ns/iter (+/- 38,736)
test native        ... bench:     975,183 ns/iter (+/- 59,961)
test native_trait  ... bench:     269,857 ns/iter (+/- 10,470)
test write_b_bench ... bench:     123,071 ns/iter (+/- 6,586)

test result: ok. 0 passed; 0 failed; 0 ignored; 4 measured

yushin@maui:~/workspace/rav1e$

**Comment by lu-zero** [comment]
Some tests aren't implemented yet so the references to C are currently unused.

**Comment by ycho** [comment]
Tested again, and no more warning messages coming.
