### ISSUE TITLE
Get mc.asm to compile

### ISSUE THREAD

**Issue by KyleSiefring** [xiph/rav1e#832]
mc.asm is not hooked and doesn't even compile up so inter prediction is slow (like 30% of the time spent). When added to the list of compiled asm files, I get an error complaining about undefined references to rav1e_mc_subpel_filters.

In dav1d, these tables are defined as such.

```
const int8_t ALIGN(dav1d_mc_subpel_filters[5][15][8], 8) = {
    [DAV1D_FILTER_8TAP_REGULAR] = {
        {   0,   1,  -3,  63,   4,  -1,   0,   0 },
...
```

This is basically the same thing as SUBPEL_FILTERS in partition.rs.
I cannot find any way to align an static array in rust. I also have no idea if a static rust array will have defined behavior when imported into assembly. It doesn't seem like it should.

I can think of three ways to work around this. 1st and 2nd are by defining the arrays a second time in C or asm. The 3rd is by defining the array only in C and removing the rust version.

I don't want to put this in mc.asm so the we can just copy over new versions. Maybe we use a separate file.

**Comment by KyleSiefring** [comment]
I'm thinking of adding it to assembly. Should this be a permanent solution? Probably not.

**Comment by tdaede** [comment]
Extern "C" should make it work in assembly. The assembly hardcodes C ABI in for various platforms, so as long as the rust uses C ABI, it's fine. That said, it seems that all the static alignment stuff only works on structs, not on arrays or other bare types :( maybe @lu-zero has a fix?

**Comment by lu-zero** [comment]
For static tables maybe [this](https://play.rust-lang.org/?version=nightly&mode=release&edition=2018&gist=42b6a1c52274b0b3d331f946468c38dc) is enough
