### ISSUE TITLE
Could not compile `proc-macro-hack`

### ISSUE THREAD

**Issue by kliffgomel** [xiph/rav1e#837]

**Comment by kliffgomel** [comment]
CFLAGS: -mthreads -mtune=generic -O2 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++
/opt/cargo/bin/cargo.exe build --release --target=x86_64-pc-windows-gnu --jobs=4
   Compiling proc-macro-hack v0.5.4
error[E0658]: non-ident macro paths are experimental (see issue #35896)
   --> D:/media-autobuild_suite/msys64/opt/cargo\registry\src\github.com-1ecc6299db9ec823\proc-macro-hack-0.5.4\src\lib.rs:267:5
    |
267 |     syn::custom_keyword!(support_nested);
    |     ^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: Could not compile `proc-macro-hack`.

To learn more, run the command again with --verbose.

**Comment by lu-zero** [comment]
Please provide the version of rust you are using.

Possibly issue a `rustup update` or make sure your toolchain is the current stable.

**Comment by kliffgomel** [comment]
Yes, the problem was this, thanks.
