### ISSUE TITLE
Add integration tests

### ISSUE THREAD

**Issue by yushincho** [xiph/rav1e#84]
That is another lovely built-in feature of Rust. Let's use it asap, and not writing hassle separate unit-tests programs.

**Comment by rzumer** [comment]
#365 introduces integration tests.

**Comment by ycho** [comment]
As I know, in addition to "cargo test", there is also "cargo integration"?
So, in https://doc.rust-lang.org/book/second-edition/ch11-03-test-organization.html
there is tests/integration_test.rs, and it seems it can be invoked by:
$ cargo test --test integration_test
Hence, I think we are already doing integration by tests/*.rs, but just not putting the code in the pre-defined  tests/integration_test.rs, that can be runnable by the option, "--test integration_test".

**Comment by lu-zero** [comment]
In general anything in `test/` can be built and executed as a program. I have already plans for it but that depends on when the code has less pending PR since would be better to write the tests on top of the public API (that incidentally I'm drafting since a while ^^).
