### ISSUE TITLE
Use predicted MV from larger size parent partitions for the ME for smaller block sizes < 32x32

### ISSUE THREAD

**Issue by ycho** [xiph/rav1e#840]
Instead of always using 32x32 pred MVs as ME seed, which pre-computed for each SB and does not change during the encoding of the SB.

**Comment by tmatth** [comment]
@ycho you're referring to https://github.com/xiph/rav1e/blob/master/src/encoder.rs#L2280 ?

**Comment by ycho** [comment]
Hey- Not really, but I meant the else part of it can be extended to
else if bsize == 32x32 {
} else {
// Use pmv from upper level of partioning, i.e. the parent block that is partitioned to children blocks, one of which is current block.
}

**Comment by ycho** [comment]
Done by 70005e353aa8ce21e3ecd257c927f71d4012a117
https://github.com/xiph/rav1e/pull/1177
