### ISSUE TITLE
BD rate change in bottomup partition search if early-exit is used for HORT or VERT partition types

### ISSUE THREAD

**Issue by ycho** [xiph/rav1e#877]
When early-exit for speed 0 (i.e. bottomup partition search) has landed, https://github.com/xiph/rav1e/commit/3a261f320befe0df2a6b89128dff708962402adb,
https://github.com/xiph/rav1e/pull/858,  (and enabled it by default) it introduces the change in bdrate, so later commit temporarily fixed it by allowing early-exit for PARTITION_SPLIT only.

The bdrate change was:

|   PSNR | PSNR Cb | PSNR Cr | PSNR HVS |   SSIM | MS SSIM | CIEDE 2000 |
|   ---: |    ---: |    ---: |     ---: |   ---: |    ---: |       ---: |
| 0.0046 |  0.0263 |  0.0246 |   0.0055 | 0.0032 |  0.0059 |     0.0151 |

 [AWCY results](https://beta.arewecompressedyet.com/?job=master_de68ab_s0_lowlatency%402019-01-16T01%3A27%3A21.601Z&job=early_exit_bottom_s0_low_latent%402019-01-16T01%3A27%3A37.303Z)

 Workaround, https://github.com/xiph/rav1e/pull/876, which only allows early-exit for PARTITION_SPLIT, solves the issue.
 However, no reason has been found about the bdrate change when early-exit is used for all types of partition, i.e. with HOR and VER added to SPLIT.

**Comment by ycho** [comment]
Hooray~~~! 
I was able to narrow down more. 
If CDEF is not used, then we can early-exit all cases, i.e. VERT/HORZ partitions.

What has been suspicious and unclear to me was when measuring the rate for partition type, such as: https://github.com/xiph/rav1e/blob/f82d92b3e0056c3f9fd9d626ebdc829a503ca8a8/src/encoder.rs#L2391, 
we use: let w: &mut dyn Writer = if cw.bc.cdef_coded {w_post_cdef} else {w_pre_cdef};
However, cw.bc.cdef_coded yet always false at this moment, and it can be set as true once a partition is encoded. That is: rdo_mode_decision(); --> encode_block_with_modes() -->  encode_block_a() and encode_block_b().
So, I probably need get helps from Monty. @xiphmont 
As I understand, the rates estimated (by writing to Writer) from w_post_cdef and w_pre_cdef can be different, correct?

**Comment by xiphmont** [comment]
they can be different due to the finite precision of the EC's counter (1/8th bit), and the current 'flush' state (and whatever stop bits would be needed to finalize?)

**Comment by ycho** [comment]
@xiphmont,
Alas, above my hooray was wrong.
In AWCY, for 5 frames, I tried CDEF off then compare partial and full early-exit for speed 0 (bottomup partition),
then there is still bdrate change.

[AWCY](https://beta.arewecompressedyet.com/?job=enable_full_earlyexit_for_bottomup_partition_cdef_off_s0_5f%402019-01-29T21%3A58%3A06.161Z&job=cdef_off_s0_5f%402019-01-29T21%3A56%3A11.025Z)

**Comment by ycho** [comment]
Confirm with [AWCY result](https://beta.arewecompressedyet.com/?job=early_exit_off_s0%402019-01-31T01%3A41%3A33.317Z&job=test_early_exit_horz_added_s0%402019-02-02T00%3A20%3A48.748Z) that horz partition is not culprit and vert causes the issue.

**Comment by ycho** [comment]
I have tried to switch the order of HORZ and VERT in partition_types array that is tested in order for bottomup partition search, then there is change of bdrate (not a regression) [AWCY](https://beta.arewecompressedyet.com/?job=change_part_order_early_exit_off_s0_5f%402019-02-04T21%3A48%3A03.555Z&job=early_exit_off_s0_5f%402019-01-31T01%3A40%3A12.239Z).
I think that this outcome would be related to the issue I am seeing.

**Comment by ycho** [comment]
Wow-
The order of testing really matter. If I test vert before horz then vert is fine with early-exit while horz now makes early-exit gives brdate change. 
I carefully think that the part_type right before the final one, i.e. split, but works differently from other part type that only split type has its reconstructed pixels kept at the end of part_type test loop.

[AWCY for early-exit for horz only, which gives bdrate change](https://beta.arewecompressedyet.com/?job=change_part_order_early_exit_off_s0_5f%402019-02-04T21%3A48%3A03.555Z&job=change_part_order_early_exit_if_vert_s0_5f%402019-02-05T04%3A17%3A19.900Z)
[AWCY for early-exit for vert only, which does not give bdrate change](https://beta.arewecompressedyet.com/?job=change_part_order_early_exit_off_s0_5f%402019-02-04T21%3A48%3A03.555Z&job=change_part_order_early_exit_if_vert_s0_5f%402019-02-05T04%3A17%3A19.900Z)

**Comment by ycho** [comment]
Not counting the rate for encoding partition type does not help either.
[AWCY result](https://beta.arewecompressedyet.com/?job=no_part_cost_earlyexit_off_s0_5f%402019-02-06T23%3A39%3A07.218Z&job=no_part_cost_earlyexit_all_s0_5f%402019-02-06T23%3A40%3A38.670Z)

**Comment by ycho** [comment]
Finally we've got good news!
It clearly seems the broken directional intra predictions modes is the cause of this issue.
With current master, which disables the directional intra pred,
i.e. https://github.com/xiph/rav1e/commit/8eae88fcda424c6cf0819102c1b7faaecde53d08
[I ran for 5 frames at -s 0 on AWCY, compare current master and full-early-exit (since current master does early-exit for SPLIT case only)
 and there is no change of bdrate this time with some improve of speed since full enabling of early-exit means bottomup partition search can now early-exit for HORZ and VERT partition types.](https://beta.arewecompressedyet.com/?job=master-8eae88fcd_s0_5f%402019-02-12T21%3A35%3A39.746Z&job=test_full_earlyexit_bottomup_s0_5f%402019-02-12T21%3A37%3A42.489Z)

I am further verifying by comparing: early-exit off vs full early-exit
[For 5 frames](https://beta.arewecompressedyet.com/?job=earlyexit_off_s0_5f%402019-02-12T21%3A52%3A34.071Z&job=test_full_earlyexit_bottomup_s0_5f%402019-02-12T21%3A37%3A42.489Z) and
With full length sequences, [AWCY result will come here probably tonight](https://beta.arewecompressedyet.com/?job=master-8eae88fc_s0%402019-02-12T21%3A42%3A20.715Z&job=test_full_earlyexit_bottomup_s0%402019-02-12T22%3A18%3A23.821Z).

**Comment by ycho** [comment]
As recap, the overall speedup at speed 0 (bottomup partition) by using early-exit is:
https://ibb.co/tM4Q6Xv
