### ISSUE TITLE
Never Ending task with a very low frame count .y4m file

### ISSUE THREAD

**Issue by moisesmcardona** [xiph/rav1e#890]
Hi everyone,

I've been encoding videos in my own distributed computing project. I've been doing this by splitting a video into 1-second segments with ffmpeg and then submitting each clip to the project.

While I'm able to encode most of my clips, this one which seems to have just a couple of frames is not working: https://drive.google.com/file/d/1dvewc7SwdE7BRFQUa2VsvcredixJuJ9_/view?usp=sharing

rav1e never seems to finish but uses 100% of the CPU thread, so it is doing something.

Parameters used are:
`--quantizer 175 -s 0 --low_latency false`

Is it stuck in a loop which seems to never finish and doesn't exit? I'm using rav1e 774b0d1, which is the latest commit as of this issue.

std output just stays as follows:
```
3840x2160 @ 30000/1001 fps

encoded 1 frames, 0.00 fps, 8493.22 Kb/s                    
```

**Comment by tdaede** [comment]
I can reproduce this. It never happens with low_latency true, so it probably has something to do with frame reordering.

**Comment by shssoichiro** [comment]
I think I have a fix for this. I'm going to do some more testing after lunch.

**Comment by moisesmcardona** [comment]
Thanks, I'll wait for the fix.

**Comment by shssoichiro** [comment]
As an update on this, I have a fix that passes manual tests, but the automated tests are hanging. I will open a PR as soon as I have the automated tests working.
