### ISSUE TITLE
Add keyframe numbers to (CLI) ouput

### ISSUE THREAD

**Issue by EwoutH** [xiph/rav1e#898]
Would be nice to get a CLI option that outputs the frame-numbers of the keyframes. A comma-seperated string would probably be most usefull (`1,82,196,245` i.e.).

Then you can do a turbo turbo pass, (speed 10, quarter resolution, etc.) to get the optimal keyframe placement, which can be used to split the video at the correct points for optimal encoding in chunks.

Maybe I have some time to implement this later, for now I will leave it here as an issue.

**Comment by shssoichiro** [comment]
I wonder if it makes sense to bake this into rav1e as a single "first-pass" option. Although a true first pass would require more analysis than just detecting keyframes, maybe this can be like an "alpha version" first pass.

**Comment by gnafuthegreat** [comment]
I like the idea overall, but I wonder if it's better kept in a separate tool (like https://github.com/tdaede/dve) since it seems it isn't really tied to rav1e or AV1 specifically.  I think improving existing tools, utilizing scene change detection from ffmpeg or similar, and having rav1e be an encoder option might be better than baking it in.  Distributed encoding of videos based on scene changes seems to be "the future" in general, so no need to restrict it to rav1e.

**Comment by tdaede** [comment]
I think having this inside rav1e makes sense. At some point our keyframe detection will get smarter than it currently is, using actual first pass encoding statistics to choose the best points to split. It makes sense as a first pass option

**Comment by moisesmcardona** [comment]
Exactly, having rav1e analyze the video makes the most sense to me as well. I currnetly split the video files into 1-second segments and feed it to my BOINC server, and sometimes that keyframe at the 1-second interval is noticeable.

**Comment by shssoichiro** [comment]
What are the thoughts on having rav1e output its stats file in some standardized format, e.g. JSON? In the past, if I wanted to parse output from xvid or x264's stats file to find the keyframes, I needed to write a custom parser. This would make that a bit easier by allowing use of existing parsers.

**Comment by tdaede** [comment]
I think that's a great idea. Also, having both a public and private stats file would make sense, where the private one can change each version (and might be binary). The public one might have less info but is defined as part of the API.
