### ISSUE TITLE
Investigate compressed 10-bit format

### ISSUE THREAD

**Issue by tdaede** [xiph/rav1e#906]
SVT-AV1 uses a bitplaned 10-bit format: https://github.com/OpenVisualCloud/SVT-AV1/blob/master/Docs/svt-av1_encoder_user_guide.pdf

We should look at if this makes any sense for us to do for speed.

**Comment by KyleSiefring** [comment]
vpmultishiftqb (_mm512_multishift_epi64_epi8) introduced in cannon lake could make this more efficient in the future.

**Comment by tdaede** [comment]
The main problem I have with this is that the loop filters in svt-av1 are applied on planar 16 bit data. This means you end up with both a 8+2->16 and 16->8+2 copy per frame. If you just wanted 8 bit mc, you could do a single 16->8 copy instead and it would be less memory bandwidth.
