### ISSUE TITLE
API Improvements

### ISSUE THREAD

**Issue by lu-zero** [xiph/rav1e#907]
- [x] Review the current API
- [x] Add proper timestamp support
- [x] Make sure that the MT usage is sound

**Comment by barrbrain** [comment]
"Add a mean to forward opaque data from Frames to Packets" #2298 at least enables timestamps to be bound to packets. Implementing VFR rate control is still TODO but this description is too terse to know if that was in scope.

**Comment by lu-zero** [comment]
https://github.com/xiph/rav1e/pull/2640 addresses the MT usage problems.

**Comment by vibhoothiiaanand** [comment]
@lu-zero are we good to close this

**Comment by lu-zero** [comment]
Yes. Thank you :)
