### ISSUE TITLE
AppVeyor access denied

### ISSUE THREAD

**Issue by EwoutH** [xiph/rav1e#935]
For regular users, https://ci.appveyor.com/project/xiph/rav1e displays the message `Project not found or access denied.`

![screenshot_384](https://user-images.githubusercontent.com/15776622/52327652-24a08b80-29ed-11e9-9407-c87491746fab.png)

**Comment by tdaede** [comment]
I can't figure out how to make this public :(

**Comment by rzumer** [comment]
The history page with artifacts is accessible, so that seems normal to me.

**Comment by EwoutH** [comment]
@tdaede No problem, let’s not waste too much time on it, PR #937 fixes it for now.
