### ISSUE TITLE
Temporal Delimiter OBUs are being inserted before every frame

### ISSUE THREAD

**Issue by jamrial** [xiph/rav1e#954]
TD OBUs are meant to be present at the beginning of a Temporal Unit, precisely to delimit them, and not before every frame, showable or not, within a given Temporal Unit. All these extra TDs are pointless overhead in the bitstream.

A simple "rav1e INPUT.y4m --output OUTPUT.ivf" seems to be enough to reproduce this. In my tests i used https://0x0.st/sfRh.y4m.

**Comment by tdaede** [comment]
Emitting them every frame is actually wrong and I'm a bit surprised we decode correctly as-is.
