### ISSUE TITLE
ivf dumper for encode/decode tests

### ISSUE THREAD

**Issue by tdaede** [xiph/rav1e#976]
When encode/decode tests mismatch, it would be nice to dump the mismatching bitstream to an .ivf file for easy reporting to other projects' bug trackers.

**Comment by lu-zero** [comment]
I have it somewhere, shall I prepare it with an additional feature to turn it on and off?

**Comment by tdaede** [comment]
Sure. In this case just even having it as commented out code in the tree that you could enable would be ok, I think?

**Comment by lu-zero** [comment]
the muxer code got moved to bin this week, I guess we could either push it back or duplicate it :P

**Comment by shssoichiro** [comment]
+1 for moving it back or making a separate crate for it.
