### ISSUE TITLE
Visual artifacts when running at speed 0

### ISSUE THREAD

**Issue by shssoichiro** [xiph/rav1e#978]
See http://screenshotcomparison.com/comparison/129784 and http://screenshotcomparison.com/comparison/129783 for examples. The artifacts are more visible with Psy, but are also present with Psnr tuning.

The only setting enabled at only speed 0 is bottom-up encoding, so this is likely related to that setting.

**Comment by utack** [comment]
Source is  
http://movietrailers.apple.com/movies/universal/johnny-english-strikes-again/johnny-english-strikes-again-trailer-1_h1080p.mov  
commandline  
`ffmpeg -nostats -i johnny-english-strikes-again-trailer-1_h1080p.mov -pix_fmt yuv420p  -f yuv4mpegpipe - | rav1e - -v --output 0psy.ivf -s 0 --low_latency false  --tune psychovisual
`

**Comment by tdaede** [comment]
This seems to be a mismatch in one of the SMOOTH intra predictors.

**Comment by shssoichiro** [comment]
Closing this one and tracking in #987, that one is more specific as to the root cause.

**Comment by ycho** [comment]
I believe we have not confirmed that the reason for this case is the same to 
the mismatch between encoder and decoder?

**Comment by shssoichiro** [comment]
I thought that was the case from the IRC conversations, but feel free to reopen if I'm wrong.

**Comment by ycho** [comment]
Verified that #989, https://github.com/xiph/rav1e/commit/8eae88fcda424c6cf0819102c1b7faaecde53d08 fixed the mismatch and the banded (brightened or darkened) artifacts.
