### ISSUE TITLE
Directional intra prediction modes cause mismatch between encoder and decoder

### ISSUE THREAD

**Issue by ycho** [xiph/rav1e#987]
Since one function,  pred_directional(), is called by all those six directional prediction modes, the function is likely have a bug.

Try fix this issue at commit af9d4ab530e4bd4, because the commit after it seems to have another bug that also causes mismatch between encoder and decoder.

**Comment by shssoichiro** [comment]
Duplicate of https://github.com/xiph/rav1e/issues/978, but I'm going to close that one because this one is more specific/accurate.
