### ISSUE TITLE
add a mp4 muxer

### ISSUE THREAD

**Issue by kodabb** [xiph/rav1e#998]
in order to favor usability of the command line encoder, we should add a mp4 (isomedia) muxer following the spec available https://aomediacodec.github.io/av1-isobmff/

writing a full mp4 muxer is a pretty big task, so it could be simpler to use a separate library. Some possible candidates are
* l-smash, https://github.com/l-smash/l-smash/compare/av1, currently not working
* libavformat, seems to work, but there still might be some compatibility problems
* gpac, currently used to mux the chimera streams

**Comment by tdaede** [comment]
Another reason this is nice is because .ivf doesn't signal keyframes, requiring a remuxer to have an AV1 parser.
